import type { BlogArticle } from "../types";

export const onPageSeoForEcommerce: BlogArticle = {
  slug: "on-page-seo-for-ecommerce",
  category: "on-page",
  publishDate: "2025-06-22",
  readingTime: 12,
  author: "Fabian van Til",
  authorRole: "CEO at EcomSEO",
  authorSlug: "fabian-van-til",
  primaryKeyword: "on-page seo for ecommerce",
  secondaryKeywords: [
    "ecommerce on-page optimization",
    "on-page seo ecommerce",
    "on-page optimization for online stores",
  ],
  content: {
    en: {
      title: "On-Page SEO for Ecommerce: Pages That Convert",
      description: "Master on-page SEO for ecommerce with actionable tips on title tags, meta descriptions, image optimization, schema markup, and internal linking.",
      sections: [
        {
          heading: "On-page SEO is where ecommerce stores win or lose",
          body: [
            "Technical SEO gets your pages crawled. Link building gives them authority. But on-page SEO is what tells Google (and your customers) exactly what each page is about and why it should rank. For ecommerce stores, on-page optimization has an outsized impact because you are working with hundreds or thousands of pages that often look very similar to search engines.",
            "We have seen stores double their organic traffic just by fixing on-page elements, without building a single link or publishing a single blog post. That is because most ecommerce sites have systemic on-page problems: duplicate title tags generated by templates, missing meta descriptions, thin content on category pages, and product pages that are indistinguishable from competitors using the same manufacturer copy.",
            "The good news is that on-page SEO is entirely within your control. You do not need to convince anyone to link to you. You do not need to wait for Google to recrawl your site after a technical fix. You can make changes today and start seeing results within weeks. Our [premium on-page SEO checklist](/premium-on-page-seo-checklist) gives you a structured workflow to follow.",
          ],
        },
        {
          heading: "Title tags that drive clicks and rankings",
          body: [
            "The title tag is still the single most influential on-page ranking factor. It also determines your click-through rate from search results, which makes it a double win when you get it right.",
            "For product pages, we use this formula: [Product Name] - [Key Differentiator] | [Brand]. The key differentiator should be whatever makes the product stand out: the material, a feature, or the use case. 'Merino Wool Crew Neck Sweater - Lightweight, Machine Washable | Woolmark' tells the searcher exactly what they will find. Keep titles under 60 characters to avoid truncation. If you must go over, front-load the important keywords because they will always be visible.",
            "For category pages, include the primary keyword and a value proposition: 'Women's Running Shoes - Free Shipping Over $75 | ShoeStore.' Category page titles should match the language people actually search. If your keyword research shows people search for 'women's running shoes' more than 'ladies' running trainers,' use the more common phrasing.",
            "Common mistakes we see: using the same title tag template for every page ('[Product Name] | [Store Name]' on 2,000 pages), stuffing multiple keywords into one title ('Buy Women's Running Shoes, Ladies' Joggers, Female Athletic Shoes'), and forgetting to include the brand name. Your brand name builds recognition over time and improves click-through rates once people know you.",
            "Run a crawl with Screaming Frog and export all title tags. Sort by length (flag anything over 60 characters or under 30), check for duplicates, and identify pages where the title does not match the primary keyword you want to rank for. Fix the worst offenders first. Our [meta tag analyzer tool](/tools/meta-tag-analyzer) lets you preview and audit title tags across your key pages.",
          ],
        },
        {
          heading: "Meta descriptions that sell the click",
          body: [
            "Google rewrites meta descriptions frequently. We have measured this across our client portfolio and found that Google uses the original meta description about 30-35% of the time for product pages and about 40-45% of the time for category pages. Those percentages are worth optimizing for.",
            "Think of the meta description as ad copy, because that is exactly what it is. You are competing for clicks against 9 other results on the page. For product pages, include the product name, price (if competitive), a key benefit, and a soft call to action: 'Shop the CloudFoam Ultra running shoe ($89.99). Memory foam insole, breathable mesh upper, and free returns. Find your size today.' That is 148 characters and contains everything a searcher needs to decide whether to click.",
            "For category pages, focus on selection and value: 'Browse 200+ women's running shoes from Nike, ASICS, and Brooks. Free shipping on orders over $75. New arrivals weekly.' This tells the searcher they will find variety, recognized brands, and a good deal.",
            "Do not write meta descriptions that could apply to any page on any store. 'Shop our great selection of products at competitive prices' says nothing. Every description should be specific to that exact page. Yes, writing unique descriptions for 2,000 product pages takes time. Prioritize your top 100 pages by organic traffic and work outward from there.",
          ],
        },
        {
          heading: "URL structure and heading hierarchy",
          body: [
            "Clean URLs are a small ranking factor but a big usability factor. A URL like /womens/running-shoes/nike-air-zoom-pegasus-40 tells both users and search engines exactly what the page contains. A URL like /product?id=48271&cat=shoes tells nobody anything.",
            "Keep URLs short and descriptive. Remove unnecessary words like 'the,' 'and,' 'of.' Use hyphens between words, never underscores. Avoid putting dates in product or category URLs because they become outdated. Keep your folder structure shallow: two levels deep is ideal, three is acceptable. Anything deeper starts to dilute link equity.",
            "For heading hierarchy, every page gets exactly one H1. On product pages, the H1 is the product name. On category pages, it is the category name. H2s break up the page content into logical sections (product description, specifications, reviews). H3s go under H2s for subsections. Do not skip levels: going from H1 to H3 without an H2 between them is sloppy and confuses the content hierarchy.",
            "We see a recurring problem with ecommerce themes that put the store name or a promotional banner as the H1, then use H2 for the actual product or category name. This is backwards. The H1 should always be the primary topic of the page. Check your page source, use a browser extension like HeadingsMap, or run our [heading structure checker](/tools/heading-checker) to audit your heading hierarchy.",
          ],
        },
        {
          heading: "Image optimization for speed and search",
          body: [
            "Ecommerce sites are image-heavy by nature. A single product page might have 6-10 images. Multiply that by thousands of products and images become both your biggest SEO asset and your biggest performance liability.",
            "Start with file format. Use WebP for all product images. It provides 25-35% smaller file sizes compared to JPEG at equivalent quality. If you need to support older browsers, serve WebP with a JPEG fallback using the HTML picture element. Most modern ecommerce platforms handle this automatically if you configure the image settings correctly.",
            "Compress images before uploading. A product photo straight from a camera might be 4-8MB. After compression and resizing to web dimensions (typically 1200px wide for product images), that same image should be under 100KB. Use tools like TinyPNG, ShortPixel, or your CDN's built-in optimization. We audited one fashion store where product images averaged 1.2MB each. After optimization, they averaged 85KB. Page load time dropped by 3.4 seconds on mobile.",
            "File names matter. Rename images from IMG_4827.jpg to something descriptive like navy-blue-wool-crew-neck-sweater-front.webp before uploading. Some platforms rename files automatically, which eliminates this opportunity. If yours does, focus on alt text instead.",
            "Alt text should describe the image for someone who cannot see it. 'Front view of a navy blue merino wool crew neck sweater on a white background' is good. 'Sweater' is too vague. 'Best sweater buy cheap sweater men's sweater wool sweater 2026' is keyword stuffing and helps nobody. Include the product name naturally in at least one alt tag per product page.",
            "Implement lazy loading for images below the fold. This means the browser only loads images as the user scrolls to them, which dramatically improves initial page load time. But do not lazy load the main product image (the first image visible on load), because that will hurt your LCP score.",
          ],
        },
        {
          heading: "Schema markup for rich search results",
          body: [
            "Schema markup is the closest thing to a cheat code in ecommerce SEO. It does not directly affect rankings (Google has said this), but it dramatically increases click-through rates by adding visual elements to your search result: star ratings, prices, availability badges, and more. Use our [schema generator tool](/tools/schema-generator) to build the correct JSON-LD for your product pages.",
            "Every product page needs Product schema. The required properties are name, image, and at least one of offers (price/availability) or aggregateRating (review stars). But do not stop at the minimum. Include brand, SKU, GTIN (barcode number), description, and review count. The more data you provide, the more likely Google is to display a rich snippet.",
            "Category pages benefit from CollectionPage or ItemList schema, where you mark up the list of products on the page. This can generate a carousel-style rich result in some cases. FAQ schema on category pages (for the FAQ section you should definitely have) can also win additional SERP real estate.",
            "BreadcrumbList schema is often overlooked but easy to implement. It replaces the default URL display in search results with a clickable breadcrumb trail, which looks cleaner and gets higher click-through rates. If your breadcrumb shows 'Home > Women's Shoes > Running Shoes,' that is far more useful to a searcher than seeing 'yourstore.com/womens/running/shoes.'",
            "Validate your schema regularly. Use Google's Rich Results Test on individual pages and check the Enhancements section in Search Console for site-wide schema errors. Schema errors can silently prevent your rich snippets from showing. We check this weekly for client accounts and fix issues before they accumulate.",
          ],
        },
        {
          heading: "Internal linking strategy for ecommerce",
          body: [
            "Internal linking is the most underused on-page tactic in ecommerce. It controls how link equity flows through your site, helps Google discover and understand pages, and guides users toward conversion. Yet most stores treat it as an afterthought. Our [complete ecommerce SEO guide](/blog/ecommerce-seo) covers how internal linking fits into the broader optimization framework. For a hands-on tutorial, the [internal linking for stores](/academy/internal-linking-for-stores) academy lesson walks through setup step by step.",
            "The foundation is your site architecture. Your homepage should link to top-level categories. Categories should link to subcategories. Subcategories should link to products. Products should link back to their parent category and to related products. This creates a logical hierarchy that makes sense for both users and crawlers.",
            "Beyond the structural links, add contextual internal links. Product descriptions should link to complementary products ('Pairs well with our [leather belt]'). Category page descriptions should link to buying guides and related categories. Blog posts should link to relevant product and category pages using descriptive anchor text.",
            "Anchor text matters for internal links. Google uses anchor text to understand what the linked page is about. If you want your category page to rank for 'women's running shoes,' link to it with that phrase as the anchor text, not 'click here' or 'see more.' Vary your anchor text slightly across different pages (use 'women's running shoes,' 'running shoes for women,' 'shop women's runners') to avoid looking manipulative.",
            "Run a regular internal link audit. Identify pages with fewer than 5 internal links pointing to them. These are likely underperforming because they receive minimal link equity. Also check for broken internal links, which waste link equity and create poor user experiences. Screaming Frog's internal linking report makes this straightforward. One client discovered that 200+ product pages had zero internal links beyond the category grid. After adding contextual links from related products and blog content, those pages saw an average ranking improvement of 8 positions over two months.",
          ],
        },
        {
          heading: "Content optimization beyond keywords",
          body: [
            "Keyword placement still matters, but Google has become much better at understanding topics rather than exact-match keywords. Your primary keyword should appear in the title tag, H1, first paragraph, and URL. After that, focus on writing naturally and covering the topic thoroughly.",
            "For product pages, write descriptions that answer the questions shoppers actually have. Do not just list specifications. Explain who the product is for, what problems it solves, how it compares to alternatives, and what makes it worth the price. Include specific measurements, materials, and care instructions. This kind of detailed content naturally includes keyword variations without forcing them.",
            "For category pages, the description text above or below the product grid should serve as a mini buying guide. Cover what the category includes, who should buy from it, what factors to consider when choosing, and what makes your selection different. This is where most ecommerce stores fall short. They either have no description or a two-sentence afterthought. Our [category page SEO guide](/blog/ecommerce-category-page-seo) goes deeper on this topic.",
            "User-generated content is an on-page SEO goldmine. Reviews, Q&A sections, and customer photos add unique, keyword-rich content to your pages automatically. A product page with 50 reviews contains hundreds of natural keyword variations that you never had to write. Enable and encourage reviews on every product page. Display them prominently. Respond to them. This content refreshes your pages and sends freshness signals to Google.",
            "Page experience signals are part of on-page SEO now. Google measures how users interact with your pages. If visitors bounce immediately, that tells Google the page did not satisfy the query. Make sure your pages load fast, display content above the fold without requiring a scroll, have clear calls to action, and provide the information the searcher is looking for. A beautiful page that does not answer the search query will not rank well, no matter how perfectly optimized the title tag is.",
          ],
        },
      ],
    },
  },
};
