import type { AcademyTopic } from "../../types";

export const keywordMappingForStores: AcademyTopic = {
  slug: "keyword-mapping-for-stores",
  cluster: 2,
  resources: [{"label":"Google Sheets","url":"https://sheets.google.com/","type":"tool"},{"label":"Screaming Frog SEO Spider","url":"https://www.screamingfrog.co.uk/seo-spider/","type":"tool"},{"label":"Google Search Console","url":"https://search.google.com/search-console","type":"tool"}],
  content: {
    en: {
      badge: "Keyword Research",
      heading: "Keyword Mapping for Online Stores",
      intro:
        "A keyword map assigns specific target keywords to specific URLs in your store. Without one, you end up with multiple pages competing for the same terms, wasted optimization effort, and missed opportunities where no page targets a proven keyword at all. For stores with hundreds or thousands of products, a keyword map is the difference between organized SEO growth and chaos.",
      readTime: "9 min read",
      sections: [
        {
          title: "What a Keyword Map Is and Why Your Store Needs One",
          content:
            "A keyword map is a document, usually a spreadsheet, that creates a one-to-one relationship between each URL on your site and the primary keyword that URL should rank for. Each URL also gets 2-3 secondary keywords and a note about search intent. Think of it as a seating chart for your keywords: every term has an assigned seat, and no two guests sit in the same chair.\n\nWithout a keyword map, ecommerce sites inevitably develop keyword cannibalization. Your category page for \"leather boots\" and your blog post titled \"Best Leather Boots for Winter\" fight each other in search results. Google sees both pages targeting the same query and either picks the wrong one or suppresses both. We've seen stores lose 30-40% of their organic traffic to cannibalization problems that a keyword map would have prevented.\n\nThe map also exposes coverage gaps. When you list every URL alongside its primary keyword, you quickly spot high-volume keywords that have no assigned page. Maybe you sell dozens of running shoes but have no category page specifically targeting \"trail running shoes\", a 12,000 monthly search volume term going completely unaddressed.\n\nFor stores running on Shopify, WooCommerce, or Magento, the keyword map becomes your content planning bible. Every new product page, every new collection, every blog post gets a keyword assignment before it's created. This prevents the reactive approach where you build pages first and try to figure out what they should rank for afterward.",
          items: [
            "Each URL gets exactly one primary keyword and 2-3 secondary keywords",
            "The map prevents cannibalization by ensuring no keyword is assigned to multiple pages",
            "Coverage gaps become visible when you see keywords with no assigned URL",
            "New pages should receive keyword assignments before they are created, not after",
          ],
        },
        {
          title: "Building Your Keyword Map: The Spreadsheet Structure",
          content:
            "Your keyword map spreadsheet needs seven columns at minimum. Column one is the URL (the actual page path). Column two is the page type: product, category, subcategory, blog post, or landing page. Column three is the primary keyword, the single most important term this page should rank for. Column four holds secondary keywords, usually 2-3 related variations. Column five is the monthly search volume for the primary keyword. Column six is the current ranking position, if any. Column seven is the search intent: navigational, informational, commercial, or transactional.\n\nStart by exporting all your existing URLs. Pull your sitemap or use Screaming Frog to crawl the site. For a store with 500 products, 30 categories, and 20 blog posts, you'll have roughly 550 rows. Then export your keyword research data, every keyword you've identified through your research process, and begin assigning terms to URLs.\n\nCategory pages get the broadest, highest-volume terms. \"Women's running shoes\" goes to the women's running shoe [category page](/academy/category-page-seo), not to an individual product. Product pages get specific, long-tail terms that describe exactly what that product is. \"Nike Air Zoom Pegasus 40 women's\" maps to that specific product page.\n\nBlog and guide pages get informational keywords. \"How to choose running shoes for flat feet\" maps to a buying guide, not to a product page. This intent-based assignment is critical, mapping an informational keyword to a product page won't work because Google expects informational content for that query.",
          tip: "Color-code your spreadsheet rows by page type. Categories in blue, products in green, blog posts in yellow. This makes it easy to scan the map and spot patterns, like if you've accidentally assigned a commercial keyword to a blog post instead of a category page.",
        },
        {
          title: "Assigning Primary and Secondary Keywords",
          content:
            "The primary keyword for each page should meet three criteria. First, it matches the page's search intent, a transactional keyword for a product page, a commercial keyword for a category page, an informational keyword for a guide. Second, only one page in your entire store targets this primary keyword. Third, the keyword has meaningful search volume relative to your niche.\n\nSecondary keywords are close variations of the primary keyword that the same page can naturally rank for. If the primary keyword for a category page is \"organic baby clothes,\" secondary keywords might be \"organic baby clothing,\" \"organic cotton baby outfits,\" and \"natural baby clothes.\" These are variations Google already associates with the same intent, so a single well-optimized page can capture all of them.\n\nAvoid assigning secondary keywords that have different intent from the primary keyword. \"Organic baby clothes\" (commercial) and \"are organic baby clothes worth it\" (informational) should not be on the same page, the informational query belongs on a blog post or guide page.\n\nFor product pages, the primary keyword is usually the product name plus its key differentiator. \"Ergobaby Omni 360 carrier\" is a product-level primary keyword. Secondary keywords add modifiers: \"Ergobaby Omni 360 review,\" \"Ergobaby Omni 360 all positions baby carrier.\" If search volume data shows people search for both the brand name format and a generic descriptor, assign the higher-volume version as primary.",
          items: [
            "Primary keywords must match the page's intent, transactional for products, commercial for categories",
            "Each primary keyword appears only once across your entire keyword map",
            "Secondary keywords are close variations that share the same search intent",
            "Product page primaries combine product name with key differentiators",
          ],
        },
        {
          title: "Detecting and Fixing Keyword Cannibalization",
          content:
            "Cannibalization occurs when two or more pages on your site target the same keyword, forcing Google to choose which one to rank. The result is usually neither page ranking as well as a single focused page would. In ecommerce, the most common cannibalization happens between category pages and blog posts, or between overlapping subcategory pages.\n\nTo detect cannibalization, search Google for \"site:yourstore.com keyword\" for each of your primary keywords. If two or more pages appear, you have a conflict. A more systematic approach uses Google Search Console: go to Performance, filter by query, and check the Pages tab. If multiple URLs receive impressions for the same query, Google is splitting signals between them.\n\nAhrefs and Semrush also flag cannibalization. In Semrush, the Cannibalization report under Position Tracking highlights keywords where multiple URLs from your domain appear in search results. The report shows which URL Google currently prefers and which ones are competing.\n\nFixes depend on the situation. If a blog post and a category page both target \"leather boots for men,\" you have three options. Option one: refocus the blog post on an informational variant like \"how to style leather boots\" and add an internal link to the category page. Option two: merge the content if the blog post has strong backlinks, redirecting it to the category page and incorporating the best content. Option three: use a canonical tag on the blog post pointing to the category page, though this is the weakest signal.\n\nThe best fix is always prevention. When your keyword map is in place and every new page gets a keyword assignment before publication, cannibalization rarely occurs.",
          tip: "After fixing a cannibalization issue, monitor the surviving page's rankings for 4-6 weeks. You should see a ranking improvement within that window as Google consolidates signals onto a single URL. If rankings don't improve, check that internal links and canonical tags are correctly pointing to the intended page.",
        },
        {
          title: "Mapping Keywords Across Page Types",
          content:
            "An ecommerce store typically has four page types that need keyword assignments: category pages, product pages, blog/guide pages, and informational or brand pages. Each type serves a different role in your keyword funnel.\n\nCategory pages capture the highest-volume commercial keywords. These are your money pages, \"women's running shoes,\" \"organic skincare,\" \"wireless headphones under 100.\" Category pages typically target keywords with 1,000 to 50,000+ monthly searches. Because these terms are competitive, category pages need strong content, internal linking, and often backlinks to rank.\n\nProduct pages target specific, long-tail transactional keywords. Each product page maps to the product's exact name and closest variant searches. Volume per keyword is lower (often 50-500 searches per month), but you have hundreds or thousands of product pages, so the aggregate traffic is significant.\n\nBlog and guide pages handle informational queries that feed your sales funnel. \"How to choose a running shoe for overpronation\" brings in potential buyers who haven't decided on a [product page](/academy/product-page-seo) yet. These pages link to relevant category and product pages, creating a content-to-commerce pathway.\n\nBrand and comparison pages sit between informational and transactional intent. \"Nike vs Adidas running shoes\" or \"best running shoes 2025\" capture comparison shoppers. These pages are keyword-mapped like blog posts but typically have higher conversion potential because the intent is closer to purchase.",
          image: {
            src: "/images/academy/keyword-map-structure.svg",
            alt: "Table showing how different page types map to keyword intent levels with example keywords and volume ranges",
            caption: "Each page type serves a distinct role in the keyword funnel. Category pages handle commercial intent, product pages handle transactional, and blogs handle informational.",
          },
          items: [
            "Category pages target broad commercial keywords with the highest volume",
            "Product pages target specific long-tail terms matching exact product names",
            "Blog pages capture informational queries that feed potential buyers into the funnel",
          ],
          callout: {
            title: "Cannibalization Cost",
            text: "Stores without a keyword map lose 30-40% of organic traffic to cannibalization. The fix takes weeks to diagnose but only 5 minutes to prevent: check the map before every new page goes live.",
          },
        },
        {
          title: "Maintaining Your Keyword Map Over Time",
          content:
            "A keyword map is a living document, not a one-time project. Every time you add a new product, create a new category, or publish a blog post, the map needs an update. We recommend reviewing the full map quarterly, but incremental updates should happen in real time as new pages go live.\n\nSet a process: before any new page is created, the content or SEO team checks the keyword map. Is there already a page targeting this keyword? If yes, either refocus the new page on a different keyword or merge it with the existing page. This five-minute check prevents cannibalization issues that take weeks to diagnose and fix later.\n\nQuarterly reviews should include three tasks. First, update ranking positions for all primary keywords. Export current rankings from your tracking tool and paste them into the map. This shows which pages are improving, stagnating, or declining. Second, check for new keyword opportunities from your research pipeline and assign them to existing or planned pages. Third, remove discontinued products or archived pages and reassign their keywords if the terms still have value.\n\nFor larger stores with thousands of products, consider automating parts of this process. A Python script that pulls ranking data from an API and updates your spreadsheet saves hours of manual work. Some teams move from spreadsheets to database-backed tools like Airtable or Notion for easier collaboration and filtering.\n\nThe keyword map also becomes your reporting foundation. When leadership asks why organic traffic grew 15% last quarter, you can point to specific keywords that were assigned, pages that were optimized, and rankings that improved, all tracked in one document. For a broader view of how keyword mapping fits into your overall approach, see our [ecommerce SEO strategy](/blog/ecommerce-seo-strategy) guide.",
        },
      ],
      navLabels: {
        previous: "Competitor Keyword Analysis",
        next: "Seasonal Keyword Trends",
      },
    },
    de: {
      badge: "Keyword-Recherche",
      heading: "Keyword-Mapping für Online-Shops",
      intro:
        "Ein Keyword-Map ordnet bestimmte Ziel-Keywords bestimmten URLs in Ihrem Shop zu. Ohne eine solche Zuordnung konkurrieren mehrere Seiten um dieselben Begriffe, Optimierungsaufwand wird verschwendet und Chancen bleiben ungenutzt, weil keine Seite auf ein bewährtes Keyword abzielt. Für Shops mit Hunderten oder Tausenden von Produkten ist ein Keyword-Map der Unterschied zwischen organisiertem SEO-Wachstum und Chaos.",
      readTime: "9 Min. Lesezeit",
      sections: [
        {
          title: "Was ein Keyword-Map ist und warum Ihr Shop einen braucht",
          content:
            "Ein Keyword-Map ist ein Dokument, meist eine Tabelle, das eine Eins-zu-Eins-Beziehung zwischen jeder URL auf Ihrer Website und dem primären Keyword herstellt, für das diese URL ranken soll. Jede URL erhält außerdem 2-3 sekundäre Keywords und einen Hinweis zur Suchintention. Stellen Sie es sich wie eine Sitzordnung für Ihre Keywords vor: Jeder Begriff hat einen zugewiesenen Platz, und kein Gast sitzt auf demselben Stuhl.\n\nOhne Keyword-Map entwickeln E-Commerce-Websites unweigerlich Keyword-Kannibalisierung. Ihre Kategorieseite für „Lederstiefel“ und Ihr Blogbeitrag mit dem Titel „Beste Lederstiefel für den Winter“ konkurrieren in den Suchergebnissen miteinander. Google sieht beide Seiten auf dieselbe Suchanfrage ausgerichtet und wählt entweder die falsche oder unterdrückt beide. Wir haben erlebt, dass Shops 30-40% ihres organischen Traffics durch Kannibalisierungsprobleme verloren haben, die ein Keyword-Map verhindert hätte.\n\nDas Map deckt auch Lücken in der Abdeckung auf. Wenn Sie jede URL neben ihrem primären Keyword auflisten, erkennen Sie schnell Keywords mit hohem Suchvolumen, denen keine Seite zugewiesen ist. Vielleicht verkaufen Sie Dutzende von Laufschuhen, haben aber keine Kategorieseite, die speziell auf „Trailrunning-Schuhe“ abzielt, ein Begriff mit 12.000 monatlichen Suchanfragen, der völlig unbearbeitet bleibt.\n\nFür Shops, die auf Shopify, WooCommerce oder Magento laufen, wird der Keyword-Map zur Content-Planungsbibel. Jede neue Produktseite, jede neue Kollektion, jeder Blogbeitrag erhält eine Keyword-Zuordnung, bevor er erstellt wird. Dies verhindert den reaktiven Ansatz, bei dem Sie zuerst Seiten erstellen und dann versuchen herauszufinden, wofür sie ranken sollen.",
          items: [
            "Jede URL erhält genau ein primäres Keyword und 2-3 sekundäre Keywords",
            "Das Map verhindert Kannibalisierung, indem sichergestellt wird, dass kein Keyword mehreren Seiten zugewiesen ist",
            "Abdeckungslücken werden sichtbar, wenn Keywords ohne zugewiesene URL erscheinen",
            "Neue Seiten sollten Keyword-Zuordnungen erhalten, bevor sie erstellt werden, nicht danach",
          ],
        },
        {
          title: "Aufbau Ihres Keyword-Maps: Die Tabellenstruktur",
          content:
            "Ihre Keyword-Map-Tabelle benötigt mindestens sieben Spalten. Spalte eins ist die URL (der tatsächliche Seitenpfad). Spalte zwei ist der Seitentyp: Produkt, Kategorie, Unterkategorie, Blogbeitrag oder Landingpage. Spalte drei ist das primäre Keyword, der einzelne wichtigste Begriff, für den diese Seite ranken soll. Spalte vier enthält sekundäre Keywords, in der Regel 2-3 verwandte Variationen. Spalte fünf ist das monatliche Suchvolumen für das primäre Keyword. Spalte sechs ist die aktuelle Ranking-Position, falls vorhanden. Spalte sieben ist die Suchintention: navigational, informational, kommerziell oder transaktional.\n\nBeginnen Sie mit dem Export aller vorhandenen URLs. Ziehen Sie Ihre Sitemap heran oder verwenden Sie Screaming Frog, um die Website zu crawlen. Für einen Shop mit 500 Produkten, 30 Kategorien und 20 Blogbeiträgen haben Sie etwa 550 Zeilen. Exportieren Sie dann Ihre Keyword-Recherche-Daten, jedes Keyword, das Sie in Ihrem Rechercheprozess identifiziert haben, und beginnen Sie mit der Zuordnung der Begriffe zu URLs.\n\n[Kategorieseite](/academy/category-page-seo)n erhalten die breitesten Keywords mit dem höchsten Suchvolumen. „Damen Laufschuhe“ geht auf die Kategorieseite für Damen-Laufschuhe, nicht auf ein einzelnes Produkt. Produktseiten erhalten spezifische Long-Tail-Begriffe, die genau beschreiben, was das Produkt ist. „Nike Air Zoom Pegasus 40 Damen“ wird dieser spezifischen Produktseite zugeordnet.\n\nBlog- und Ratgeberseiten erhalten informationale Keywords. „Wie wähle ich Laufschuhe bei Plattfüßen“ wird einem Kaufratgeber zugeordnet, nicht einer Produktseite. Diese intentionsbasierte Zuordnung ist entscheidend, ein informationales Keyword einer Produktseite zuzuordnen funktioniert nicht, weil Google für diese Anfrage informationale Inhalte erwartet.",
          tip: "Verwenden Sie Farbcodierung für die Zeilen Ihrer Tabelle nach Seitentyp. Kategorien in Blau, Produkte in Grün, Blogbeiträge in Gelb. So können Sie das Map leicht scannen und Muster erkennen, etwa wenn Sie versehentlich ein kommerzielles Keyword einem Blogbeitrag statt einer Kategorieseite zugewiesen haben.",
        },
        {
          title: "Primäre und sekundäre Keywords zuweisen",
          content:
            "Das primäre Keyword für jede Seite sollte drei Kriterien erfüllen. Erstens: Es stimmt mit der Suchintention der Seite überein, ein transaktionales Keyword für eine Produktseite, ein kommerzielles Keyword für eine Kategorieseite, ein informationales Keyword für einen Ratgeber. Zweitens: Nur eine Seite in Ihrem gesamten Shop zielt auf dieses primäre Keyword ab. Drittens: Das Keyword hat ein bedeutsames Suchvolumen relativ zu Ihrer Nische.\n\nSekundäre Keywords sind nahe Variationen des primären Keywords, für die dieselbe Seite natürlich ranken kann. Wenn das primäre Keyword einer Kategorieseite „Bio-Babykleidung“ ist, könnten sekundäre Keywords „Babykleidung Bio-Baumwolle,“ „Ökologische Baby-Outfits“ und „Natürliche Babykleidung“ sein. Dies sind Variationen, die Google bereits mit derselben Intention verknüpft, sodass eine einzelne gut optimierte Seite alle erfassen kann.\n\nVermeiden Sie die Zuweisung sekundärer Keywords mit anderer Intention als das primäre Keyword. „Bio-Babykleidung“ (kommerziell) und „lohnt sich Bio-Babykleidung“ (informational) sollten nicht auf derselben Seite sein, die informationale Anfrage gehört zu einem Blogbeitrag oder einer Ratgeberseite.\n\nBei Produktseiten ist das primäre Keyword in der Regel der Produktname plus sein wichtigstes Unterscheidungsmerkmal. „Ergobaby Omni 360 Trage“ ist ein Keyword auf Produktebene. Sekundäre Keywords fügen Modifikatoren hinzu: „Ergobaby Omni 360 Test,“ „Ergobaby Omni 360 Alle-Positionen-Babytrage.“ Wenn Suchvolumendaten zeigen, dass Menschen sowohl nach dem Markennamenformat als auch nach einer generischen Beschreibung suchen, weisen Sie die Version mit höherem Volumen als primäres Keyword zu.",
          items: [
            "Primäre Keywords müssen zur Intention der Seite passen, transaktional für Produkte, kommerziell für Kategorien",
            "Jedes primäre Keyword erscheint nur einmal in Ihrem gesamten Keyword-Map",
            "Sekundäre Keywords sind nahe Variationen mit derselben Suchintention",
            "Primäre Keywords für Produktseiten kombinieren Produktname mit wichtigen Unterscheidungsmerkmalen",
          ],
          image: {
            src: "/images/academy/de/keyword-map-structure.svg",
            alt: "Tabelle, die zeigt, wie verschiedene Seitentypen Keyword-Intentionsstufen zugeordnet werden",
            caption: "Jeder Seitentyp erfüllt eine bestimmte Rolle im Keyword-Trichter.",
          },
          callout: {
            title: "Kannibalisierungskosten",
            text: "Shops ohne Keyword-Map verlieren 30–40 % ihres organischen Traffics durch Kannibalisierung.",
          },
        },
        {
          title: "Keyword-Kannibalisierung erkennen und beheben",
          content:
            "Kannibalisierung tritt auf, wenn zwei oder mehr Seiten auf Ihrer Website auf dasselbe Keyword abzielen und Google gezwungen ist zu wählen, welche ranken soll. Das Ergebnis ist normalerweise, dass keine der Seiten so gut rankt, wie eine einzelne fokussierte Seite es würde. Im E-Commerce tritt die häufigste Kannibalisierung zwischen Kategorieseiten und Blogbeiträgen oder zwischen sich überschneidenden Unterkategorieseiten auf.\n\nUm Kannibalisierung zu erkennen, suchen Sie bei Google nach „site:ihrshop.de keyword“ für jedes Ihrer primären Keywords. Wenn zwei oder mehr Seiten erscheinen, haben Sie einen Konflikt. Ein systematischerer Ansatz nutzt die Google Search Console: Gehen Sie zu Leistung, filtern Sie nach Suchanfrage und prüfen Sie den Tab Seiten. Wenn mehrere URLs Impressionen für dieselbe Anfrage erhalten, teilt Google die Signale zwischen ihnen auf.\n\nAhrefs und Semrush kennzeichnen ebenfalls Kannibalisierung. In Semrush hebt der Kannibalisierungsbericht unter Position Tracking Keywords hervor, bei denen mehrere URLs Ihrer Domain in den Suchergebnissen erscheinen. Der Bericht zeigt, welche URL Google derzeit bevorzugt und welche konkurrieren.\n\nDie Lösung hängt von der Situation ab. Wenn ein Blogbeitrag und eine Kategorieseite beide auf „Lederstiefel Herren“ abzielen, haben Sie drei Optionen. Option eins: Den Blogbeitrag auf eine informationale Variante wie „Lederstiefel richtig stylen“ umfokussieren und einen internen Link zur Kategorieseite hinzufügen. Option zwei: Die Inhalte zusammenführen, wenn der Blogbeitrag starke Backlinks hat, ihn auf die Kategorieseite weiterleiten und die besten Inhalte integrieren. Option drei: Ein Canonical-Tag auf dem Blogbeitrag verwenden, das auf die Kategorieseite zeigt, obwohl dies das schwächste Signal ist.\n\nDie beste Lösung ist immer Prävention. Wenn Ihr Keyword-Map vorhanden ist und jede neue Seite vor der Veröffentlichung eine Keyword-Zuordnung erhält, tritt Kannibalisierung selten auf.",
          tip: "Überwachen Sie nach der Behebung eines Kannibalisierungsproblems die Rankings der verbleibenden Seite 4-6 Wochen lang. Sie sollten innerhalb dieses Zeitraums eine Ranking-Verbesserung sehen, da Google die Signale auf eine einzelne URL konsolidiert. Wenn sich die Rankings nicht verbessern, prüfen Sie, ob interne Links und Canonical-Tags korrekt auf die vorgesehene Seite verweisen.",
        },
        {
          title: "Keywords über Seitentypen hinweg zuordnen",
          content:
            "Ein E-Commerce-Shop hat typischerweise vier Seitentypen, die Keyword-Zuordnungen benötigen: Kategorieseiten, Produktseiten, Blog-/Ratgeberseiten und Informations- oder Markenseiten. Jeder Typ erfüllt eine andere Rolle in Ihrem Keyword-Funnel.\n\nKategorieseiten erfassen die Keywords mit dem höchsten Suchvolumen im kommerziellen Bereich. Dies sind Ihre Geldseiten, „Damen Laufschuhe,“ „Bio-Hautpflege,“ „Bluetooth-Kopfhörer unter 100.“ Kategorieseiten zielen typischerweise auf Keywords mit 1.000 bis über 50.000 monatlichen Suchanfragen ab. Da diese Begriffe wettbewerbsintensiv sind, benötigen Kategorieseiten starke Inhalte, interne Verlinkung und oft Backlinks, um zu ranken.\n\nProduktseiten zielen auf spezifische, transaktionale Long-Tail-Keywords ab. Jede Produktseite wird dem exakten Produktnamen und den nächsten Suchvarianten zugeordnet. Das Volumen pro Keyword ist niedriger (oft 50-500 Suchanfragen pro Monat), aber Sie haben Hunderte oder Tausende von Produktseiten, sodass der aggregierte Traffic erheblich ist.\n\nBlog- und Ratgeberseiten behandeln informationale Suchanfragen, die Ihren Sales-Funnel füllen. „Wie wähle ich Laufschuhe bei Überpronation“ bringt potenzielle Käufer, die sich noch nicht für ein Produkt entschieden haben. Diese Seiten verlinken auf relevante Kategorie- und Produktseiten und schaffen einen Content-zu-Commerce-Pfad. Weitere Informationen finden Sie in unserem Leitfaden zu [Produktseite](/academy/product-page-seo).\n\nMarken- und Vergleichsseiten liegen zwischen informationaler und transaktionaler Intention. „Nike vs Adidas Laufschuhe“ oder „Beste Laufschuhe 2025“ erfassen Vergleichskäufer. Diese Seiten werden wie Blogbeiträge im Keyword-Map behandelt, haben aber typischerweise ein höheres Konversionspotenzial, da die Intention näher am Kauf liegt.",
          items: [
            "Kategorieseiten zielen auf breite kommerzielle Keywords mit dem höchsten Volumen ab",
            "Produktseiten zielen auf spezifische Long-Tail-Begriffe ab, die exakten Produktnamen entsprechen",
            "Blog-Seiten erfassen informationale Anfragen, die potenzielle Käufer in den Funnel führen",
          ],
        },
        {
          title: "Ihr Keyword-Map langfristig pflegen",
          content:
            "Ein Keyword-Map ist ein lebendes Dokument, kein einmaliges Projekt. Jedes Mal, wenn Sie ein neues Produkt hinzufügen, eine neue Kategorie erstellen oder einen Blogbeitrag veröffentlichen, muss das Map aktualisiert werden. Wir empfehlen eine vierteljährliche Überprüfung des gesamten Maps, aber inkrementelle Aktualisierungen sollten in Echtzeit erfolgen, sobald neue Seiten live gehen.\n\nRichten Sie einen Prozess ein: Bevor eine neue Seite erstellt wird, prüft das Content- oder SEO-Team den Keyword-Map. Gibt es bereits eine Seite, die auf dieses Keyword abzielt? Wenn ja, entweder die neue Seite auf ein anderes Keyword umfokussieren oder sie mit der bestehenden Seite zusammenführen. Diese Fünf-Minuten-Prüfung verhindert Kannibalisierungsprobleme, deren Diagnose und Behebung später Wochen dauert.\n\nVierteljährliche Überprüfungen sollten drei Aufgaben umfassen. Erstens: Ranking-Positionen für alle primären Keywords aktualisieren. Exportieren Sie aktuelle Rankings aus Ihrem Tracking-Tool und fügen Sie sie in das Map ein. Dies zeigt, welche Seiten sich verbessern, stagnieren oder abfallen. Zweitens: Neue Keyword-Chancen aus Ihrer Recherche-Pipeline prüfen und bestehenden oder geplanten Seiten zuweisen. Drittens: Eingestellte Produkte oder archivierte Seiten entfernen und deren Keywords neu zuordnen, wenn die Begriffe noch Wert haben.\n\nFür größere Shops mit Tausenden von Produkten sollten Sie Teile dieses Prozesses automatisieren. Ein Python-Skript, das Ranking-Daten über eine API abruft und Ihre Tabelle aktualisiert, spart Stunden manueller Arbeit. Einige Teams wechseln von Tabellen zu datenbankgestützten Tools wie Airtable oder Notion für einfachere Zusammenarbeit und Filterung.\n\nDer Keyword-Map wird auch zu Ihrer Reporting-Grundlage. Wenn die Geschäftsleitung fragt, warum der organische Traffic im letzten Quartal um 15% gewachsen ist, können Sie auf bestimmte Keywords verweisen, die zugewiesen wurden, Seiten, die optimiert wurden, und Rankings, die sich verbessert haben, alles in einem Dokument nachverfolgt. F\u00fcr einen tieferen Einblick lesen Sie unseren Leitfaden zu [Ecommerce-SEO-Strategie](/blog/ecommerce-seo-strategy).",
        },
      ],
      navLabels: {
        previous: "Wettbewerber-Keyword-Analyse",
        next: "Saisonale Keyword-Trends",
      },
    },
    fr: {
      badge: "Recherche de mots-clés",
      heading: "Mapping de mots-clés pour les boutiques en ligne",
      intro: "Un mapping de mots-clés attribue des mots-clés cibles spécifiques à des URLs spécifiques de votre boutique. Sans cela, vous vous retrouvez avec plusieurs pages en concurrence pour les mêmes termes, des efforts d'optimisation gaspillés et des opportunités manquées où aucune page ne cible un mot-clé éprouvé. Pour les boutiques comptant des centaines ou des milliers de produits, un mapping de mots-clés fait la différence entre une croissance SEO organisée et le chaos.",
      readTime: "9 min de lecture",
      sections: [
        {
          title: "Qu'est-ce qu'un mapping de mots-clés et pourquoi votre boutique en a besoin",
          content:
            "Un mapping de mots-clés est un document, généralement un tableur, qui crée une relation un-à-un entre chaque URL de votre site et le mot-clé principal pour lequel cette URL doit se positionner. Chaque URL reçoit également 2-3 mots-clés secondaires et une note sur l'intention de recherche. Pensez-y comme un plan de table pour vos mots-clés : chaque terme a une place assignée, et deux invités ne peuvent pas s'asseoir sur la même chaise.\n\nSans mapping, les sites e-commerce développent inévitablement une cannibalisation de mots-clés. Votre [page catégorie](/academy/category-page-seo) pour « bottes en cuir » et votre article de blog intitulé « Les meilleures bottes en cuir pour l'hiver » se battent dans les résultats de recherche. Google voit les deux pages cibler la même requête et soit choisit la mauvaise, soit supprime les deux. Nous avons vu des boutiques perdre 30-40% de leur trafic organique à cause de problèmes de cannibalisation qu'un mapping aurait prévenus.\n\nLe mapping révèle aussi les lacunes de couverture. Lorsque vous listez chaque URL à côté de son mot-clé principal, vous repérez rapidement les mots-clés à fort volume qui n'ont aucune page assignée. Peut-être que vous vendez des dizaines de chaussures de course mais n'avez aucune page catégorie ciblant spécifiquement « chaussures de trail », un terme à 12 000 recherches mensuelles totalement non adressé.\n\nPour les boutiques fonctionnant sur Shopify, WooCommerce ou Magento, le mapping devient votre bible de planification de contenu. Chaque nouvelle [page produit](/academy/product-page-seo), chaque nouvelle collection, chaque article de blog reçoit une attribution de mot-clé avant sa création. Cela empêche l'approche réactive où vous créez des pages d'abord puis essayez de déterminer pour quoi elles devraient se positionner ensuite.",
          items: [
            "Chaque URL reçoit exactement un mot-clé principal et 2-3 mots-clés secondaires",
            "Le mapping empêche la cannibalisation en s'assurant qu'aucun mot-clé n'est assigné à plusieurs pages",
            "Les lacunes de couverture deviennent visibles lorsque des mots-clés n'ont aucune URL assignée",
            "Les nouvelles pages doivent recevoir des attributions de mots-clés avant leur création, pas après",
          ],
        },
        {
          title: "Construire votre mapping : la structure du tableur",
          content:
            "Votre tableur de mapping nécessite au minimum sept colonnes. Colonne un : l'URL (le chemin réel de la page). Colonne deux : le type de page, produit, catégorie, sous-catégorie, article de blog ou page d'atterrissage. Colonne trois : le mot-clé principal, le terme le plus important pour lequel cette page doit se positionner. Colonne quatre : les mots-clés secondaires, généralement 2-3 variations liées. Colonne cinq : le volume de recherche mensuel du mot-clé principal. Colonne six : la position de classement actuelle, le cas échéant. Colonne sept : l'intention de recherche, navigationnelle, informationnelle, commerciale ou transactionnelle.\n\nCommencez par exporter toutes vos URLs existantes. Récupérez votre sitemap ou utilisez Screaming Frog pour crawler le site. Pour une boutique avec 500 produits, 30 catégories et 20 articles de blog, vous aurez environ 550 lignes. Puis exportez vos données de recherche de mots-clés, chaque mot-clé identifié dans votre processus de recherche, et commencez à assigner les termes aux URLs.\n\nLes pages catégories reçoivent les termes les plus larges avec le volume le plus élevé. « Chaussures de course femme » va sur la page catégorie des chaussures de course pour femmes, pas sur un produit individuel. Les pages produits reçoivent des termes longs et spécifiques décrivant exactement le produit. « Nike Air Zoom Pegasus 40 femme » est mappé sur cette page produit spécifique.\n\nLes pages de blog et de guides reçoivent les mots-clés informationnels. « Comment choisir des chaussures de course pour pieds plats » est mappé sur un guide d'achat, pas sur une page produit. Cette attribution basée sur l'intention est cruciale, mapper un mot-clé informationnel sur une page produit ne fonctionnera pas car Google attend un contenu informationnel pour cette requête.",
          tip: "Utilisez un code couleur pour les lignes de votre tableur selon le type de page. Les catégories en bleu, les produits en vert, les articles de blog en jaune. Cela facilite le scan du mapping et l'identification de patterns, comme si vous avez accidentellement assigné un mot-clé commercial à un article de blog au lieu d'une page catégorie.",
        },
        {
          title: "Assigner les mots-clés principaux et secondaires",
          content:
            "Le mot-clé principal de chaque page doit répondre à trois critères. Premièrement, il correspond à l'intention de recherche de la page, un mot-clé transactionnel pour une page produit, un mot-clé commercial pour une page catégorie, un mot-clé informationnel pour un guide. Deuxièmement, une seule page dans toute votre boutique cible ce mot-clé principal. Troisièmement, le mot-clé a un volume de recherche significatif par rapport à votre niche.\n\nLes mots-clés secondaires sont des variations proches du mot-clé principal pour lesquelles la même page peut naturellement se positionner. Si le mot-clé principal d'une page catégorie est « vêtements bébé bio, » les mots-clés secondaires pourraient être « habits bébé biologiques, » « tenues bébé coton bio » et « vêtements bébé naturels. » Ce sont des variations que Google associe déjà à la même intention, donc une seule page bien optimisée peut toutes les capturer.\n\nÉvitez d'assigner des mots-clés secondaires ayant une intention différente du mot-clé principal. « Vêtements bébé bio » (commercial) et « les vêtements bébé bio valent-ils le coup » (informationnel) ne devraient pas être sur la même page, la requête informationnelle appartient à un article de blog ou une page de guide.\n\nPour les pages produits, le mot-clé principal est généralement le nom du produit plus son principal différenciateur. « Ergobaby Omni 360 porte-bébé » est un mot-clé au niveau produit. Les mots-clés secondaires ajoutent des modificateurs : « Ergobaby Omni 360 avis, » « Ergobaby Omni 360 toutes positions. » Si les données de volume montrent que les gens recherchent à la fois le format avec nom de marque et un descripteur générique, assignez la version au volume le plus élevé comme mot-clé principal.",
          items: [
            "Les mots-clés principaux doivent correspondre à l'intention de la page, transactionnel pour les produits, commercial pour les catégories",
            "Chaque mot-clé principal n'apparaît qu'une seule fois dans tout votre mapping",
            "Les mots-clés secondaires sont des variations proches partageant la même intention de recherche",
            "Les mots-clés principaux des pages produits combinent nom du produit et différenciateurs clés",
          ],
          image: {
            src: "/images/academy/fr/keyword-map-structure.svg",
            alt: "Tableau montrant comment les différents types de pages correspondent aux niveaux d'intention des mots clés avec des exemples de mots clés et de plages de volumes",
            caption: "Jeder Seitentyp erfüllt eine bestimmte Rolle im Keyword-Trichter.",
          },
          callout: {
            title: "Kannibalisierungskosten",
            text: "Shops ohne Keyword-Map verlieren 30–40 % ihres organischen Traffics durch Kannibalisierung.",
          },
        },
        {
          title: "Détecter et corriger la cannibalisation de mots-clés",
          content:
            "La cannibalisation survient lorsque deux pages ou plus de votre site ciblent le même mot-clé, forçant Google à choisir laquelle positionner. Le résultat est généralement qu'aucune page ne se positionne aussi bien qu'une seule page focalisée. En e-commerce, la cannibalisation la plus courante se produit entre pages catégories et articles de blog, ou entre des pages de sous-catégories qui se chevauchent.\n\nPour détecter la cannibalisation, recherchez sur Google « site:votreboutique.com mot-clé » pour chacun de vos mots-clés principaux. Si deux pages ou plus apparaissent, vous avez un conflit. Une approche plus systématique utilise Google Search Console : allez dans Performances, filtrez par requête et vérifiez l'onglet Pages. Si plusieurs URLs reçoivent des impressions pour la même requête, Google divise les signaux entre elles.\n\nAhrefs et Semrush signalent également la cannibalisation. Dans Semrush, le rapport Cannibalisation sous Suivi de Position met en évidence les mots-clés pour lesquels plusieurs URLs de votre domaine apparaissent dans les résultats. Le rapport montre quelle URL Google préfère actuellement et lesquelles sont en concurrence.\n\nLes corrections dépendent de la situation. Si un article de blog et une page catégorie ciblent tous deux « bottes en cuir homme, » vous avez trois options. Option un : recentrer l'article de blog sur une variante informationnelle comme « comment entretenir des bottes en cuir » et ajouter un lien interne vers la page catégorie. Option deux : fusionner le contenu si l'article a des backlinks solides, le rediriger vers la page catégorie et intégrer le meilleur contenu. Option trois : utiliser une balise canonical sur l'article pointant vers la page catégorie, bien que ce soit le signal le plus faible.\n\nLa meilleure correction est toujours la prévention. Lorsque votre mapping est en place et que chaque nouvelle page reçoit une attribution de mot-clé avant publication, la cannibalisation survient rarement.",
          tip: "Après avoir corrigé un problème de cannibalisation, surveillez les classements de la page restante pendant 4-6 semaines. Vous devriez voir une amélioration du classement dans ce délai, car Google consolide les signaux sur une seule URL. Si les classements ne s'améliorent pas, vérifiez que les liens internes et les balises canonical pointent correctement vers la page prévue.",
        },
        {
          title: "Mapper les mots-clés selon les types de pages",
          content:
            "Une boutique e-commerce a typiquement quatre types de pages nécessitant des attributions de mots-clés : pages catégories, pages produits, pages blog/guides et pages d'information ou de marque. Chaque type joue un rôle différent dans votre entonnoir de mots-clés.\n\nLes pages catégories capturent les mots-clés commerciaux au volume le plus élevé. Ce sont vos pages génératrices de revenus, « chaussures de course femme, » « soins de la peau bio, » « écouteurs sans fil moins de 100 euros. » Les pages catégories ciblent typiquement des mots-clés avec 1 000 à plus de 50 000 recherches mensuelles. Comme ces termes sont concurrentiels, les pages catégories ont besoin d'un contenu solide, de liens internes et souvent de backlinks pour se positionner.\n\nLes pages produits ciblent des mots-clés transactionnels spécifiques et longs. Chaque page produit est mappée au nom exact du produit et aux recherches de variantes les plus proches. Le volume par mot-clé est plus faible (souvent 50-500 recherches par mois), mais vous avez des centaines ou des milliers de pages produits, donc le trafic agrégé est significatif.\n\nLes pages blog et guides traitent les requêtes informationnelles qui alimentent votre entonnoir de vente. « Comment choisir des chaussures de course pour la surpronation » attire des acheteurs potentiels qui n'ont pas encore choisi de produit. Ces pages renvoient vers les pages catégories et produits pertinentes, créant un chemin du contenu vers le commerce.\n\nLes pages de marque et de comparaison se situent entre l'intention informationnelle et transactionnelle. « Nike vs Adidas chaussures de course » ou « meilleures chaussures de course 2025 » capturent les acheteurs comparatifs. Ces pages sont mappées comme des articles de blog mais ont typiquement un potentiel de conversion plus élevé car l'intention est plus proche de l'achat.",
          items: [
            "Les pages catégories ciblent les mots-clés commerciaux larges au volume le plus élevé",
            "Les pages produits ciblent des termes longs spécifiques correspondant aux noms exacts des produits",
            "Les pages blog capturent les requêtes informationnelles qui alimentent les acheteurs potentiels dans l'entonnoir",
          ],
        },
        {
          title: "Maintenir votre mapping dans le temps",
          content:
            "Un mapping de mots-clés est un document vivant, pas un projet ponctuel. Chaque fois que vous ajoutez un nouveau produit, créez une nouvelle catégorie ou publiez un article de blog, le mapping doit être mis à jour. Nous recommandons de revoir l'ensemble du mapping chaque trimestre, mais les mises à jour incrémentielles doivent se faire en temps réel dès que de nouvelles pages sont publiées.\n\nÉtablissez un processus : avant la création de toute nouvelle page, l'équipe contenu ou SEO vérifie le mapping. Y a-t-il déjà une page ciblant ce mot-clé ? Si oui, soit recentrer la nouvelle page sur un mot-clé différent, soit la fusionner avec la page existante. Cette vérification de cinq minutes prévient les problèmes de cannibalisation qui prennent des semaines à diagnostiquer et corriger par la suite.\n\nLes revues trimestrielles doivent inclure trois tâches. Premièrement, mettre à jour les positions de classement pour tous les mots-clés principaux. Exportez les classements actuels de votre outil de suivi et collez-les dans le mapping. Cela montre quelles pages s'améliorent, stagnent ou déclinent. Deuxièmement, vérifier les nouvelles opportunités de mots-clés de votre pipeline de recherche et les assigner à des pages existantes ou planifiées. Troisièmement, supprimer les produits abandonnés ou les pages archivées et réassigner leurs mots-clés si les termes ont encore de la valeur.\n\nPour les boutiques plus grandes avec des milliers de produits, envisagez d'automatiser des parties de ce processus. Un script Python qui récupère les données de classement via une API et met à jour votre tableur fait gagner des heures de travail manuel. Certaines équipes passent des tableurs à des outils basés sur des bases de données comme Airtable ou Notion pour une collaboration et un filtrage plus faciles.\n\nLe mapping devient aussi le fondement de vos rapports. Quand la direction demande pourquoi le trafic organique a augmenté de 15% le trimestre dernier, vous pouvez montrer les mots-clés assignés, les pages optimisées et les classements améliorés, tout suivi dans un seul document. Pour une vision plus large de la façon dont le mapping de mots-clés s'intègre dans votre approche globale, consultez notre guide sur la [stratégie SEO e-commerce](/blog/ecommerce-seo-strategy).",
        },
      ],
      navLabels: {
        previous: "Analyse des mots-clés concurrents",
        next: "Tendances saisonnières des mots-clés",
      },
    },
    es: {
      badge: "Investigación de palabras clave",
      heading: "Mapeo de palabras clave para tiendas online",
      intro: "Un mapa de palabras clave asigna palabras clave objetivo específicas a URLs específicas de tu tienda. Sin él, terminas con múltiples páginas compitiendo por los mismos términos, esfuerzo de optimización desperdiciado y oportunidades perdidas donde ninguna página apunta a una palabra clave probada. Para tiendas con cientos o miles de productos, un mapa de palabras clave es la diferencia entre un crecimiento SEO organizado y el caos.",
      readTime: "9 min de lectura",
      sections: [
        {
          title: "Qué es un mapa de palabras clave y por qué tu tienda lo necesita",
          content:
            "Un mapa de palabras clave es un documento, generalmente una hoja de cálculo, que crea una relación uno a uno entre cada URL de tu sitio y la palabra clave principal por la que esa URL debe posicionarse. Cada URL también recibe 2-3 palabras clave secundarias y una nota sobre la intención de búsqueda. Piénsalo como un plano de asientos para tus palabras clave: cada término tiene un asiento asignado, y dos invitados no se sientan en la misma silla.\n\nSin un mapa de palabras clave, los sitios de comercio electrónico inevitablemente desarrollan canibalización de palabras clave. Tu página de categoría para \"botas de cuero\" y tu artículo de blog titulado \"Las mejores botas de cuero para invierno\" luchan entre sí en los resultados de búsqueda. Google ve ambas páginas apuntando a la misma consulta y elige la incorrecta o suprime ambas. Hemos visto tiendas perder 30-40% de su tráfico orgánico por problemas de canibalización que un mapa habría prevenido.\n\nEl mapa también expone brechas de cobertura. Cuando listas cada URL junto a su palabra clave principal, rápidamente detectas palabras clave de alto volumen sin página asignada. Quizás vendes docenas de zapatillas de running pero no tienes una página de categoría que apunte específicamente a \"zapatillas de trail running\", un término con 12.000 búsquedas mensuales completamente sin atender.\n\nPara tiendas que funcionan con Shopify, WooCommerce o Magento, el mapa de palabras clave se convierte en tu biblia de planificación de contenido. Cada nueva página de producto, cada nueva colección, cada artículo del blog recibe una asignación de palabra clave antes de ser creado. Esto previene el enfoque reactivo donde construyes páginas primero e intentas descifrar para qué deberían posicionarse después.",
          items: [
            "Cada URL recibe exactamente una palabra clave principal y 2-3 secundarias",
            "El mapa previene la canibalización asegurando que ninguna palabra clave se asigne a múltiples páginas",
            "Las brechas de cobertura se hacen visibles cuando hay palabras clave sin URL asignada",
            "Las nuevas páginas deben recibir asignaciones de palabras clave antes de ser creadas, no después",
          ],
        },
        {
          title: "Construyendo tu mapa: la estructura de la hoja de cálculo",
          content:
            "Tu hoja de cálculo de mapa de palabras clave necesita un mínimo de siete columnas. Columna uno es la URL (la ruta real de la página). Columna dos es el tipo de página: producto, categoría, subcategoría, artículo de blog o página de destino. Columna tres es la palabra clave principal, el término más importante por el que esta página debe posicionarse. Columna cuatro contiene las palabras clave secundarias, generalmente 2-3 variaciones relacionadas. Columna cinco es el volumen de búsqueda mensual de la palabra clave principal. Columna seis es la posición de ranking actual, si existe. Columna siete es la intención de búsqueda: navegacional, informacional, comercial o transaccional.\n\nComienza exportando todas tus URLs existentes. Extrae tu sitemap o usa Screaming Frog para rastrear el sitio. Para una tienda con 500 productos, 30 categorías y 20 artículos de blog, tendrás aproximadamente 550 filas. Luego exporta tus datos de investigación de palabras clave, cada palabra clave identificada en tu proceso de investigación, y comienza a asignar términos a URLs.\n\nLas páginas de categoría reciben los términos más amplios y de mayor volumen. \"Zapatillas de running para mujer\" va a la [página de categoría](/academy/category-page-seo) de zapatillas de running femeninas, no a un producto individual. Las páginas de producto reciben términos específicos de cola larga que describen exactamente lo que es ese producto. \"Nike Air Zoom Pegasus 40 mujer\" se asigna a esa página de producto específica.\n\nLas páginas de blog y guías reciben palabras clave informacionales. \"Cómo elegir zapatillas de running para pies planos\" se asigna a una guía de compra, no a una página de producto. Esta asignación basada en intención es crítica, asignar una palabra clave informacional a una página de producto no funcionará porque Google espera contenido informacional para esa consulta.",
          tip: "Usa códigos de colores en las filas de tu hoja de cálculo por tipo de página. Categorías en azul, productos en verde, artículos de blog en amarillo. Esto facilita escanear el mapa y detectar patrones, como si accidentalmente asignaste una palabra clave comercial a un artículo de blog en lugar de a una página de categoría.",
        },
        {
          title: "Asignando palabras clave principales y secundarias",
          content:
            "La palabra clave principal de cada página debe cumplir tres criterios. Primero, coincide con la intención de búsqueda de la página, una palabra clave transaccional para una página de producto, una comercial para una página de categoría, una informacional para una guía. Segundo, solo una página en toda tu tienda apunta a esta palabra clave principal. Tercero, la palabra clave tiene un volumen de búsqueda significativo relativo a tu nicho.\n\nLas palabras clave secundarias son variaciones cercanas de la principal por las que la misma página puede posicionarse naturalmente. Si la palabra clave principal de una página de categoría es \"ropa de bebé orgánica,\" las secundarias podrían ser \"ropa bebé algodón orgánico,\" \"ropa de bebé ecológica\" y \"ropa natural para bebé.\" Son variaciones que Google ya asocia con la misma intención, así que una sola página bien optimizada puede capturarlas todas.\n\nEvita asignar palabras clave secundarias con intención diferente a la principal. \"Ropa de bebé orgánica\" (comercial) y \"¿vale la pena la ropa orgánica para bebé?\" (informacional) no deberían estar en la misma página, la consulta informacional pertenece a un artículo de blog o página de guía.\n\nPara páginas de producto, la palabra clave principal suele ser el nombre del producto más su diferenciador clave. \"Ergobaby Omni 360 portabebés\" es una palabra clave a nivel de producto. Las secundarias agregan modificadores: \"Ergobaby Omni 360 opiniones,\" \"Ergobaby Omni 360 todas las posiciones.\" Si los datos de volumen muestran que la gente busca tanto el formato con marca como un descriptor genérico, asigna la versión de mayor volumen como principal.",
          items: [
            "Las palabras clave principales deben coincidir con la intención de la página, transaccional para productos, comercial para categorías",
            "Cada palabra clave principal aparece solo una vez en todo tu mapa",
            "Las secundarias son variaciones cercanas que comparten la misma intención de búsqueda",
            "Las principales de páginas de producto combinan nombre del producto con diferenciadores clave",
          ],
          image: {
            src: "/images/academy/es/keyword-map-structure.svg",
            alt: "Tabla que muestra cómo los diferentes tipos de páginas se asignan a los niveles de intención de las palabras clave con ejemplos de palabras clave y rangos de volumen.",
            caption: "Jeder Seitentyp erfüllt eine bestimmte Rolle im Keyword-Trichter.",
          },
          callout: {
            title: "Kannibalisierungskosten",
            text: "Shops ohne Keyword-Map verlieren 30–40 % ihres organischen Traffics durch Kannibalisierung.",
          },
        },
        {
          title: "Detectar y corregir la canibalización de palabras clave",
          content:
            "La canibalización ocurre cuando dos o más páginas de tu sitio apuntan a la misma palabra clave, forzando a Google a elegir cuál posicionar. El resultado suele ser que ninguna página se posiciona tan bien como lo haría una sola página enfocada. En e-commerce, la canibalización más común ocurre entre páginas de categoría y artículos de blog, o entre páginas de subcategorías que se solapan.\n\nPara detectar canibalización, busca en Google \"site:tutienda.com palabra-clave\" para cada una de tus palabras clave principales. Si aparecen dos o más páginas, tienes un conflicto. Un enfoque más sistemático usa Google Search Console: ve a Rendimiento, filtra por consulta y revisa la pestaña Páginas. Si múltiples URLs reciben impresiones para la misma consulta, Google está dividiendo las señales entre ellas.\n\nAhrefs y Semrush también señalan la canibalización. En Semrush, el informe de Canibalización bajo Seguimiento de Posición resalta las palabras clave donde múltiples URLs de tu dominio aparecen en los resultados. El informe muestra qué URL prefiere Google actualmente y cuáles compiten.\n\nLas soluciones dependen de la situación. Si un artículo de blog y una página de categoría apuntan a \"botas de cuero hombre,\" tienes tres opciones. Opción uno: reenfocar el artículo en una variante informacional como \"cómo cuidar botas de cuero\" y agregar un enlace interno a la página de categoría. Opción dos: fusionar el contenido si el artículo tiene backlinks sólidos, redirigirlo a la página de categoría e incorporar el mejor contenido. Opción tres: usar una etiqueta canonical en el artículo apuntando a la página de categoría, aunque esta es la señal más débil.\n\nLa mejor solución siempre es la prevención. Cuando tu mapa está establecido y cada nueva página recibe una asignación de palabra clave antes de publicarse, la canibalización rara vez ocurre.",
          tip: "Después de corregir un problema de canibalización, monitorea los rankings de la página que permanece durante 4-6 semanas. Deberías ver una mejora en el posicionamiento dentro de ese plazo, ya que Google consolida las señales en una sola URL. Si los rankings no mejoran, verifica que los enlaces internos y las etiquetas canonical apunten correctamente a la página prevista.",
        },
        {
          title: "Mapeando palabras clave según tipos de página",
          content:
            "Una tienda de e-commerce típicamente tiene cuatro tipos de página que necesitan asignaciones de palabras clave: páginas de categoría, páginas de producto, páginas de blog/guías y páginas informacionales o de marca. Cada tipo cumple un rol diferente en tu embudo de palabras clave.\n\nLas páginas de categoría capturan las palabras clave comerciales de mayor volumen. Estas son tus páginas generadoras de ingresos, \"zapatillas de running para mujer,\" \"cuidado de la piel orgánico,\" \"auriculares inalámbricos menos de 100.\" Las páginas de categoría típicamente apuntan a palabras clave con 1.000 a más de 50.000 búsquedas mensuales. Como estos términos son competitivos, necesitan contenido sólido, enlazado interno y frecuentemente backlinks para posicionarse.\n\nLas páginas de producto apuntan a palabras clave transaccionales específicas de cola larga. Cada [página de producto](/academy/product-page-seo) se mapea al nombre exacto del producto y las búsquedas de variantes más cercanas. El volumen por palabra clave es menor (frecuentemente 50-500 búsquedas al mes), pero tienes cientos o miles de páginas de producto, así que el tráfico agregado es significativo.\n\nLas páginas de blog y guías manejan consultas informacionales que alimentan tu embudo de ventas. \"Cómo elegir zapatillas de running para sobrepronación\" atrae compradores potenciales que aún no han decidido un producto. Estas páginas enlazan a las páginas de categoría y producto relevantes, creando un camino del contenido al comercio.\n\nLas páginas de marca y comparación se sitúan entre la intención informacional y transaccional. \"Nike vs Adidas zapatillas de running\" o \"mejores zapatillas de running 2025\" capturan compradores comparativos. Estas páginas se mapean como artículos de blog pero típicamente tienen mayor potencial de conversión porque la intención está más cerca de la compra.",
          items: [
            "Las páginas de categoría apuntan a palabras clave comerciales amplias de mayor volumen",
            "Las páginas de producto apuntan a términos de cola larga específicos que coinciden con nombres exactos de productos",
            "Las páginas de blog capturan consultas informacionales que alimentan a los compradores potenciales en el embudo",
          ],
        },
        {
          title: "Mantener tu mapa de palabras clave a lo largo del tiempo",
          content:
            "Un mapa de palabras clave es un documento vivo, no un proyecto puntual. Cada vez que agregas un nuevo producto, creas una nueva categoría o publicas un artículo de blog, el mapa necesita actualizarse. Recomendamos revisar el mapa completo trimestralmente, pero las actualizaciones incrementales deben ocurrir en tiempo real cuando las nuevas páginas se publican.\n\nEstablece un proceso: antes de crear cualquier página nueva, el equipo de contenido o SEO revisa el mapa. ¿Ya existe una página apuntando a esta palabra clave? Si es así, reenfocar la nueva página en una palabra clave diferente o fusionarla con la página existente. Esta verificación de cinco minutos previene problemas de canibalización que tardan semanas en diagnosticar y corregir después.\n\nLas revisiones trimestrales deben incluir tres tareas. Primero, actualizar posiciones de ranking para todas las palabras clave principales. Exporta los rankings actuales de tu herramienta de seguimiento y pégalos en el mapa. Esto muestra qué páginas están mejorando, estancándose o declinando. Segundo, buscar nuevas oportunidades de palabras clave de tu pipeline de investigación y asignarlas a páginas existentes o planificadas. Tercero, eliminar productos descontinuados o páginas archivadas y reasignar sus palabras clave si los términos aún tienen valor.\n\nPara tiendas más grandes con miles de productos, considera automatizar partes de este proceso. Un script en Python que obtiene datos de ranking a través de una API y actualiza tu hoja de cálculo ahorra horas de trabajo manual. Algunos equipos migran de hojas de cálculo a herramientas con base de datos como Airtable o Notion para una colaboración y filtrado más fáciles.\n\nEl mapa de palabras clave también se convierte en la base de tus informes. Cuando la dirección pregunta por qué el tráfico orgánico creció 15% el último trimestre, puedes señalar palabras clave específicas que fueron asignadas, páginas que fueron optimizadas y rankings que mejoraron, todo rastreado en un solo documento. Para una vision mas amplia de como el mapeo de palabras clave encaja en tu enfoque general, consulta nuestra guia de [estrategia SEO para ecommerce](/blog/ecommerce-seo-strategy).",
        },
      ],
      navLabels: {
        previous: "Análisis de palabras clave de competidores",
        next: "Tendencias estacionales de palabras clave",
      },
    },
    it: {
      badge: "Ricerca parole chiave",
      heading: "Mappatura delle parole chiave per negozi online",
      intro:
        "Una mappa delle parole chiave assegna specifiche parole chiave target a specifici URL nel tuo negozio. Senza di essa, ti ritrovi con pagine multiple che competono per gli stessi termini, sforzi di ottimizzazione sprecati e opportunità mancate dove nessuna pagina punta a una parola chiave collaudata. Per i negozi con centinaia o migliaia di prodotti, una mappa delle parole chiave fa la differenza tra una crescita SEO organizzata e il caos.",
      readTime: "9 min di lettura",
      sections: [
        {
          title: "Cos'è una mappa delle parole chiave e perché il tuo negozio ne ha bisogno",
          content:
            "Una mappa delle parole chiave è un documento, solitamente un foglio di calcolo, che crea una relazione uno-a-uno tra ogni URL del tuo sito e la parola chiave principale per cui quell'URL dovrebbe posizionarsi. Ogni URL riceve anche 2-3 parole chiave secondarie e una nota sull'intento di ricerca. Pensala come un piano dei posti per le tue parole chiave: ogni termine ha un posto assegnato, e due ospiti non possono sedersi sulla stessa sedia.\n\nSenza una mappa, i siti e-commerce sviluppano inevitabilmente la cannibalizzazione delle parole chiave. La tua pagina categoria per \"stivali in pelle\" e il tuo articolo del blog intitolato \"I migliori stivali in pelle per l'inverno\" si contendono i risultati di ricerca. Google vede entrambe le pagine mirare alla stessa query e sceglie quella sbagliata o le sopprime entrambe. Abbiamo visto negozi perdere il 30-40% del traffico organico a causa di problemi di cannibalizzazione che una mappa avrebbe prevenuto.\n\nLa mappa rivela anche le lacune di copertura. Quando elenchi ogni URL accanto alla sua parola chiave principale, individui rapidamente le parole chiave ad alto volume senza una pagina assegnata. Forse vendi decine di scarpe da running ma non hai una pagina categoria che punti specificamente a \"scarpe da trail running\", un termine con 12.000 ricerche mensili completamente non presidiato.\n\nPer i negozi su Shopify, WooCommerce o Magento, la mappa diventa la bibbia della pianificazione dei contenuti. Ogni nuova [pagina prodotto](/academy/product-page-seo), ogni nuova collezione, ogni articolo del blog riceve un'assegnazione di parola chiave prima di essere creato. Questo previene l'approccio reattivo dove crei prima le pagine e poi cerchi di capire per cosa dovrebbero posizionarsi.",
          items: [
            "Ogni URL riceve esattamente una parola chiave principale e 2-3 secondarie",
            "La mappa previene la cannibalizzazione assicurando che nessuna parola chiave sia assegnata a più pagine",
            "Le lacune di copertura diventano visibili quando le parole chiave non hanno URL assegnati",
            "Le nuove pagine devono ricevere assegnazioni di parole chiave prima di essere create, non dopo",
          ],
        },
        {
          title: "Costruire la tua mappa: la struttura del foglio di calcolo",
          content:
            "Il tuo foglio di calcolo per la mappa necessita di almeno sette colonne. Colonna uno è l'URL (il percorso effettivo della pagina). Colonna due è il tipo di pagina: prodotto, categoria, sottocategoria, articolo del blog o landing page. Colonna tre è la parola chiave principale, il singolo termine più importante per cui questa pagina deve posizionarsi. Colonna quattro contiene le parole chiave secondarie, solitamente 2-3 variazioni correlate. Colonna cinque è il volume di ricerca mensile della parola chiave principale. Colonna sei è la posizione di ranking attuale, se presente. Colonna sette è l'intento di ricerca: navigazionale, informazionale, commerciale o transazionale.\n\nInizia esportando tutti i tuoi URL esistenti. Estrai la tua sitemap o usa Screaming Frog per scansionare il sito. Per un negozio con 500 prodotti, 30 categorie e 20 articoli del blog, avrai circa 550 righe. Poi esporta i dati della tua ricerca parole chiave, ogni parola chiave identificata nel tuo processo di ricerca, e inizia ad assegnare i termini agli URL.\n\nLe pagine categoria ricevono i termini più ampi e ad alto volume. \"Scarpe da corsa donna\" va alla pagina categoria delle scarpe da running femminili, non a un singolo prodotto. Le pagine prodotto ricevono termini specifici long-tail che descrivono esattamente cosa è quel prodotto. \"Nike Air Zoom Pegasus 40 donna\" viene mappata a quella specifica pagina prodotto. Approfondisci con la nostra guida sulla [pagina di categoria](/academy/category-page-seo).\n\nLe pagine blog e guide ricevono parole chiave informazionali. \"Come scegliere le scarpe da corsa per piedi piatti\" va a una guida all'acquisto, non a una pagina prodotto. Questa assegnazione basata sull'intento è cruciale, mappare una parola chiave informazionale a una pagina prodotto non funzionerà perché Google si aspetta contenuto informativo per quella query.",
          tip: "Usa un codice colore per le righe del foglio di calcolo in base al tipo di pagina. Categorie in blu, prodotti in verde, articoli del blog in giallo. Questo rende facile scorrere la mappa e individuare pattern, come se hai accidentalmente assegnato una parola chiave commerciale a un articolo del blog invece che a una pagina categoria.",
        },
        {
          title: "Assegnare parole chiave principali e secondarie",
          content:
            "La parola chiave principale di ogni pagina deve soddisfare tre criteri. Primo, corrisponde all'intento di ricerca della pagina, una parola chiave transazionale per una pagina prodotto, una commerciale per una pagina categoria, una informazionale per una guida. Secondo, solo una pagina nell'intero negozio punta a questa parola chiave principale. Terzo, la parola chiave ha un volume di ricerca significativo relativo alla tua nicchia.\n\nLe parole chiave secondarie sono variazioni vicine della principale per cui la stessa pagina può naturalmente posizionarsi. Se la parola chiave principale di una pagina categoria è \"abbigliamento neonato biologico,\" le secondarie potrebbero essere \"vestiti neonato cotone bio,\" \"outfit neonato organici\" e \"abbigliamento neonato naturale.\" Queste sono variazioni che Google già associa allo stesso intento, quindi una singola pagina ben ottimizzata può catturarle tutte.\n\nEvita di assegnare parole chiave secondarie con intento diverso dalla principale. \"Abbigliamento neonato biologico\" (commerciale) e \"vale la pena l'abbigliamento bio per neonati\" (informazionale) non dovrebbero essere sulla stessa pagina, la query informazionale appartiene a un articolo del blog o a una pagina guida.\n\nPer le pagine prodotto, la parola chiave principale è solitamente il nome del prodotto più il suo differenziatore chiave. \"Ergobaby Omni 360 marsupio\" è una parola chiave a livello prodotto. Le secondarie aggiungono modificatori: \"Ergobaby Omni 360 recensione,\" \"Ergobaby Omni 360 tutte le posizioni.\" Se i dati sul volume mostrano che le persone cercano sia il formato con nome del brand sia un descrittore generico, assegna la versione a volume più alto come principale.",
          items: [
            "Le parole chiave principali devono corrispondere all'intento della pagina, transazionale per prodotti, commerciale per categorie",
            "Ogni parola chiave principale appare solo una volta nell'intera mappa",
            "Le secondarie sono variazioni vicine che condividono lo stesso intento di ricerca",
            "Le principali delle pagine prodotto combinano nome del prodotto con differenziatori chiave",
          ],
          image: {
            src: "/images/academy/it/keyword-map-structure.svg",
            alt: "Tabella che mostra in che modo i diversi tipi di pagina vengono associati ai livelli di intenzione delle parole chiave con parole chiave di esempio e intervalli di volume",
            caption: "Jeder Seitentyp erfüllt eine bestimmte Rolle im Keyword-Trichter.",
          },
          callout: {
            title: "Kannibalisierungskosten",
            text: "Shops ohne Keyword-Map verlieren 30–40 % ihres organischen Traffics durch Kannibalisierung.",
          },
        },
        {
          title: "Rilevare e correggere la cannibalizzazione delle parole chiave",
          content:
            "La cannibalizzazione si verifica quando due o più pagine del tuo sito puntano alla stessa parola chiave, costringendo Google a scegliere quale posizionare. Il risultato è solitamente che nessuna pagina si posiziona bene quanto una singola pagina focalizzata. Nell'e-commerce, la cannibalizzazione più comune avviene tra pagine categoria e articoli del blog, o tra pagine di sottocategorie che si sovrappongono.\n\nPer rilevare la cannibalizzazione, cerca su Google \"site:tuonegozio.it parola-chiave\" per ciascuna delle tue parole chiave principali. Se appaiono due o più pagine, hai un conflitto. Un approccio più sistematico usa Google Search Console: vai su Rendimento, filtra per query e controlla la scheda Pagine. Se più URL ricevono impressioni per la stessa query, Google sta dividendo i segnali tra di esse.\n\nAnche Ahrefs e Semrush segnalano la cannibalizzazione. In Semrush, il report Cannibalizzazione sotto Monitoraggio Posizioni evidenzia le parole chiave per cui più URL del tuo dominio appaiono nei risultati. Il report mostra quale URL Google preferisce attualmente e quali competono.\n\nLe soluzioni dipendono dalla situazione. Se un articolo del blog e una pagina categoria puntano entrambi a \"stivali in pelle uomo,\" hai tre opzioni. Opzione uno: rifocalizzare l'articolo su una variante informazionale come \"come prendersi cura degli stivali in pelle\" e aggiungere un link interno alla pagina categoria. Opzione due: unire i contenuti se l'articolo ha backlink solidi, reindirizzarlo alla pagina categoria e incorporare i contenuti migliori. Opzione tre: usare un tag canonical sull'articolo che punta alla pagina categoria, anche se questo è il segnale più debole.\n\nLa soluzione migliore è sempre la prevenzione. Quando la tua mappa è in atto e ogni nuova pagina riceve un'assegnazione di parola chiave prima della pubblicazione, la cannibalizzazione si verifica raramente.",
          tip: "Dopo aver corretto un problema di cannibalizzazione, monitora i posizionamenti della pagina sopravvissuta per 4-6 settimane. Dovresti vedere un miglioramento del ranking entro quel periodo, poiché Google consolida i segnali su un singolo URL. Se i posizionamenti non migliorano, verifica che i link interni e i tag canonical puntino correttamente alla pagina prevista.",
        },
        {
          title: "Mappare le parole chiave sui tipi di pagina",
          content:
            "Un negozio e-commerce ha tipicamente quattro tipi di pagina che necessitano di assegnazioni di parole chiave: pagine categoria, pagine prodotto, pagine blog/guide e pagine informative o di brand. Ogni tipo svolge un ruolo diverso nel tuo funnel di parole chiave.\n\nLe pagine categoria catturano le parole chiave commerciali a volume più alto. Queste sono le tue pagine che generano ricavi, \"scarpe da corsa donna,\" \"skincare biologico,\" \"cuffie wireless sotto i 100 euro.\" Le pagine categoria tipicamente puntano a parole chiave con 1.000 a oltre 50.000 ricerche mensili. Poiché questi termini sono competitivi, le pagine categoria necessitano di contenuti solidi, linking interno e spesso backlink per posizionarsi.\n\nLe pagine prodotto puntano a parole chiave transazionali specifiche long-tail. Ogni pagina prodotto è mappata al nome esatto del prodotto e alle ricerche di varianti più vicine. Il volume per parola chiave è inferiore (spesso 50-500 ricerche al mese), ma hai centinaia o migliaia di pagine prodotto, quindi il traffico aggregato è significativo.\n\nLe pagine blog e guide gestiscono le query informazionali che alimentano il tuo funnel di vendita. \"Come scegliere scarpe da corsa per la pronazione\" porta potenziali acquirenti che non hanno ancora deciso un prodotto. Queste pagine linkano alle pagine categoria e prodotto rilevanti, creando un percorso dal contenuto al commercio.\n\nLe pagine di brand e confronto si collocano tra l'intento informazionale e transazionale. \"Nike vs Adidas scarpe da corsa\" o \"migliori scarpe da corsa 2025\" catturano gli acquirenti che confrontano. Queste pagine sono mappate come articoli del blog ma tipicamente hanno un potenziale di conversione più alto perché l'intento è più vicino all'acquisto.",
          items: [
            "Le pagine categoria puntano a parole chiave commerciali ampie con il volume più alto",
            "Le pagine prodotto puntano a termini long-tail specifici corrispondenti ai nomi esatti dei prodotti",
            "Le pagine blog catturano query informazionali che portano potenziali acquirenti nel funnel",
          ],
        },
        {
          title: "Mantenere la tua mappa nel tempo",
          content:
            "Una mappa delle parole chiave è un documento vivo, non un progetto una tantum. Ogni volta che aggiungi un nuovo prodotto, crei una nuova categoria o pubblichi un articolo del blog, la mappa deve essere aggiornata. Consigliamo di rivedere l'intera mappa trimestralmente, ma gli aggiornamenti incrementali dovrebbero avvenire in tempo reale quando le nuove pagine vengono pubblicate.\n\nStabilisci un processo: prima che qualsiasi nuova pagina venga creata, il team contenuti o SEO controlla la mappa. C'è già una pagina che punta a questa parola chiave? Se sì, rifocalizzare la nuova pagina su una parola chiave diversa o unirla con la pagina esistente. Questo controllo di cinque minuti previene problemi di cannibalizzazione che richiedono settimane per essere diagnosticati e corretti successivamente.\n\nLe revisioni trimestrali dovrebbero includere tre attività. Primo, aggiornare le posizioni di ranking per tutte le parole chiave principali. Esporta i ranking attuali dal tuo strumento di monitoraggio e inseriscili nella mappa. Questo mostra quali pagine stanno migliorando, stagnando o declinando. Secondo, verificare nuove opportunità di parole chiave dalla tua pipeline di ricerca e assegnarle a pagine esistenti o pianificate. Terzo, rimuovere prodotti fuori produzione o pagine archiviate e riassegnare le loro parole chiave se i termini hanno ancora valore.\n\nPer negozi più grandi con migliaia di prodotti, considera di automatizzare parti di questo processo. Uno script Python che recupera dati di ranking tramite un'API e aggiorna il tuo foglio di calcolo risparmia ore di lavoro manuale. Alcuni team passano dai fogli di calcolo a strumenti basati su database come Airtable o Notion per una collaborazione e filtrazione più facili.\n\nLa mappa diventa anche il fondamento dei tuoi report. Quando la direzione chiede perché il traffico organico è cresciuto del 15% nell'ultimo trimestre, puoi indicare parole chiave specifiche che sono state assegnate, pagine che sono state ottimizzate e posizionamenti che sono migliorati, tutto tracciato in un unico documento. Per approfondire, consulta la nostra guida sulla [strategia SEO per ecommerce](/blog/ecommerce-seo-strategy).",
        },
      ],
      navLabels: {
        previous: "Analisi parole chiave dei competitor",
        next: "Tendenze stagionali delle parole chiave",
      },
    },
    nl: {
      badge: "Zoekwoordonderzoek",
      heading: "Keyword mapping voor webshops",
      intro:
        "Een keyword map wijst specifieke doelzoekwoorden toe aan specifieke URL's in je webshop. Zonder zo'n map concurreren meerdere pagina's om dezelfde termen, wordt optimalisatie-inspanning verspild en worden kansen gemist waarbij geen enkele pagina een bewezen zoekwoord target. Voor winkels met honderden of duizenden producten is een keyword map het verschil tussen georganiseerde SEO-groei en chaos.",
      readTime: "9 min leestijd",
      sections: [
        {
          title: "Wat een keyword map is en waarom je webshop er een nodig heeft",
          content:
            "Een keyword map is een document, meestal een spreadsheet, dat een een-op-een relatie creëert tussen elke URL op je site en het primaire zoekwoord waarvoor die URL moet ranken. Elke URL krijgt ook 2-3 secundaire zoekwoorden en een notitie over de zoekintentie. Zie het als een tafelschikking voor je zoekwoorden: elke term heeft een toegewezen stoel, en geen twee gasten zitten op dezelfde stoel.\n\nZonder keyword map ontwikkelen e-commerce sites onvermijdelijk zoekwoordkannibalisatie. Je categoriepagina voor \"leren laarzen\" en je blogpost getiteld \"Beste leren laarzen voor de winter\" vechten met elkaar in de zoekresultaten. Google ziet beide pagina's gericht op dezelfde zoekopdracht en kiest de verkeerde of onderdrukt beide. We hebben gezien dat winkels 30-40% van hun organisch verkeer verloren door kannibaliseringsproblemen die een keyword map had voorkomen.\n\nDe map legt ook dekkingsgaten bloot. Wanneer je elke URL naast het primaire zoekwoord opsomt, spot je snel zoekwoorden met hoog volume die geen toegewezen pagina hebben. Misschien verkoop je tientallen hardloopschoenen maar heb je geen categoriepagina die specifiek richt op \"trailrunningschoenen\", een term met 12.000 maandelijkse zoekopdrachten die volledig onbenut blijft.\n\nVoor winkels die draaien op Shopify, WooCommerce of Magento wordt de keyword map je contentplanningsbijbel. Elke nieuwe productpagina, elke nieuwe collectie, elke blogpost krijgt een zoekwoordtoewijzing voordat deze wordt aangemaakt. Dit voorkomt de reactieve aanpak waarbij je eerst pagina's bouwt en daarna probeert uit te zoeken waarvoor ze moeten ranken.",
          items: [
            "Elke URL krijgt precies één primair zoekwoord en 2-3 secundaire zoekwoorden",
            "De map voorkomt kannibalisatie door te zorgen dat geen zoekwoord aan meerdere pagina's wordt toegewezen",
            "Dekkingsgaten worden zichtbaar wanneer zoekwoorden geen toegewezen URL hebben",
            "Nieuwe pagina's moeten zoekwoordtoewijzingen krijgen voordat ze worden aangemaakt, niet erna",
          ],
        },
        {
          title: "Je keyword map opbouwen: de spreadsheetstructuur",
          content:
            "Je keyword map spreadsheet heeft minimaal zeven kolommen nodig. Kolom een is de URL (het daadwerkelijke paginapad). Kolom twee is het paginatype: product, categorie, subcategorie, blogpost of landingspagina. Kolom drie is het primaire zoekwoord, de allerbelangrijkste term waarvoor deze pagina moet ranken. Kolom vier bevat secundaire zoekwoorden, meestal 2-3 gerelateerde variaties. Kolom vijf is het maandelijkse zoekvolume van het primaire zoekwoord. Kolom zes is de huidige rankingpositie, indien aanwezig. Kolom zeven is de zoekintentie: navigatie, informationeel, commercieel of transactioneel.\n\nBegin met het exporteren van al je bestaande URL's. Haal je sitemap op of gebruik Screaming Frog om de site te crawlen. Voor een winkel met 500 producten, 30 categorieën en 20 blogposts heb je ongeveer 550 rijen. Exporteer vervolgens je zoekwoordonderzoeksdata, elk zoekwoord dat je in je onderzoeksproces hebt geïdentificeerd, en begin termen aan URL's toe te wijzen.\n\nCategoriepagina's krijgen de breedste termen met het hoogste volume. \"Dames hardloopschoenen\" gaat naar de [categoriepagina](/academy/category-page-seo) voor dames hardloopschoenen, niet naar een individueel product. Productpagina's krijgen specifieke long-tail termen die precies beschrijven wat dat product is. \"Nike Air Zoom Pegasus 40 dames\" wordt aan die specifieke productpagina gekoppeld.\n\nBlog- en gidspagina's krijgen informationele zoekwoorden. \"Hoe kies je hardloopschoenen bij platvoeten\" wordt aan een koopgids gekoppeld, niet aan een productpagina. Deze op intentie gebaseerde toewijzing is cruciaal, een informationeel zoekwoord aan een productpagina koppelen werkt niet omdat Google informationele content verwacht voor die zoekopdracht.",
          tip: "Gebruik kleurcodering voor de rijen in je spreadsheet op basis van paginatype. Categorieën in blauw, producten in groen, blogposts in geel. Dit maakt het makkelijk om de map te scannen en patronen te herkennen, zoals wanneer je per ongeluk een commercieel zoekwoord aan een blogpost hebt toegewezen in plaats van aan een categoriepagina.",
        },
        {
          title: "Primaire en secundaire zoekwoorden toewijzen",
          content:
            "Het primaire zoekwoord voor elke pagina moet aan drie criteria voldoen. Ten eerste: het komt overeen met de zoekintentie van de pagina, een transactioneel zoekwoord voor een productpagina, een commercieel zoekwoord voor een categoriepagina, een informationeel zoekwoord voor een gids. Ten tweede: slechts één pagina in je hele winkel richt zich op dit primaire zoekwoord. Ten derde: het zoekwoord heeft een betekenisvol zoekvolume ten opzichte van je niche.\n\nSecundaire zoekwoorden zijn nauwe variaties van het primaire zoekwoord waarvoor dezelfde pagina van nature kan ranken. Als het primaire zoekwoord van een categoriepagina \"biologische babykleding\" is, kunnen secundaire zoekwoorden \"baby kleding biologisch katoen,\" \"ecologische babykleding\" en \"natuurlijke babykleding\" zijn. Dit zijn variaties die Google al associeert met dezelfde intentie, dus een enkele goed geoptimaliseerde pagina kan ze allemaal opvangen.\n\nVermijd het toewijzen van secundaire zoekwoorden met een andere intentie dan het primaire zoekwoord. \"Biologische babykleding\" (commercieel) en \"is biologische babykleding het waard\" (informationeel) zouden niet op dezelfde pagina moeten staan, de informationele zoekopdracht hoort bij een blogpost of gidspagina.\n\nVoor productpagina's is het primaire zoekwoord meestal de productnaam plus het belangrijkste onderscheidende kenmerk. \"Ergobaby Omni 360 draagzak\" is een zoekwoord op productniveau. Secundaire zoekwoorden voegen modifiers toe: \"Ergobaby Omni 360 review,\" \"Ergobaby Omni 360 alle posities draagzak.\" Als zoekvolume-data laten zien dat mensen zowel op het merknaamformaat als op een generieke beschrijving zoeken, wijs dan de versie met het hoogste volume toe als primair.",
          items: [
            "Primaire zoekwoorden moeten overeenkomen met de intentie van de pagina, transactioneel voor producten, commercieel voor categorieën",
            "Elk primair zoekwoord verschijnt slechts één keer in je hele keyword map",
            "Secundaire zoekwoorden zijn nauwe variaties die dezelfde zoekintentie delen",
            "Primaire zoekwoorden voor productpagina's combineren productnaam met belangrijke onderscheidende kenmerken",
          ],
          image: {
            src: "/images/academy/nl/keyword-map-structure.svg",
            alt: "Tabel die laat zien hoe verschillende paginatypen verband houden met zoekwoordintentieniveaus, met voorbeeldzoekwoorden en volumebereiken",
            caption: "Jeder Seitentyp erfüllt eine bestimmte Rolle im Keyword-Trichter.",
          },
          callout: {
            title: "Kannibalisierungskosten",
            text: "Shops ohne Keyword-Map verlieren 30–40 % ihres organischen Traffics durch Kannibalisierung.",
          },
        },
        {
          title: "Zoekwoordkannibalisatie detecteren en oplossen",
          content:
            "Kannibalisatie treedt op wanneer twee of meer pagina's op je site zich richten op hetzelfde zoekwoord, waardoor Google gedwongen wordt te kiezen welke te ranken. Het resultaat is meestal dat geen van beide pagina's zo goed rankt als een enkele gefocuste pagina zou doen. In e-commerce komt de meest voorkomende kannibalisatie voor tussen categoriepagina's en blogposts, of tussen overlappende subcategoriepagina's.\n\nOm kannibalisatie te detecteren, zoek op Google naar \"site:jouwebshop.nl zoekwoord\" voor elk van je primaire zoekwoorden. Als twee of meer pagina's verschijnen, heb je een conflict. Een meer systematische aanpak gebruikt Google Search Console: ga naar Prestaties, filter op query en controleer het tabblad Pagina's. Als meerdere URL's vertoningen ontvangen voor dezelfde query, verdeelt Google signalen tussen hen.\n\nAhrefs en Semrush signaleren ook kannibalisatie. In Semrush belicht het Kannibaliseringsrapport onder Positietracking zoekwoorden waarvoor meerdere URL's van je domein verschijnen in de zoekresultaten. Het rapport toont welke URL Google momenteel prefereert en welke concurreren.\n\nOplossingen hangen af van de situatie. Als een blogpost en een categoriepagina beide richten op \"leren laarzen heren,\" heb je drie opties. Optie een: de blogpost heroriënteren op een informationele variant zoals \"hoe onderhoud je leren laarzen\" en een interne link naar de categoriepagina toevoegen. Optie twee: de content samenvoegen als de blogpost sterke backlinks heeft, deze doorverwijzen naar de categoriepagina en de beste content incorporeren. Optie drie: een canonical tag op de blogpost gebruiken die naar de categoriepagina wijst, hoewel dit het zwakste signaal is.\n\nDe beste oplossing is altijd preventie. Wanneer je keyword map op zijn plaats is en elke nieuwe pagina een zoekwoordtoewijzing krijgt vóór publicatie, komt kannibalisatie zelden voor.",
          tip: "Monitor na het oplossen van een kannibaliseringsprobleem de rankings van de overgebleven pagina gedurende 4-6 weken. Je zou een rankingverbetering moeten zien binnen dat venster, omdat Google signalen consolideert op één URL. Als de rankings niet verbeteren, controleer dan of interne links en canonical tags correct naar de bedoelde pagina wijzen.",
        },
        {
          title: "Zoekwoorden mappen over paginatypes",
          content:
            "Een e-commerce webshop heeft doorgaans vier paginatypes die zoekwoordtoewijzingen nodig hebben: categoriepagina's, productpagina's, blog-/gidspagina's en informationele of merkpagina's. Elk type vervult een andere rol in je zoekwoordfunnel.\n\nCategoriepagina's vangen de commerciële zoekwoorden met het hoogste volume op. Dit zijn je geldpagina's, \"dames hardloopschoenen,\" \"biologische huidverzorging,\" \"draadloze koptelefoons onder 100 euro.\" Categoriepagina's richten zich doorgaans op zoekwoorden met 1.000 tot meer dan 50.000 maandelijkse zoekopdrachten. Omdat deze termen competitief zijn, hebben categoriepagina's sterke content, interne links en vaak backlinks nodig om te ranken.\n\nProductpagina's richten zich op specifieke, transactionele long-tail zoekwoorden. Elke productpagina wordt gekoppeld aan de exacte productnaam en de dichtstbijzijnde variantzoekopdrachten. Het volume per zoekwoord is lager (vaak 50-500 zoekopdrachten per maand), maar je hebt honderden of duizenden productpagina's, dus het totale verkeer is aanzienlijk.\n\nBlog- en gidspagina's behandelen informationele zoekopdrachten die je salesfunnel voeden. \"Hoe kies je hardloopschoenen bij overpronatie\" trekt potentiële kopers aan die nog geen product hebben gekozen. Deze pagina's linken naar relevante categorie- en [productpagina's](/academy/product-page-seo), waardoor een pad van content naar commerce ontstaat.\n\nMerk- en vergelijkingspagina's zitten tussen informationele en transactionele intentie. \"Nike vs Adidas hardloopschoenen\" of \"beste hardloopschoenen 2025\" vangen vergelijkende shoppers op. Deze pagina's worden als blogposts in de keyword map behandeld, maar hebben doorgaans een hoger conversiepotentieel omdat de intentie dichter bij de aankoop ligt.",
          items: [
            "Categoriepagina's richten zich op brede commerciële zoekwoorden met het hoogste volume",
            "Productpagina's richten zich op specifieke long-tail termen die overeenkomen met exacte productnamen",
            "Blogpagina's vangen informationele zoekopdrachten op die potentiële kopers in de funnel brengen",
          ],
        },
        {
          title: "Je keyword map onderhouden in de tijd",
          content:
            "Een keyword map is een levend document, geen eenmalig project. Elke keer dat je een nieuw product toevoegt, een nieuwe categorie aanmaakt of een blogpost publiceert, moet de map worden bijgewerkt. We raden aan de volledige map elk kwartaal te herzien, maar incrementele updates moeten in realtime plaatsvinden wanneer nieuwe pagina's live gaan.\n\nStel een proces in: voordat een nieuwe pagina wordt aangemaakt, controleert het content- of SEO-team de keyword map. Is er al een pagina die zich richt op dit zoekwoord? Zo ja, heroriënteer de nieuwe pagina op een ander zoekwoord of voeg deze samen met de bestaande pagina. Deze vijf minuten durende controle voorkomt kannibaliseringsproblemen die weken kosten om later te diagnosticeren en op te lossen.\n\nKwartaalreviews moeten drie taken omvatten. Ten eerste: rankingposities bijwerken voor alle primaire zoekwoorden. Exporteer huidige rankings uit je trackingtool en plak ze in de map. Dit laat zien welke pagina's verbeteren, stagneren of dalen. Ten tweede: nieuwe zoekwoordkansen uit je onderzoekspijplijn controleren en toewijzen aan bestaande of geplande pagina's. Ten derde: uitgefaseerde producten of gearchiveerde pagina's verwijderen en hun zoekwoorden opnieuw toewijzen als de termen nog waarde hebben.\n\nVoor grotere winkels met duizenden producten, overweeg delen van dit proces te automatiseren. Een Python-script dat rankingdata ophaalt via een API en je spreadsheet bijwerkt, bespaart uren handmatig werk. Sommige teams stappen over van spreadsheets naar database-ondersteunde tools zoals Airtable of Notion voor eenvoudigere samenwerking en filtering.\n\nDe keyword map wordt ook de basis van je rapportage. Wanneer het management vraagt waarom organisch verkeer vorig kwartaal met 15% is gegroeid, kun je wijzen op specifieke zoekwoorden die werden toegewezen, pagina's die werden geoptimaliseerd en rankings die verbeterden, allemaal bijgehouden in één document.\n\nOnze gids over [ecommerce-SEO-strategie](/blog/ecommerce-seo-strategy) behandelt deze aanpak uitgebreid.",
        },
      ],
      navLabels: {
        previous: "Concurrentie-zoekwoordanalyse",
        next: "Seizoensgebonden zoekwoordtrends",
      },
    },
  },
};
