import type { AcademyTopic } from "../../types";

export const magentoSeoGuide: AcademyTopic = {
  slug: "magento-seo-guide",
  cluster: 8,
  content: {
    en: {
      badge: "Platform SEO",
      heading: "Magento SEO Guide",
      intro:
        "Magento (now Adobe Commerce) offers unmatched flexibility for ecommerce SEO, but that flexibility comes with complexity. Unlike hosted platforms that handle many SEO basics automatically, Magento requires deliberate configuration to avoid duplicate content, manage crawl budget, and optimize page speed. Mastering Magento's SEO settings and common pitfalls lets you leverage the platform's power to build a highly optimized, large-scale ecommerce store.",
      readTime: "13 min read",
      sections: [
        {
          title: "Magento URL Structure and Rewrites",
          content:
            "Magento's default URL structure generates clean, SEO-friendly URLs for products and categories, but the platform has several URL-related pitfalls that create duplicate content if left unconfigured. The most critical setting is under Stores, then Configuration, then Catalog, then Search Engine Optimization. Here you must enable URL rewrites and set the canonical link meta tag to yes for both categories and products.\n\nBy default, Magento can generate multiple URLs for the same product. A product may be accessible at /product-name.html, /category/product-name.html, and /another-category/product-name.html if the product belongs to multiple categories. Without canonical tags, Google sees three separate pages with identical content. Enable the Use Canonical Link Meta Tag setting to tell Google which URL is the primary version.\n\nURL suffixes are another consideration. Magento lets you add .html or any other suffix to product and category URLs. While the suffix itself does not affect SEO, changing it after your site is indexed will break all existing URLs. If you need to change the suffix, create redirect rules in your .htaccess file or use Magento's built-in URL rewrite system to map old URLs to new ones.\n\nFor large catalogs with hundreds of categories, consider your URL hierarchy carefully. Magento can create deeply nested URLs like /mens/clothing/shirts/casual/blue-oxford-shirt.html. While Google can crawl deep URLs, shorter paths tend to perform slightly better in click-through rates. Configure your category URL structure to balance descriptiveness with brevity. Many successful Magento stores use a flat structure like /blue-oxford-shirt.html for products, reserving the hierarchical path for category pages only.",
          items: [
            "Enable canonical link meta tags for both products and categories in Magento configuration",
            "Resolve multi-category URL duplication by choosing a single canonical product URL pattern",
            "Keep URL suffixes consistent after launch to avoid mass redirect requirements",
            "Consider flat product URL structures for large catalogs to improve crawlability",
          ],
          tip: "After configuring URL settings, use Screaming Frog to crawl your Magento site and check for duplicate pages. Filter by canonical tag status to find pages where the canonical points to a different URL. Address any mismatches before Google indexes both versions.",
        },
        {
          title: "Managing Layered Navigation and Faceted URLs",
          content:
            "Layered navigation is Magento's term for faceted filtering, which lets customers narrow products by attributes like size, color, price, and brand. While essential for user experience, layered navigation creates a massive crawl budget problem. Every filter combination generates a unique URL, and a catalog with ten attributes of ten values each can produce millions of filterable URL combinations.\n\nThe default Magento behavior appends filter parameters to the URL, creating paths like /shoes.html?color=red&size=10&brand=nike. Google will attempt to crawl all these combinations, consuming crawl budget on pages that add no unique indexable value. For stores with large catalogs, this can prevent Google from efficiently crawling and indexing your actual product and category pages.\n\nThe most effective approach is to use AJAX-based filtering that does not change the URL at all. Several Magento extensions implement this pattern, loading filtered results dynamically while keeping the URL as /shoes.html. This eliminates the faceted URL problem entirely. If you cannot implement AJAX filtering, add noindex meta robots tags to all filtered pages and block the filter parameters in robots.txt.\n\nHowever, some filter combinations do have SEO value. A page showing all red Nike running shoes might match a valuable search query. For these specific cases, create dedicated landing pages with unique content rather than relying on the filtered navigation URL. A purpose-built landing page at /red-nike-running-shoes.html will always outperform a filtered URL because you can add unique descriptions, internal links, and structured data.\n\nMonitor your Google Search Console coverage report for signs of faceted URL problems. If you see hundreds of thousands of discovered but not indexed URLs, or if your crawl stats show Googlebot requesting filter parameter URLs at high volume, your layered navigation is consuming crawl budget that should go to your product pages.",
          items: [
            "Implement AJAX-based filtering to prevent faceted URLs from being generated",
            "Add noindex tags and robots.txt blocks for filter parameter URLs you cannot eliminate",
            "Create dedicated landing pages for high-value filter combinations with unique content",
            "Monitor Search Console coverage for signs of crawl budget waste from faceted URLs",
          ],
        },
        {
          title: "Magento Page Speed Optimization",
          content:
            "Magento sites historically struggle with page speed, and slow load times directly impact both rankings and conversion rates. A typical unoptimized Magento installation loads product pages in four to eight seconds, far exceeding Google's recommended threshold. Systematic optimization can bring this under two seconds for most pages.\n\nEnable Magento's built-in full-page cache, which is the single highest-impact speed improvement available. For Magento 2, Varnish is the recommended caching layer. Configure Varnish as a reverse proxy in front of your Magento server, and full-page load times will drop dramatically for returning visitors and any page that has been previously cached. Without full-page caching, every request hits the PHP application layer, which is inherently slow for complex Magento pages.\n\nOptimize JavaScript and CSS delivery. Magento loads numerous JavaScript files and CSS stylesheets by default. Enable JS and CSS merging and minification in Stores, Configuration, Developer settings. Consider implementing critical CSS extraction, which inlines the above-the-fold styles and defers the rest. Extensions like MagePack or Defer JS can help reduce render-blocking resources.\n\nImage optimization is essential for product-heavy ecommerce pages. Implement WebP format with JPEG fallback for all product and category images. Use lazy loading for images below the fold so the browser does not download all product grid images simultaneously. Magento 2.4 and later includes native lazy loading support. For earlier versions, add a lazy loading extension or implement it via JavaScript.\n\nConsider using a Content Delivery Network for static assets. Serve images, CSS, and JavaScript from CDN edge servers located geographically close to your customers. Configure Magento to use the CDN URL for all static content under Stores, Configuration, Web, Base URLs for Static View Files. This reduces server load and improves load times for visitors far from your primary hosting location.",
          tip: "Test page speed on product pages, category pages, and the homepage separately. Magento category pages with large product grids often have different performance bottlenecks than product detail pages. Your optimization priorities may differ by page type.",
        },
        {
          title: "Structured Data and Rich Results",
          content:
            "Magento does not implement comprehensive structured data out of the box, which means you miss opportunities for rich results in Google search. Adding Product, BreadcrumbList, Organization, and Review schema markup can significantly improve your click-through rates from organic search.\n\nProduct schema is the most impactful for ecommerce. Each product page should include JSON-LD markup with name, description, image, sku, brand, offers (including price, currency, availability, and price valid until date), and aggregate rating if you have reviews. Magento extensions like Amasty SEO Suite or Mageplaza SEO handle this automatically, or your development team can add it via layout XML and template modifications.\n\nBreadcrumb schema helps Google display your site hierarchy in search results, replacing the raw URL with a clickable breadcrumb trail. This improves both aesthetics and click-through rates. Implement BreadcrumbList JSON-LD on every page, mapping your Magento category hierarchy into the structured data. Ensure the breadcrumb path matches what users see on the page.\n\nFor stores with physical locations, add LocalBusiness schema to your store locator pages. This helps your physical locations appear in Google Maps and local search results. Include address, phone number, opening hours, and geo coordinates for each location.\n\nReview markup deserves careful handling. Only implement AggregateRating schema if you have genuine customer reviews on your product pages. Google penalizes sites that show review stars for pages without actual reviews. If you use a third-party review platform like Trustpilot or Yotpo, ensure their Magento integration outputs the correct schema markup. Validate all structured data using Google's Rich Results Test after implementation.",
          items: [
            "Add Product schema with name, price, availability, SKU, and reviews to all product pages",
            "Implement BreadcrumbList schema matching your visible breadcrumb navigation",
            "Add LocalBusiness schema to store locator pages for physical retail locations",
            "Validate all structured data with Google's Rich Results Test before and after deployment",
          ],
        },
        {
          title: "XML Sitemaps and Crawl Management",
          content:
            "Magento generates XML sitemaps automatically, but the default configuration often includes pages that should not be in the sitemap. A poorly configured sitemap sends Google to low-value or duplicate pages, wasting the crawl budget you need for your actual product catalog.\n\nConfigure your sitemap settings under Stores, Configuration, Catalog, XML Sitemap. Disable inclusion of out-of-stock products unless you plan to restock them. Exclude CMS pages that are not meant for organic search, such as terms and conditions, privacy policy, and return policy pages. These pages should be indexable but do not benefit from sitemap inclusion because Google already discovers them through internal links.\n\nFor large Magento catalogs with more than 50,000 URLs, Magento automatically splits the sitemap into multiple files with a sitemap index. Verify this is working correctly because a single sitemap file exceeding the 50,000 URL or 50MB limit will be rejected by Google. Check the generated sitemap files in your root directory and confirm they validate against the sitemap protocol.\n\nSupplement Magento's auto-generated sitemaps with a manual review of what is included. Crawl your site with Screaming Frog and compare the discovered URLs against the sitemap. If the crawler finds pages that are not in the sitemap but should be, add them. If the sitemap contains URLs that return 404 errors, redirect loops, or noindex tags, remove them. A clean sitemap that only contains indexable, canonical URLs tells Google exactly which pages you consider important.\n\nSubmit your sitemaps through Google Search Console and monitor the indexation ratio. If Google indexes significantly fewer URLs than your sitemap contains, investigate why. Common Magento issues include orphaned products not linked from any category, product pages with noindex tags from a misconfigured extension, and canonical tags pointing to different URLs than those in the sitemap.",
          items: [
            "Exclude out-of-stock products and non-SEO CMS pages from Magento's XML sitemap",
            "Verify automatic sitemap splitting works for catalogs exceeding 50,000 URLs",
            "Cross-reference crawled URLs against sitemap contents to find gaps and errors",
            "Monitor Search Console indexation ratio to identify discrepancies between submitted and indexed URLs",
          ],
          tip: "Set up a monthly automated comparison between your sitemap URLs and your Google Search Console indexed pages report. Any growing gap between submitted and indexed URLs signals a crawling or indexation problem that needs investigation before it impacts your organic traffic.",
        },
        {
          title: "Common Magento SEO Mistakes to Avoid",
          content:
            "The most damaging Magento SEO mistake is ignoring duplicate content caused by configurable products. When a configurable product like a t-shirt has size and color variations, Magento can create individual simple product URLs for each variation. A t-shirt in three sizes and four colors produces twelve simple product pages with nearly identical content, plus the configurable product page itself. Set simple products associated with configurables to Not Visible Individually in the product visibility settings to prevent this duplication.\n\nAnother common mistake is leaving Magento's default meta title and description templates unchanged. The default title format of Product Name - Store Name produces titles that lack keywords and waste character space. Customize the title format in Content, Design, HTML Head to include category context and relevant keywords. A better format might be Product Name - Category | Store Name, which adds topical relevance.\n\nMagento's built-in search creates indexable search result pages by default. Every search query generates a URL like /catalogsearch/result/?q=query that Google can discover and crawl. These pages add no value because they are thin content pages that often show the same products as your category pages. Block /catalogsearch/ in robots.txt and add noindex tags to the search results template.\n\nFailing to handle out-of-stock products properly is another frequent issue. When products go out of stock, many store owners delete the product or let Magento return a 404 error. Both approaches waste the SEO equity those product pages accumulated. Instead, keep out-of-stock product pages live with a clear out-of-stock message and suggest alternative products. If the product is permanently discontinued, redirect the URL to the most relevant category or replacement product page.\n\nFinally, many Magento stores neglect mobile optimization. While Magento 2 themes are responsive by default, heavy customizations often break mobile layouts or introduce mobile-specific performance issues. Since Google uses mobile-first indexing, your mobile site experience directly determines your rankings. Test your customized Magento theme on actual mobile devices, not just browser emulation.",
          items: [
            "Set simple products of configurables to Not Visible Individually to prevent content duplication",
            "Customize default meta title templates to include category context and relevant keywords",
            "Block and noindex the internal search results pages at /catalogsearch/",
            "Keep out-of-stock product pages live with alternatives rather than returning 404 errors",
            "Test mobile experience on real devices since Google uses mobile-first indexing",
          ],
        },
      ],
      navLabels: {
        previous: "Previous",
        next: "Next",
      },
    },
    de: {
      badge: "Plattform-SEO",
      heading: "Magento SEO-Leitfaden",
      intro:
        "Magento (jetzt Adobe Commerce) bietet unuebertroffene Flexibilitaet fuer E-Commerce-SEO, aber diese Flexibilitaet bringt Komplexitaet mit sich. Im Gegensatz zu gehosteten Plattformen, die viele SEO-Grundlagen automatisch handhaben, erfordert Magento bewusste Konfiguration, um Duplicate Content zu vermeiden, das Crawl-Budget zu verwalten und die Seitengeschwindigkeit zu optimieren. Die Beherrschung von Magentos SEO-Einstellungen und typischen Fallstricken ermoeglicht es Ihnen, die Leistung der Plattform fuer einen hochoptimierten, grossangelegten E-Commerce-Shop zu nutzen.",
      readTime: "13 Min. Lesezeit",
      sections: [
        {
          title: "Magento URL-Struktur und Rewrites",
          content:
            "Magentos Standard-URL-Struktur generiert saubere, SEO-freundliche URLs fuer Produkte und Kategorien, aber die Plattform hat mehrere URL-bezogene Fallstricke, die ohne Konfiguration Duplicate Content erzeugen. Die wichtigste Einstellung befindet sich unter Stores, Konfiguration, Katalog, Suchmaschinenoptimierung. Hier muessen Sie URL-Rewrites aktivieren und das Canonical-Link-Meta-Tag fuer Kategorien und Produkte auf Ja setzen.\n\nStandardmaessig kann Magento mehrere URLs fuer dasselbe Produkt generieren. Ein Produkt kann unter /product-name.html, /category/product-name.html und /another-category/product-name.html erreichbar sein, wenn es mehreren Kategorien zugeordnet ist. Ohne Canonical Tags sieht Google drei separate Seiten mit identischem Inhalt.\n\nURL-Suffixe sind eine weitere Ueberlegung. Magento erlaubt das Hinzufuegen von .html oder anderem Suffix zu Produkt- und Kategorie-URLs. Waehrend das Suffix selbst SEO nicht beeinflusst, wird eine Aenderung nach der Indexierung alle bestehenden URLs brechen. Erstellen Sie bei Aenderungen Redirect-Regeln in Ihrer .htaccess-Datei.\n\nFuer grosse Kataloge mit Hunderten von Kategorien planen Sie Ihre URL-Hierarchie sorgfaeltig. Magento kann tief verschachtelte URLs wie /herren/bekleidung/hemden/casual/blaues-oxford-hemd.html erstellen. Konfigurieren Sie Ihre Kategorie-URL-Struktur, um Beschreibungsgehalt und Kuerze auszubalancieren. Viele erfolgreiche Magento-Shops verwenden eine flache Struktur wie /blaues-oxford-hemd.html fuer Produkte.",
          items: [
            "Aktivieren Sie Canonical-Link-Meta-Tags fuer Produkte und Kategorien in der Magento-Konfiguration",
            "Loesen Sie Multi-Kategorie-URL-Duplizierung durch Wahl eines einheitlichen kanonischen Produkt-URL-Musters",
            "Halten Sie URL-Suffixe nach dem Launch konsistent, um Massenredirects zu vermeiden",
            "Erwaegen Sie flache Produkt-URL-Strukturen fuer grosse Kataloge zur Verbesserung der Crawlbarkeit",
          ],
          tip: "Crawlen Sie Ihre Magento-Seite nach der URL-Konfiguration mit Screaming Frog und pruefen Sie auf doppelte Seiten. Filtern Sie nach Canonical-Tag-Status, um Seiten zu finden, deren Canonical auf eine andere URL zeigt. Beheben Sie Diskrepanzen, bevor Google beide Versionen indexiert.",
        },
        {
          title: "Layered Navigation und facettierte URLs verwalten",
          content:
            "Layered Navigation ist Magentos Begriff fuer facettierte Filterung, die Kunden ermoeglicht, Produkte nach Attributen wie Groesse, Farbe, Preis und Marke einzugrenzen. Obwohl fuer die Benutzererfahrung essentiell, erzeugt Layered Navigation ein massives Crawl-Budget-Problem. Jede Filterkombination generiert eine einzigartige URL, und ein Katalog mit zehn Attributen mit je zehn Werten kann Millionen filterbarer URL-Kombinationen produzieren.\n\nDas Standard-Magento-Verhalten haengt Filterparameter an die URL an und erzeugt Pfade wie /schuhe.html?farbe=rot&groesse=42&marke=nike. Google wird versuchen, alle diese Kombinationen zu crawlen und dabei Crawl-Budget fuer Seiten verbrauchen, die keinen einzigartigen indexierbaren Wert haben.\n\nDer effektivste Ansatz ist AJAX-basierte Filterung, die die URL ueberhaupt nicht aendert. Mehrere Magento-Erweiterungen implementieren dieses Muster und laden gefilterte Ergebnisse dynamisch, waehrend die URL als /schuhe.html bestehen bleibt. Falls Sie AJAX-Filterung nicht implementieren koennen, fuegen Sie noindex-Meta-Robots-Tags zu allen gefilterten Seiten hinzu und blockieren Sie die Filterparameter in robots.txt.\n\nEinige Filterkombinationen haben jedoch SEO-Wert. Eine Seite mit allen roten Nike-Laufschuhen koennte zu einer wertvollen Suchanfrage passen. Fuer diese spezifischen Faelle erstellen Sie dedizierte Landing Pages mit einzigartigem Content statt sich auf die gefilterte Navigations-URL zu verlassen.\n\nUeberwachen Sie Ihren Google Search Console-Abdeckungsbericht auf Anzeichen von Problemen mit facettierten URLs. Wenn Sie Hunderttausende entdeckter, aber nicht indexierter URLs sehen, verbraucht Ihre Layered Navigation Crawl-Budget.",
          items: [
            "Implementieren Sie AJAX-basierte Filterung, um die Generierung facettierter URLs zu verhindern",
            "Fuegen Sie noindex-Tags und robots.txt-Blockierungen fuer nicht eliminierbare Filterparameter-URLs hinzu",
            "Erstellen Sie dedizierte Landing Pages fuer hochwertige Filterkombinationen mit einzigartigem Content",
            "Ueberwachen Sie die Search Console-Abdeckung auf Anzeichen von Crawl-Budget-Verschwendung durch facettierte URLs",
          ],
        },
        {
          title: "Magento Seitengeschwindigkeits-Optimierung",
          content:
            "Magento-Seiten kaempfen historisch mit der Seitengeschwindigkeit, und langsame Ladezeiten wirken sich direkt auf Rankings und Conversion-Raten aus. Eine typische unoptimierte Magento-Installation laedt Produktseiten in vier bis acht Sekunden. Systematische Optimierung kann dies fuer die meisten Seiten auf unter zwei Sekunden bringen.\n\nAktivieren Sie Magentos integrierten Full-Page-Cache, die wirkungsvollste Einzelverbesserung der Geschwindigkeit. Fuer Magento 2 ist Varnish die empfohlene Caching-Schicht. Konfigurieren Sie Varnish als Reverse Proxy vor Ihrem Magento-Server, und die Ladezeiten ganzer Seiten sinken drastisch.\n\nOptimieren Sie die JavaScript- und CSS-Auslieferung. Magento laedt standardmaessig zahlreiche JavaScript-Dateien und CSS-Stylesheets. Aktivieren Sie JS- und CSS-Zusammenfuehrung und -Minifizierung unter Stores, Konfiguration, Entwickler-Einstellungen. Erwaegen Sie die Implementierung von Critical CSS Extraction.\n\nBildoptimierung ist essentiell fuer produktlastige E-Commerce-Seiten. Implementieren Sie WebP-Format mit JPEG-Fallback fuer alle Produkt- und Kategoriebilder. Verwenden Sie Lazy Loading fuer Bilder unterhalb des sichtbaren Bereichs. Magento 2.4 und spaeter bietet native Lazy-Loading-Unterstuetzung.\n\nErwaegen Sie die Verwendung eines Content Delivery Networks fuer statische Assets. Liefern Sie Bilder, CSS und JavaScript von CDN-Edge-Servern, die geografisch nahe bei Ihren Kunden liegen. Konfigurieren Sie Magento unter Stores, Konfiguration, Web, Basis-URLs fuer statische View-Dateien.",
          tip: "Testen Sie die Seitengeschwindigkeit auf Produktseiten, Kategorieseiten und der Startseite separat. Magento-Kategorieseiten mit grossen Produktrastern haben oft andere Performance-Engpaesse als Produktdetailseiten. Ihre Optimierungsprioritaeten koennen sich je nach Seitentyp unterscheiden.",
        },
        {
          title: "Strukturierte Daten und Rich Results",
          content:
            "Magento implementiert keine umfassenden strukturierten Daten von Haus aus, was bedeutet, dass Sie Chancen fuer Rich Results in der Google-Suche verpassen. Das Hinzufuegen von Product-, BreadcrumbList-, Organization- und Review-Schema-Markup kann Ihre Klickraten aus der organischen Suche erheblich verbessern.\n\nProdukt-Schema ist am wirkungsvollsten fuer E-Commerce. Jede Produktseite sollte JSON-LD-Markup mit Name, Beschreibung, Bild, SKU, Marke, Angeboten (einschliesslich Preis, Waehrung, Verfuegbarkeit und Gueltigkeitsdatum des Preises) und Gesamtbewertung enthalten. Magento-Erweiterungen wie Amasty SEO Suite oder Mageplaza SEO handhaben dies automatisch.\n\nBreadcrumb-Schema hilft Google, Ihre Site-Hierarchie in den Suchergebnissen anzuzeigen und die rohe URL durch einen klickbaren Breadcrumb-Pfad zu ersetzen. Implementieren Sie BreadcrumbList JSON-LD auf jeder Seite und bilden Sie Ihre Magento-Kategoriehierarchie in den strukturierten Daten ab.\n\nFuer Shops mit physischen Standorten fuegen Sie LocalBusiness-Schema zu Ihren Filialfinder-Seiten hinzu. Dies hilft Ihren physischen Standorten, in Google Maps und lokalen Suchergebnissen zu erscheinen.\n\nBewertungs-Markup verdient sorgfaeltige Behandlung. Implementieren Sie AggregateRating-Schema nur, wenn Sie echte Kundenbewertungen auf Ihren Produktseiten haben. Google bestraft Seiten, die Bewertungssterne fuer Seiten ohne tatsaechliche Bewertungen zeigen. Validieren Sie alle strukturierten Daten mit Googles Rich-Results-Test nach der Implementierung.",
          items: [
            "Fuegen Sie Produkt-Schema mit Name, Preis, Verfuegbarkeit, SKU und Bewertungen zu allen Produktseiten hinzu",
            "Implementieren Sie BreadcrumbList-Schema passend zu Ihrer sichtbaren Breadcrumb-Navigation",
            "Fuegen Sie LocalBusiness-Schema zu Filialfinder-Seiten fuer physische Einzelhandelsstandorte hinzu",
            "Validieren Sie alle strukturierten Daten mit Googles Rich-Results-Test vor und nach der Bereitstellung",
          ],
        },
        {
          title: "XML-Sitemaps und Crawl-Management",
          content:
            "Magento generiert XML-Sitemaps automatisch, aber die Standardkonfiguration schliesst oft Seiten ein, die nicht in der Sitemap sein sollten. Eine schlecht konfigurierte Sitemap sendet Google zu minderwertigen oder doppelten Seiten.\n\nKonfigurieren Sie Ihre Sitemap-Einstellungen unter Stores, Konfiguration, Katalog, XML-Sitemap. Deaktivieren Sie die Aufnahme nicht verfuegbarer Produkte, es sei denn, Sie planen eine Nachbestellung. Schliessen Sie CMS-Seiten aus, die nicht fuer die organische Suche bestimmt sind, wie AGB, Datenschutzrichtlinie und Rueckgabebedingungen.\n\nFuer grosse Magento-Kataloge mit mehr als 50.000 URLs teilt Magento die Sitemap automatisch in mehrere Dateien mit einem Sitemap-Index auf. Ueberpruefen Sie, dass dies korrekt funktioniert, da eine einzelne Sitemap-Datei, die das Limit von 50.000 URLs oder 50 MB ueberschreitet, von Google abgelehnt wird.\n\nErgaenzen Sie Magentos automatisch generierte Sitemaps durch eine manuelle Pruefung des Inhalts. Crawlen Sie Ihre Seite mit Screaming Frog und vergleichen Sie die entdeckten URLs mit der Sitemap. Wenn der Crawler Seiten findet, die nicht in der Sitemap sind, aber sein sollten, fuegen Sie diese hinzu. Wenn die Sitemap URLs enthaelt, die 404-Fehler, Redirect-Schleifen oder noindex-Tags zurueckgeben, entfernen Sie diese.\n\nReichen Sie Ihre Sitemaps ueber die Google Search Console ein und ueberwachen Sie das Indexierungsverhaeltnis. Wenn Google deutlich weniger URLs indexiert als Ihre Sitemap enthaelt, untersuchen Sie die Ursache.",
          items: [
            "Schliessen Sie nicht verfuegbare Produkte und nicht-SEO-CMS-Seiten aus Magentos XML-Sitemap aus",
            "Ueberpruefen Sie, dass die automatische Sitemap-Aufteilung fuer Kataloge mit ueber 50.000 URLs funktioniert",
            "Vergleichen Sie gecrawlte URLs mit dem Sitemap-Inhalt, um Luecken und Fehler zu finden",
            "Ueberwachen Sie das Indexierungsverhaeltnis in der Search Console, um Diskrepanzen zu identifizieren",
          ],
          tip: "Richten Sie einen monatlichen automatisierten Vergleich zwischen Ihren Sitemap-URLs und dem Bericht indexierter Seiten in der Google Search Console ein. Jede wachsende Luecke zwischen eingereichten und indexierten URLs signalisiert ein Crawling- oder Indexierungsproblem.",
        },
        {
          title: "Haeufige Magento-SEO-Fehler vermeiden",
          content:
            "Der schaedlichste Magento-SEO-Fehler ist das Ignorieren von Duplicate Content durch konfigurierbare Produkte. Wenn ein konfigurierbares Produkt wie ein T-Shirt Groessen- und Farbvarianten hat, kann Magento individuelle einfache Produkt-URLs fuer jede Variante erstellen. Ein T-Shirt in drei Groessen und vier Farben produziert zwoelf einfache Produktseiten mit nahezu identischem Inhalt. Setzen Sie einfache Produkte, die mit Konfigurierbaren verbunden sind, auf Nicht einzeln sichtbar in den Produktsichtbarkeitseinstellungen.\n\nEin weiterer haeufiger Fehler ist das Belassen von Magentos Standard-Meta-Titel- und -Beschreibungsvorlagen. Das Standardformat Produktname - Shopname produziert Titel ohne Keywords. Passen Sie das Titelformat unter Content, Design, HTML-Kopf an. Ein besseres Format koennte Produktname - Kategorie | Shopname sein.\n\nMagentos integrierte Suche erstellt standardmaessig indexierbare Suchergebnisseiten. Jede Suchanfrage generiert eine URL wie /catalogsearch/result/?q=anfrage. Diese Seiten haben keinen Wert, da sie Thin-Content-Seiten sind. Blockieren Sie /catalogsearch/ in robots.txt und fuegen Sie noindex-Tags hinzu.\n\nDas falsche Handling von nicht verfuegbaren Produkten ist ein weiteres haeufiges Problem. Wenn Produkte nicht mehr verfuegbar sind, loeschen viele Shopbetreiber das Produkt oder lassen Magento einen 404-Fehler zurueckgeben. Beide Ansaetze verschwenden die SEO-Equity, die diese Produktseiten aufgebaut haben. Halten Sie stattdessen nicht verfuegbare Produktseiten mit einer klaren Meldung aktiv.\n\nSchliesslich vernachlaessigen viele Magento-Shops die mobile Optimierung. Obwohl Magento 2-Themes standardmaessig responsiv sind, brechen umfangreiche Anpassungen oft mobile Layouts. Da Google Mobile-First-Indexierung verwendet, bestimmt Ihre mobile Erfahrung direkt Ihre Rankings.",
          items: [
            "Setzen Sie einfache Produkte von Konfigurierbaren auf Nicht einzeln sichtbar, um Inhalts-Duplizierung zu verhindern",
            "Passen Sie Standard-Meta-Titel-Vorlagen an, um Kategoriekontext und relevante Keywords einzubeziehen",
            "Blockieren Sie die internen Suchergebnisseiten unter /catalogsearch/ und setzen Sie noindex",
            "Halten Sie nicht verfuegbare Produktseiten mit Alternativen aktiv statt 404-Fehler zurueckzugeben",
            "Testen Sie die mobile Erfahrung auf echten Geraeten, da Google Mobile-First-Indexierung verwendet",
          ],
        },
      ],
      navLabels: {
        previous: "Zurueck",
        next: "Weiter",
      },
    },
    fr: {
      badge: "SEO par plateforme",
      heading: "Guide SEO Magento",
      intro:
        "Magento (desormais Adobe Commerce) offre une flexibilite inegalee pour le SEO e-commerce, mais cette flexibilite s'accompagne de complexite. Contrairement aux plateformes hebergees qui gerent automatiquement de nombreuses bases SEO, Magento necessite une configuration deliberee pour eviter le contenu duplique, gerer le budget de crawl et optimiser la vitesse des pages. Maitriser les parametres SEO de Magento et les pieges courants vous permet d'exploiter la puissance de la plateforme pour construire une boutique e-commerce hautement optimisee et a grande echelle.",
      readTime: "13 min de lecture",
      sections: [
        {
          title: "Structure d'URL et reecritures Magento",
          content:
            "La structure d'URL par defaut de Magento genere des URLs propres et SEO-friendly pour les produits et categories, mais la plateforme a plusieurs pieges lies aux URLs qui creent du contenu duplique si non configures. Le parametre le plus critique se trouve sous Stores, Configuration, Catalogue, Optimisation des moteurs de recherche. Ici, vous devez activer les reecritures d'URL et definir la balise meta de lien canonique sur oui pour les categories et les produits.\n\nPar defaut, Magento peut generer plusieurs URLs pour le meme produit. Un produit peut etre accessible a /nom-produit.html, /categorie/nom-produit.html et /autre-categorie/nom-produit.html s'il appartient a plusieurs categories. Sans balises canoniques, Google voit trois pages separees avec un contenu identique.\n\nLes suffixes d'URL sont une autre consideration. Magento permet d'ajouter .html ou tout autre suffixe aux URLs de produits et categories. Bien que le suffixe lui-meme n'affecte pas le SEO, le modifier apres l'indexation de votre site cassera toutes les URLs existantes.\n\nPour les grands catalogues avec des centaines de categories, planifiez votre hierarchie d'URL soigneusement. Magento peut creer des URLs profondement imbriquees. Configurez votre structure d'URL de categorie pour equilibrer description et brievete. Beaucoup de boutiques Magento prosperes utilisent une structure plate comme /chemise-oxford-bleue.html pour les produits.",
          items: [
            "Activez les balises meta de lien canonique pour les produits et categories dans la configuration Magento",
            "Resolvez la duplication d'URL multi-categories en choisissant un patron d'URL canonique unique",
            "Gardez les suffixes d'URL coherents apres le lancement pour eviter les redirections massives",
            "Envisagez des structures d'URL produit plates pour les grands catalogues afin d'ameliorer la crawlabilite",
          ],
          tip: "Apres avoir configure les parametres d'URL, utilisez Screaming Frog pour crawler votre site Magento et verifier les pages en double. Filtrez par statut de balise canonique pour trouver les pages ou le canonical pointe vers une URL differente.",
        },
        {
          title: "Gerer la navigation a facettes et les URLs facettees",
          content:
            "La navigation par couches est le terme de Magento pour le filtrage a facettes, qui permet aux clients d'affiner les produits par attributs comme la taille, la couleur, le prix et la marque. Bien qu'essentielle pour l'experience utilisateur, la navigation par couches cree un probleme massif de budget de crawl. Chaque combinaison de filtres genere une URL unique, et un catalogue avec dix attributs de dix valeurs chacun peut produire des millions de combinaisons.\n\nLe comportement par defaut de Magento ajoute les parametres de filtre a l'URL, creant des chemins comme /chaussures.html?couleur=rouge&taille=42&marque=nike. Google tentera de crawler toutes ces combinaisons, consommant du budget de crawl sur des pages sans valeur unique.\n\nL'approche la plus efficace est d'utiliser un filtrage base sur AJAX qui ne change pas du tout l'URL. Plusieurs extensions Magento implementent ce pattern. Si vous ne pouvez pas implementer le filtrage AJAX, ajoutez des balises meta robots noindex a toutes les pages filtrees et bloquez les parametres de filtre dans robots.txt.\n\nCependant, certaines combinaisons de filtres ont une valeur SEO. Une page montrant toutes les chaussures de course Nike rouges pourrait correspondre a une requete de recherche precieuse. Pour ces cas specifiques, creez des pages d'atterrissage dediees avec du contenu unique.\n\nSurveillez votre rapport de couverture Google Search Console pour les signes de problemes d'URL facettees.",
          items: [
            "Implementez un filtrage AJAX pour empecher la generation d'URLs facettees",
            "Ajoutez des balises noindex et des blocages robots.txt pour les URLs de parametres de filtre",
            "Creez des pages d'atterrissage dediees pour les combinaisons de filtres a haute valeur avec du contenu unique",
            "Surveillez la couverture Search Console pour les signes de gaspillage de budget de crawl",
          ],
        },
        {
          title: "Optimisation de la vitesse des pages Magento",
          content:
            "Les sites Magento luttent historiquement avec la vitesse des pages, et les temps de chargement lents impactent directement les classements et les taux de conversion. Une installation Magento non optimisee charge typiquement les pages produit en quatre a huit secondes. L'optimisation systematique peut ramener cela sous deux secondes.\n\nActivez le cache de page complet integre de Magento. Pour Magento 2, Varnish est la couche de cache recommandee. Configurez Varnish comme proxy inverse devant votre serveur Magento.\n\nOptimisez la livraison JavaScript et CSS. Magento charge de nombreux fichiers JavaScript et feuilles de style CSS par defaut. Activez la fusion et la minification JS et CSS dans les parametres Developpeur. Envisagez l'extraction CSS critique.\n\nL'optimisation des images est essentielle pour les pages e-commerce riches en produits. Implementez le format WebP avec fallback JPEG pour toutes les images. Utilisez le chargement paresseux pour les images sous le pli. Magento 2.4 et versions ulterieures incluent le support natif du chargement paresseux.\n\nEnvisagez l'utilisation d'un reseau de diffusion de contenu pour les actifs statiques. Servez images, CSS et JavaScript depuis des serveurs CDN edge geographiquement proches de vos clients.",
          tip: "Testez la vitesse des pages sur les pages produit, les pages categorie et la page d'accueil separement. Les pages categorie Magento avec de grandes grilles de produits ont souvent des goulots d'etranglement differents des pages de detail produit.",
        },
        {
          title: "Donnees structurees et resultats enrichis",
          content:
            "Magento n'implemente pas de donnees structurees completes nativement, ce qui signifie que vous manquez des opportunites de resultats enrichis dans la recherche Google. L'ajout du balisage schema Product, BreadcrumbList, Organization et Review peut significativement ameliorer vos taux de clics.\n\nLe schema Produit est le plus impactant pour l'e-commerce. Chaque page produit devrait inclure du balisage JSON-LD avec nom, description, image, SKU, marque, offres et note globale si vous avez des avis. Des extensions Magento comme Amasty SEO Suite ou Mageplaza SEO gerent cela automatiquement.\n\nLe schema Breadcrumb aide Google a afficher votre hierarchie de site dans les resultats de recherche. Implementez BreadcrumbList JSON-LD sur chaque page.\n\nPour les boutiques avec des emplacements physiques, ajoutez le schema LocalBusiness a vos pages de localisation de magasin. Incluez adresse, numero de telephone, horaires d'ouverture et coordonnees geographiques.\n\nLe balisage d'avis merite un traitement soigneux. N'implementez le schema AggregateRating que si vous avez de vrais avis clients. Google penalise les sites qui affichent des etoiles d'avis sans avis reels. Validez toutes les donnees structurees avec le test des resultats enrichis de Google.",
          items: [
            "Ajoutez le schema Produit avec nom, prix, disponibilite, SKU et avis a toutes les pages produit",
            "Implementez le schema BreadcrumbList correspondant a votre navigation fil d'Ariane visible",
            "Ajoutez le schema LocalBusiness aux pages de localisation pour les emplacements physiques",
            "Validez toutes les donnees structurees avec le test des resultats enrichis de Google",
          ],
        },
        {
          title: "Sitemaps XML et gestion du crawl",
          content:
            "Magento genere des sitemaps XML automatiquement, mais la configuration par defaut inclut souvent des pages qui ne devraient pas y etre. Un sitemap mal configure envoie Google vers des pages a faible valeur ou dupliquees.\n\nConfigurez vos parametres de sitemap sous Stores, Configuration, Catalogue, Sitemap XML. Desactivez l'inclusion des produits en rupture de stock sauf si vous prevoyez de les reapprovisionner. Excluez les pages CMS non destinees a la recherche organique.\n\nPour les grands catalogues Magento avec plus de 50 000 URLs, Magento divise automatiquement le sitemap en plusieurs fichiers avec un index de sitemap. Verifiez que cela fonctionne correctement car un fichier sitemap unique depassant la limite sera rejete par Google.\n\nCompletez les sitemaps auto-generes de Magento par une revision manuelle du contenu. Crawlez votre site avec Screaming Frog et comparez les URLs decouvertes au sitemap.\n\nSoumettez vos sitemaps via Google Search Console et surveillez le ratio d'indexation. Si Google indexe significativement moins d'URLs que votre sitemap en contient, investiguer pourquoi.",
          items: [
            "Excluez les produits en rupture de stock et les pages CMS non-SEO du sitemap XML Magento",
            "Verifiez que la division automatique du sitemap fonctionne pour les catalogues de plus de 50 000 URLs",
            "Comparez les URLs crawlees avec le contenu du sitemap pour trouver les ecarts et erreurs",
            "Surveillez le ratio d'indexation dans Search Console pour identifier les ecarts",
          ],
          tip: "Mettez en place une comparaison mensuelle automatisee entre les URLs de votre sitemap et le rapport de pages indexees de Google Search Console. Tout ecart croissant signale un probleme de crawl ou d'indexation qui necessite une investigation.",
        },
        {
          title: "Erreurs SEO Magento courantes a eviter",
          content:
            "L'erreur SEO Magento la plus dommageable est d'ignorer le contenu duplique cause par les produits configurables. Quand un produit configurable comme un t-shirt a des variations de taille et de couleur, Magento peut creer des URLs de produits simples individuels pour chaque variation. Definissez les produits simples associes aux configurables sur Non visible individuellement dans les parametres de visibilite.\n\nUne autre erreur courante est de laisser les modeles de meta titre et description par defaut de Magento inchanges. Le format par defaut Nom du produit - Nom de la boutique produit des titres manquant de mots-cles. Personnalisez le format du titre pour inclure le contexte de categorie et les mots-cles pertinents.\n\nLa recherche integree de Magento cree des pages de resultats de recherche indexables par defaut. Chaque requete de recherche genere une URL comme /catalogsearch/result/?q=requete. Bloquez /catalogsearch/ dans robots.txt et ajoutez des balises noindex.\n\nNe pas gerer correctement les produits en rupture de stock est un autre probleme frequent. Quand les produits sont en rupture, beaucoup de proprietaires suppriment le produit ou laissent Magento retourner une erreur 404. Gardez plutot les pages de produits en rupture actives avec un message clair et suggerez des alternatives.\n\nEnfin, beaucoup de boutiques Magento negligent l'optimisation mobile. Bien que les themes Magento 2 soient responsifs par defaut, les personnalisations lourdes cassent souvent les mises en page mobiles. Puisque Google utilise l'indexation mobile-first, votre experience mobile determine directement vos classements.",
          items: [
            "Definissez les produits simples des configurables sur Non visible individuellement",
            "Personnalisez les modeles de meta titre par defaut pour inclure le contexte de categorie",
            "Bloquez et mettez noindex les pages de resultats de recherche interne a /catalogsearch/",
            "Gardez les pages de produits en rupture actives avec des alternatives plutot que des erreurs 404",
            "Testez l'experience mobile sur de vrais appareils car Google utilise l'indexation mobile-first",
          ],
        },
      ],
      navLabels: {
        previous: "Precedent",
        next: "Suivant",
      },
    },
    es: {
      badge: "SEO por plataforma",
      heading: "Guia SEO para Magento",
      intro:
        "Magento (ahora Adobe Commerce) ofrece una flexibilidad inigualable para el SEO de ecommerce, pero esa flexibilidad viene con complejidad. A diferencia de las plataformas alojadas que manejan automaticamente muchos aspectos basicos del SEO, Magento requiere configuracion deliberada para evitar contenido duplicado, gestionar el presupuesto de rastreo y optimizar la velocidad de pagina. Dominar la configuracion SEO de Magento y sus trampas comunes te permite aprovechar el poder de la plataforma para construir una tienda ecommerce altamente optimizada a gran escala.",
      readTime: "13 min de lectura",
      sections: [
        { title: "Estructura de URLs y reescrituras en Magento", content: "La estructura de URLs predeterminada de Magento genera URLs limpias y amigables para SEO para productos y categorias, pero la plataforma tiene varias trampas relacionadas con URLs que crean contenido duplicado si no se configuran. La configuracion mas critica esta en Tiendas, Configuracion, Catalogo, Optimizacion de motores de busqueda. Aqui debes habilitar las reescrituras de URL y establecer la etiqueta meta de enlace canonico en si para categorias y productos.\n\nPor defecto, Magento puede generar multiples URLs para el mismo producto. Un producto puede ser accesible en /nombre-producto.html, /categoria/nombre-producto.html y /otra-categoria/nombre-producto.html si pertenece a multiples categorias. Sin etiquetas canonicas, Google ve tres paginas separadas con contenido identico.\n\nLos sufijos de URL son otra consideracion. Magento permite agregar .html u otro sufijo a las URLs de productos y categorias. Mientras que el sufijo en si no afecta el SEO, cambiarlo despues de que tu sitio este indexado rompera todas las URLs existentes.\n\nPara catalogos grandes con cientos de categorias, planifica tu jerarquia de URLs cuidadosamente. Magento puede crear URLs profundamente anidadas. Configura la estructura de URLs de categoria para equilibrar descriptividad con brevedad. Muchas tiendas Magento exitosas usan una estructura plana como /camisa-oxford-azul.html para productos.", items: ["Habilita las etiquetas meta de enlace canonico para productos y categorias en la configuracion de Magento", "Resuelve la duplicacion de URLs multi-categoria eligiendo un patron canonico unico de URL de producto", "Mantén los sufijos de URL consistentes despues del lanzamiento para evitar redirects masivos", "Considera estructuras de URL planas para catalogos grandes para mejorar la rastreabilidad"], tip: "Despues de configurar los ajustes de URL, usa Screaming Frog para rastrear tu sitio Magento y verificar paginas duplicadas. Filtra por estado de etiqueta canonica para encontrar paginas donde el canonico apunta a una URL diferente." },
        { title: "Gestionar la navegacion por capas y URLs facetadas", content: "La navegacion por capas es el termino de Magento para el filtrado facetado, que permite a los clientes filtrar productos por atributos como tamano, color, precio y marca. Aunque esencial para la experiencia del usuario, la navegacion por capas crea un problema masivo de presupuesto de rastreo. Cada combinacion de filtros genera una URL unica, y un catalogo con diez atributos de diez valores cada uno puede producir millones de combinaciones.\n\nEl comportamiento predeterminado de Magento agrega parametros de filtro a la URL, creando rutas como /zapatos.html?color=rojo&talla=42&marca=nike. Google intentara rastrear todas estas combinaciones, consumiendo presupuesto de rastreo en paginas sin valor unico.\n\nEl enfoque mas efectivo es usar filtrado basado en AJAX que no cambie la URL en absoluto. Varias extensiones de Magento implementan este patron. Si no puedes implementar filtrado AJAX, agrega etiquetas meta robots noindex a todas las paginas filtradas y bloquea los parametros de filtro en robots.txt.\n\nSin embargo, algunas combinaciones de filtros tienen valor SEO. Para estos casos especificos, crea paginas de destino dedicadas con contenido unico en lugar de depender de la URL de navegacion filtrada.\n\nMonitorea tu reporte de cobertura de Google Search Console para signos de problemas con URLs facetadas.", items: ["Implementa filtrado basado en AJAX para prevenir la generacion de URLs facetadas", "Agrega etiquetas noindex y bloqueos en robots.txt para URLs de parametros de filtro que no puedas eliminar", "Crea paginas de destino dedicadas para combinaciones de filtros de alto valor con contenido unico", "Monitorea la cobertura de Search Console para signos de desperdicio de presupuesto de rastreo"] },
        { title: "Optimizacion de velocidad de pagina en Magento", content: "Los sitios Magento historicamente luchan con la velocidad de pagina, y los tiempos de carga lentos impactan directamente tanto los rankings como las tasas de conversion. Una instalacion Magento tipica sin optimizar carga paginas de producto en cuatro a ocho segundos. La optimizacion sistematica puede llevar esto a menos de dos segundos.\n\nHabilita la cache de pagina completa integrada de Magento, que es la mejora de velocidad de mayor impacto disponible. Para Magento 2, Varnish es la capa de cache recomendada. Configura Varnish como proxy inverso frente a tu servidor Magento.\n\nOptimiza la entrega de JavaScript y CSS. Magento carga numerosos archivos JavaScript y hojas de estilo CSS por defecto. Habilita la fusion y minificacion de JS y CSS en los ajustes de Desarrollador. Considera implementar extraccion de CSS critico.\n\nLa optimizacion de imagenes es esencial para paginas ecommerce con muchos productos. Implementa formato WebP con fallback JPEG para todas las imagenes. Usa carga lazy para imagenes debajo del pliegue. Magento 2.4 y posteriores incluye soporte nativo de carga lazy.\n\nConsidera usar una Red de Entrega de Contenido para activos estaticos. Sirve imagenes, CSS y JavaScript desde servidores CDN edge ubicados geograficamente cerca de tus clientes.", tip: "Prueba la velocidad de pagina en paginas de producto, paginas de categoria y la pagina principal por separado. Las paginas de categoria Magento con grandes grillas de productos a menudo tienen diferentes cuellos de botella que las paginas de detalle de producto." },
        { title: "Datos estructurados y resultados enriquecidos", content: "Magento no implementa datos estructurados completos de fabrica, lo que significa que pierdes oportunidades de resultados enriquecidos en la busqueda de Google. Agregar marcado schema de Product, BreadcrumbList, Organization y Review puede mejorar significativamente tus tasas de clics.\n\nEl schema de Producto es el mas impactante para ecommerce. Cada pagina de producto debe incluir marcado JSON-LD con nombre, descripcion, imagen, SKU, marca, ofertas y calificacion agregada si tienes resenas. Extensiones de Magento como Amasty SEO Suite o Mageplaza SEO manejan esto automaticamente.\n\nEl schema de Breadcrumb ayuda a Google a mostrar la jerarquia de tu sitio en los resultados de busqueda. Implementa BreadcrumbList JSON-LD en cada pagina.\n\nPara tiendas con ubicaciones fisicas, agrega schema LocalBusiness a tus paginas de localizador de tiendas. Incluye direccion, telefono, horarios de apertura y coordenadas geograficas.\n\nEl marcado de resenas merece manejo cuidadoso. Solo implementa schema AggregateRating si tienes resenas genuinas de clientes. Google penaliza sitios que muestran estrellas de resenas en paginas sin resenas reales. Valida todos los datos estructurados con la prueba de resultados enriquecidos de Google.", items: ["Agrega schema de Producto con nombre, precio, disponibilidad, SKU y resenas a todas las paginas de producto", "Implementa schema BreadcrumbList que coincida con tu navegacion de migas de pan visible", "Agrega schema LocalBusiness a paginas de localizador para ubicaciones fisicas de retail", "Valida todos los datos estructurados con la prueba de resultados enriquecidos de Google"] },
        { title: "Sitemaps XML y gestion de rastreo", content: "Magento genera sitemaps XML automaticamente, pero la configuracion predeterminada a menudo incluye paginas que no deberian estar en el sitemap. Un sitemap mal configurado envia a Google a paginas de bajo valor o duplicadas.\n\nConfigura tus ajustes de sitemap en Tiendas, Configuracion, Catalogo, Sitemap XML. Deshabilita la inclusion de productos agotados a menos que planees reabastecerlos. Excluye paginas CMS no destinadas a busqueda organica como terminos y condiciones y politica de privacidad.\n\nPara catalogos grandes de Magento con mas de 50,000 URLs, Magento divide automaticamente el sitemap en multiples archivos con un indice de sitemap. Verifica que esto funcione correctamente.\n\nComplementa los sitemaps autogenerados de Magento con una revision manual del contenido. Rastrea tu sitio con Screaming Frog y compara las URLs descubiertas con el sitemap.\n\nEnvia tus sitemaps a traves de Google Search Console y monitorea la proporcion de indexacion.", items: ["Excluye productos agotados y paginas CMS no-SEO del sitemap XML de Magento", "Verifica que la division automatica del sitemap funcione para catalogos que excedan 50,000 URLs", "Compara las URLs rastreadas con el contenido del sitemap para encontrar brechas y errores", "Monitorea la proporcion de indexacion en Search Console para identificar discrepancias"], tip: "Configura una comparacion mensual automatizada entre las URLs de tu sitemap y el reporte de paginas indexadas de Google Search Console. Cualquier brecha creciente senala un problema de rastreo o indexacion." },
        { title: "Errores SEO comunes de Magento a evitar", content: "El error SEO de Magento mas danino es ignorar el contenido duplicado causado por productos configurables. Cuando un producto configurable como una camiseta tiene variaciones de tamano y color, Magento puede crear URLs individuales de productos simples para cada variacion. Configura los productos simples asociados con configurables como No visible individualmente en los ajustes de visibilidad del producto.\n\nOtro error comun es dejar las plantillas predeterminadas de meta titulo y descripcion de Magento sin cambios. El formato predeterminado Nombre del producto - Nombre de la tienda produce titulos sin palabras clave. Personaliza el formato del titulo para incluir contexto de categoria y palabras clave relevantes.\n\nLa busqueda integrada de Magento crea paginas de resultados de busqueda indexables por defecto. Cada consulta de busqueda genera una URL como /catalogsearch/result/?q=consulta. Bloquea /catalogsearch/ en robots.txt y agrega etiquetas noindex.\n\nNo manejar correctamente los productos agotados es otro problema frecuente. Mantén las paginas de productos agotados activas con un mensaje claro y sugiere alternativas en lugar de devolver errores 404.\n\nFinalmente, muchas tiendas Magento descuidan la optimizacion movil. Aunque los temas de Magento 2 son responsivos por defecto, las personalizaciones pesadas a menudo rompen los disenos moviles. Como Google usa indexacion mobile-first, tu experiencia movil determina directamente tus rankings.", items: ["Configura productos simples de configurables como No visible individualmente para prevenir duplicacion", "Personaliza las plantillas predeterminadas de meta titulo para incluir contexto de categoria y palabras clave", "Bloquea y pon noindex a las paginas de resultados de busqueda interna en /catalogsearch/", "Mantén las paginas de productos agotados activas con alternativas en lugar de devolver errores 404", "Prueba la experiencia movil en dispositivos reales ya que Google usa indexacion mobile-first"] },
      ],
      navLabels: {
        previous: "Anterior",
        next: "Siguiente",
      },
    },
    it: {
      badge: "SEO per piattaforma",
      heading: "Guida SEO per Magento",
      intro:
        "Magento (ora Adobe Commerce) offre una flessibilita senza pari per il SEO e-commerce, ma questa flessibilita comporta complessita. A differenza delle piattaforme ospitate che gestiscono automaticamente molte basi SEO, Magento richiede una configurazione deliberata per evitare contenuti duplicati, gestire il budget di crawl e ottimizzare la velocita delle pagine. Padroneggiare le impostazioni SEO di Magento e le insidie comuni vi permette di sfruttare la potenza della piattaforma per costruire un negozio e-commerce altamente ottimizzato e su larga scala.",
      readTime: "13 min di lettura",
      sections: [
        { title: "Struttura URL e rewrite di Magento", content: "La struttura URL predefinita di Magento genera URL puliti e SEO-friendly per prodotti e categorie, ma la piattaforma ha diverse insidie relative alle URL che creano contenuto duplicato se non configurate. L'impostazione piu critica si trova in Stores, Configurazione, Catalogo, Ottimizzazione motori di ricerca. Qui dovete abilitare le riscritture URL e impostare il tag meta del link canonico su si per categorie e prodotti.\n\nPer impostazione predefinita, Magento puo generare URL multipli per lo stesso prodotto. Un prodotto puo essere accessibile a /nome-prodotto.html, /categoria/nome-prodotto.html e /altra-categoria/nome-prodotto.html se appartiene a piu categorie. Senza tag canonici, Google vede tre pagine separate con contenuto identico.\n\nI suffissi URL sono un'altra considerazione. Magento permette di aggiungere .html o qualsiasi altro suffisso alle URL di prodotti e categorie. Mentre il suffisso stesso non influisce sul SEO, cambiarlo dopo l'indicizzazione del sito rompera tutti gli URL esistenti.\n\nPer cataloghi grandi con centinaia di categorie, pianificate la vostra gerarchia URL con cura. Magento puo creare URL profondamente nidificati. Configurate la struttura URL delle categorie per bilanciare descrittivita e brevita. Molti negozi Magento di successo usano una struttura piatta come /camicia-oxford-blu.html per i prodotti.", items: ["Abilitate i tag meta di link canonico per prodotti e categorie nella configurazione Magento", "Risolvete la duplicazione URL multi-categoria scegliendo un unico pattern URL canonico per i prodotti", "Mantenete i suffissi URL coerenti dopo il lancio per evitare redirect di massa", "Considerate strutture URL piatte per cataloghi grandi per migliorare la crawlabilita"], tip: "Dopo aver configurato le impostazioni URL, usate Screaming Frog per crawlare il vostro sito Magento e verificare pagine duplicate. Filtrate per stato del tag canonico per trovare pagine dove il canonico punta a un URL diverso." },
        { title: "Gestire la navigazione a livelli e le URL facettate", content: "La navigazione a livelli e il termine di Magento per il filtraggio a faccette, che permette ai clienti di restringere i prodotti per attributi come taglia, colore, prezzo e marca. Sebbene essenziale per l'esperienza utente, la navigazione a livelli crea un enorme problema di budget di crawl. Ogni combinazione di filtri genera un URL unico, e un catalogo con dieci attributi di dieci valori ciascuno puo produrre milioni di combinazioni.\n\nIl comportamento predefinito di Magento aggiunge parametri di filtro all'URL, creando percorsi come /scarpe.html?colore=rosso&taglia=42&marca=nike. Google tentera di crawlare tutte queste combinazioni, consumando budget di crawl su pagine senza valore unico.\n\nL'approccio piu efficace e usare un filtraggio basato su AJAX che non cambia affatto l'URL. Diverse estensioni Magento implementano questo pattern. Se non potete implementare il filtraggio AJAX, aggiungete tag meta robots noindex a tutte le pagine filtrate e bloccate i parametri di filtro in robots.txt.\n\nTuttavia, alcune combinazioni di filtri hanno valore SEO. Per questi casi specifici, create pagine di destinazione dedicate con contenuto unico.\n\nMonitorate il vostro report di copertura Google Search Console per segni di problemi con URL facettate.", items: ["Implementate il filtraggio basato su AJAX per prevenire la generazione di URL facettate", "Aggiungete tag noindex e blocchi robots.txt per le URL con parametri di filtro che non potete eliminare", "Create pagine di destinazione dedicate per combinazioni di filtri ad alto valore con contenuto unico", "Monitorate la copertura Search Console per segni di spreco di budget di crawl"] },
        { title: "Ottimizzazione della velocita delle pagine Magento", content: "I siti Magento storicamente lottano con la velocita delle pagine, e tempi di caricamento lenti impattano direttamente sia i posizionamenti che i tassi di conversione. Un'installazione Magento tipica non ottimizzata carica le pagine prodotto in quattro-otto secondi. L'ottimizzazione sistematica puo portare questo sotto i due secondi.\n\nAbilitate la cache a pagina intera integrata di Magento. Per Magento 2, Varnish e il livello di cache raccomandato. Configurate Varnish come reverse proxy davanti al vostro server Magento.\n\nOttimizzate la consegna di JavaScript e CSS. Magento carica numerosi file JavaScript e fogli di stile CSS per impostazione predefinita. Abilitate la fusione e minificazione JS e CSS nelle impostazioni Sviluppatore. Considerate l'implementazione dell'estrazione CSS critico.\n\nL'ottimizzazione delle immagini e essenziale per pagine e-commerce ricche di prodotti. Implementate il formato WebP con fallback JPEG per tutte le immagini. Usate il lazy loading per le immagini sotto il fold. Magento 2.4 e versioni successive include il supporto nativo per il lazy loading.\n\nConsiderate l'uso di un Content Delivery Network per gli asset statici. Servite immagini, CSS e JavaScript da server CDN edge geograficamente vicini ai vostri clienti.", tip: "Testate la velocita delle pagine su pagine prodotto, pagine categoria e homepage separatamente. Le pagine categoria Magento con grandi griglie di prodotti hanno spesso colli di bottiglia diversi dalle pagine di dettaglio prodotto." },
        { title: "Dati strutturati e risultati arricchiti", content: "Magento non implementa dati strutturati completi nativamente, il che significa che perdete opportunita per risultati arricchiti nella ricerca Google. Aggiungere markup schema Product, BreadcrumbList, Organization e Review puo migliorare significativamente i vostri tassi di clic.\n\nLo schema Prodotto e il piu impattante per l'e-commerce. Ogni pagina prodotto dovrebbe includere markup JSON-LD con nome, descrizione, immagine, SKU, marca, offerte e valutazione aggregata se avete recensioni. Estensioni Magento come Amasty SEO Suite o Mageplaza SEO gestiscono questo automaticamente.\n\nLo schema Breadcrumb aiuta Google a mostrare la gerarchia del vostro sito nei risultati di ricerca. Implementate BreadcrumbList JSON-LD su ogni pagina.\n\nPer i negozi con sedi fisiche, aggiungete schema LocalBusiness alle pagine del localizzatore di negozi. Includete indirizzo, telefono, orari di apertura e coordinate geografiche.\n\nIl markup delle recensioni merita un trattamento attento. Implementate lo schema AggregateRating solo se avete recensioni genuine dei clienti. Google penalizza i siti che mostrano stelle di recensione per pagine senza recensioni reali. Validate tutti i dati strutturati con il test dei risultati arricchiti di Google.", items: ["Aggiungete schema Prodotto con nome, prezzo, disponibilita, SKU e recensioni a tutte le pagine prodotto", "Implementate schema BreadcrumbList corrispondente alla vostra navigazione breadcrumb visibile", "Aggiungete schema LocalBusiness alle pagine del localizzatore per sedi fisiche di vendita", "Validate tutti i dati strutturati con il test dei risultati arricchiti di Google"] },
        { title: "Sitemap XML e gestione del crawl", content: "Magento genera sitemap XML automaticamente, ma la configurazione predefinita include spesso pagine che non dovrebbero esserci. Una sitemap mal configurata invia Google a pagine di basso valore o duplicate.\n\nConfigurate le impostazioni della sitemap in Stores, Configurazione, Catalogo, Sitemap XML. Disabilitate l'inclusione di prodotti esauriti a meno che non pianifichiate di rifornirli. Escludete le pagine CMS non destinate alla ricerca organica.\n\nPer cataloghi Magento grandi con piu di 50.000 URL, Magento divide automaticamente la sitemap in piu file con un indice sitemap. Verificate che funzioni correttamente.\n\nIntegrate le sitemap auto-generate di Magento con una revisione manuale del contenuto. Crawlate il vostro sito con Screaming Frog e confrontate gli URL scoperti con la sitemap.\n\nInviate le vostre sitemap tramite Google Search Console e monitorate il rapporto di indicizzazione.", items: ["Escludete prodotti esauriti e pagine CMS non-SEO dalla sitemap XML di Magento", "Verificate che la divisione automatica della sitemap funzioni per cataloghi superiori a 50.000 URL", "Confrontate gli URL crawlati con il contenuto della sitemap per trovare lacune ed errori", "Monitorate il rapporto di indicizzazione in Search Console per identificare discrepanze"], tip: "Impostate un confronto mensile automatizzato tra gli URL della vostra sitemap e il report delle pagine indicizzate di Google Search Console. Ogni divario crescente segnala un problema di crawling o indicizzazione." },
        { title: "Errori SEO comuni di Magento da evitare", content: "L'errore SEO Magento piu dannoso e ignorare il contenuto duplicato causato dai prodotti configurabili. Quando un prodotto configurabile come una maglietta ha variazioni di taglia e colore, Magento puo creare URL di prodotti semplici individuali per ogni variazione. Impostate i prodotti semplici associati ai configurabili su Non visibile individualmente nelle impostazioni di visibilita del prodotto.\n\nUn altro errore comune e lasciare invariati i template predefiniti di meta titolo e descrizione di Magento. Il formato predefinito Nome prodotto - Nome negozio produce titoli privi di parole chiave. Personalizzate il formato del titolo per includere contesto di categoria e parole chiave rilevanti.\n\nLa ricerca integrata di Magento crea pagine di risultati di ricerca indicizzabili per impostazione predefinita. Ogni query di ricerca genera un URL come /catalogsearch/result/?q=query. Bloccate /catalogsearch/ in robots.txt e aggiungete tag noindex.\n\nNon gestire correttamente i prodotti esauriti e un altro problema frequente. Mantenete le pagine dei prodotti esauriti attive con un messaggio chiaro e suggerite alternative invece di restituire errori 404.\n\nInfine, molti negozi Magento trascurano l'ottimizzazione mobile. Sebbene i temi Magento 2 siano responsive per impostazione predefinita, le personalizzazioni pesanti spesso rompono i layout mobile. Poiche Google usa l'indicizzazione mobile-first, la vostra esperienza mobile determina direttamente i vostri posizionamenti.", items: ["Impostate i prodotti semplici dei configurabili su Non visibile individualmente per prevenire duplicazione", "Personalizzate i template di meta titolo predefiniti per includere contesto di categoria e parole chiave", "Bloccate e mettete noindex le pagine dei risultati di ricerca interna su /catalogsearch/", "Mantenete le pagine dei prodotti esauriti attive con alternative invece di errori 404", "Testate l'esperienza mobile su dispositivi reali poiche Google usa l'indicizzazione mobile-first"] },
      ],
      navLabels: {
        previous: "Precedente",
        next: "Successivo",
      },
    },
    nl: {
      badge: "Platform SEO",
      heading: "Magento SEO-gids",
      intro:
        "Magento (nu Adobe Commerce) biedt ongeevenaarde flexibiliteit voor ecommerce SEO, maar die flexibiliteit brengt complexiteit met zich mee. In tegenstelling tot gehoste platformen die veel SEO-basisprincipes automatisch afhandelen, vereist Magento bewuste configuratie om dubbele content te voorkomen, crawlbudget te beheren en paginasnelheid te optimaliseren. Het beheersen van Magento's SEO-instellingen en veelvoorkomende valkuilen stelt u in staat de kracht van het platform te benutten voor een hooggeoptimaliseerde, grootschalige ecommerce-winkel.",
      readTime: "13 min leestijd",
      sections: [
        { title: "Magento URL-structuur en rewrites", content: "Magento's standaard URL-structuur genereert schone, SEO-vriendelijke URL's voor producten en categorieen, maar het platform heeft meerdere URL-gerelateerde valkuilen die dubbele content creeren als ze niet worden geconfigureerd. De meest kritische instelling staat onder Stores, Configuratie, Catalogus, Zoekmachineoptimalisatie. Hier moet u URL-rewrites inschakelen en de canonical link meta tag op ja zetten voor zowel categorieen als producten.\n\nStandaard kan Magento meerdere URL's genereren voor hetzelfde product. Een product kan toegankelijk zijn op /productnaam.html, /categorie/productnaam.html en /andere-categorie/productnaam.html als het tot meerdere categorieen behoort. Zonder canonical tags ziet Google drie afzonderlijke pagina's met identieke content.\n\nURL-suffixen zijn een andere overweging. Magento laat u .html of een ander suffix toevoegen aan product- en categorie-URL's. Hoewel het suffix zelf SEO niet beinvloedt, zal het wijzigen ervan na indexering alle bestaande URL's breken.\n\nVoor grote catalogi met honderden categorieen, plan uw URL-hierarchie zorgvuldig. Magento kan diep geneste URL's creeren. Configureer uw categorie-URL-structuur om beschrijvendheid en beknoptheid in balans te brengen. Veel succesvolle Magento-winkels gebruiken een platte structuur zoals /blauw-oxford-overhemd.html voor producten.", items: ["Schakel canonical link meta tags in voor zowel producten als categorieen in de Magento-configuratie", "Los multi-categorie URL-duplicatie op door een enkel canoniek product-URL-patroon te kiezen", "Houd URL-suffixen consistent na lancering om massa-redirects te voorkomen", "Overweeg platte product-URL-structuren voor grote catalogi om crawlbaarheid te verbeteren"], tip: "Crawl na het configureren van URL-instellingen uw Magento-site met Screaming Frog en controleer op dubbele pagina's. Filter op canonical tag-status om pagina's te vinden waar de canonical naar een andere URL wijst." },
        { title: "Gelaagde navigatie en gefacetteerde URL's beheren", content: "Gelaagde navigatie is Magento's term voor gefacetteerd filteren, waarmee klanten producten kunnen verfijnen op attributen zoals maat, kleur, prijs en merk. Hoewel essentieel voor gebruikerservaring, creert gelaagde navigatie een enorm crawlbudgetprobleem. Elke filtercombinatie genereert een unieke URL, en een catalogus met tien attributen van elk tien waarden kan miljoenen filterbare URL-combinaties produceren.\n\nHet standaard Magento-gedrag voegt filterparameters toe aan de URL, waardoor paden ontstaan zoals /schoenen.html?kleur=rood&maat=42&merk=nike. Google zal proberen al deze combinaties te crawlen, waardoor crawlbudget wordt verspild aan pagina's zonder unieke waarde.\n\nDe meest effectieve aanpak is AJAX-gebaseerd filteren dat de URL helemaal niet wijzigt. Als u AJAX-filtering niet kunt implementeren, voeg noindex meta robots tags toe aan alle gefilterde pagina's en blokkeer de filterparameters in robots.txt.\n\nSommige filtercombinaties hebben echter SEO-waarde. Maak voor deze specifieke gevallen dedicated landingspagina's met unieke content.\n\nMonitor uw Google Search Console dekkingsrapport voor tekenen van problemen met gefacetteerde URL's.", items: ["Implementeer AJAX-gebaseerd filteren om het genereren van gefacetteerde URL's te voorkomen", "Voeg noindex tags en robots.txt-blokkades toe voor filterparameter-URL's die u niet kunt elimineren", "Maak dedicated landingspagina's voor hoogwaardige filtercombinaties met unieke content", "Monitor Search Console dekking voor tekenen van crawlbudgetverspilling door gefacetteerde URL's"] },
        { title: "Magento paginasnelheid-optimalisatie", content: "Magento-sites worstelen historisch met paginasnelheid, en trage laadtijden beinvloeden zowel rankings als conversiepercentages direct. Een typische niet-geoptimaliseerde Magento-installatie laadt productpagina's in vier tot acht seconden. Systematische optimalisatie kan dit onder twee seconden brengen.\n\nSchakel Magento's ingebouwde full-page cache in. Voor Magento 2 is Varnish de aanbevolen caching-laag. Configureer Varnish als reverse proxy voor uw Magento-server.\n\nOptimaliseer JavaScript en CSS-levering. Magento laadt standaard talrijke JavaScript-bestanden en CSS-stylesheets. Schakel JS en CSS samenvoeging en minificatie in onder Ontwikkelaar-instellingen. Overweeg implementatie van critical CSS extractie.\n\nBeeldoptimalisatie is essentieel voor productrijke ecommerce-pagina's. Implementeer WebP-formaat met JPEG-fallback voor alle afbeeldingen. Gebruik lazy loading voor afbeeldingen onder de vouw. Magento 2.4 en later bevat native lazy loading-ondersteuning.\n\nOverweeg het gebruik van een Content Delivery Network voor statische assets. Lever afbeeldingen, CSS en JavaScript vanaf CDN edge-servers die geografisch dicht bij uw klanten liggen.", tip: "Test paginasnelheid op productpagina's, categoriepagina's en de homepage apart. Magento categoriepagina's met grote productrasters hebben vaak andere prestatieknelpunten dan productdetailpagina's." },
        { title: "Gestructureerde data en rijke resultaten", content: "Magento implementeert standaard geen uitgebreide gestructureerde data, wat betekent dat u kansen mist voor rijke resultaten in Google zoeken. Het toevoegen van Product, BreadcrumbList, Organization en Review schema markup kan uw klikpercentages aanzienlijk verbeteren.\n\nProduct schema is het meest impactvol voor ecommerce. Elke productpagina moet JSON-LD markup bevatten met naam, beschrijving, afbeelding, SKU, merk, aanbiedingen en gemiddelde beoordeling als u reviews heeft. Magento-extensies zoals Amasty SEO Suite of Mageplaza SEO handelen dit automatisch af.\n\nBreadcrumb schema helpt Google uw sitehierarchie weer te geven in zoekresultaten. Implementeer BreadcrumbList JSON-LD op elke pagina.\n\nVoor winkels met fysieke locaties, voeg LocalBusiness schema toe aan uw winkelvinderpagina's. Neem adres, telefoonnummer, openingstijden en geocoordinaten op.\n\nReview markup verdient zorgvuldige behandeling. Implementeer AggregateRating schema alleen als u echte klantreviews heeft. Google bestraft sites die reviewsterren tonen voor pagina's zonder daadwerkelijke reviews. Valideer alle gestructureerde data met Google's Rich Results Test.", items: ["Voeg Product schema toe met naam, prijs, beschikbaarheid, SKU en reviews aan alle productpagina's", "Implementeer BreadcrumbList schema dat overeenkomt met uw zichtbare breadcrumb-navigatie", "Voeg LocalBusiness schema toe aan winkelvinderpagina's voor fysieke retaillocaties", "Valideer alle gestructureerde data met Google's Rich Results Test voor en na implementatie"] },
        { title: "XML sitemaps en crawlbeheer", content: "Magento genereert XML sitemaps automatisch, maar de standaardconfiguratie bevat vaak pagina's die niet in de sitemap thuishoren. Een slecht geconfigureerde sitemap stuurt Google naar pagina's met lage waarde of duplicaten.\n\nConfigureer uw sitemap-instellingen onder Stores, Configuratie, Catalogus, XML Sitemap. Schakel opname van niet-voorradige producten uit tenzij u van plan bent ze te hervullen. Sluit CMS-pagina's uit die niet bedoeld zijn voor organisch zoeken.\n\nVoor grote Magento-catalogi met meer dan 50.000 URL's splitst Magento de sitemap automatisch in meerdere bestanden met een sitemap-index. Verifieer dat dit correct werkt.\n\nVul Magento's auto-gegenereerde sitemaps aan met een handmatige review van de inhoud. Crawl uw site met Screaming Frog en vergelijk de ontdekte URL's met de sitemap.\n\nDien uw sitemaps in via Google Search Console en monitor de indexatieratio.", items: ["Sluit niet-voorradige producten en niet-SEO CMS-pagina's uit van Magento's XML sitemap", "Verifieer dat automatische sitemap-splitsing werkt voor catalogi boven 50.000 URL's", "Vergelijk gecrawlde URL's met sitemap-inhoud om gaten en fouten te vinden", "Monitor de indexatieratio in Search Console om discrepanties te identificeren"], tip: "Stel een maandelijkse geautomatiseerde vergelijking in tussen uw sitemap-URL's en het rapport geindexeerde pagina's van Google Search Console. Elke groeiende kloof signaleert een crawling- of indexatieprobleem." },
        { title: "Veelvoorkomende Magento SEO-fouten vermijden", content: "De meest schadelijke Magento SEO-fout is het negeren van dubbele content veroorzaakt door configureerbare producten. Wanneer een configureerbaar product zoals een t-shirt maat- en kleurvariaties heeft, kan Magento individuele simpele product-URL's creeren voor elke variatie. Stel simpele producten gekoppeld aan configureerbare in op Niet individueel zichtbaar in de productzichtbaarheidsinstellingen.\n\nEen andere veelvoorkomende fout is het ongewijzigd laten van Magento's standaard meta titel- en beschrijvingstemplates. Het standaardformaat Productnaam - Winkelnaam produceert titels zonder zoekwoorden. Pas het titelformaat aan om categoriecontext en relevante zoekwoorden op te nemen.\n\nMagento's ingebouwde zoekmachine maakt standaard indexeerbare zoekresultatenpagina's. Elke zoekopdracht genereert een URL zoals /catalogsearch/result/?q=zoekopdracht. Blokkeer /catalogsearch/ in robots.txt en voeg noindex tags toe.\n\nHet niet correct afhandelen van niet-voorradige producten is een ander frequent probleem. Houd niet-voorradige productpagina's actief met een duidelijk bericht en stel alternatieven voor in plaats van 404-fouten te retourneren.\n\nTenslotte verwaarlozen veel Magento-winkels mobiele optimalisatie. Hoewel Magento 2-thema's standaard responsief zijn, breken zware aanpassingen vaak mobiele layouts. Aangezien Google mobile-first indexering gebruikt, bepaalt uw mobiele ervaring direct uw rankings.", items: ["Stel simpele producten van configureerbare in op Niet individueel zichtbaar om duplicatie te voorkomen", "Pas standaard meta titel-templates aan om categoriecontext en relevante zoekwoorden op te nemen", "Blokkeer en zet noindex op de interne zoekresultatenpagina's op /catalogsearch/", "Houd niet-voorradige productpagina's actief met alternatieven in plaats van 404-fouten", "Test mobiele ervaring op echte apparaten aangezien Google mobile-first indexering gebruikt"] },
      ],
      navLabels: {
        previous: "Vorige",
        next: "Volgende",
      },
    },
  },
};
