import type { AcademyTopic } from "../../types";

export const productPageSeo: AcademyTopic = {
  slug: "product-page-seo",
  cluster: 3,
  resources: [{"label":"Google Product Structured Data","url":"https://developers.google.com/search/docs/appearance/structured-data/product","type":"docs"},{"label":"Rich Results Test","url":"https://search.google.com/test/rich-results","type":"tool"},{"label":"Google PageSpeed Insights","url":"https://pagespeed.web.dev/","type":"tool"},{"label":"Schema.org Product Type","url":"https://schema.org/Product","type":"docs"}],
  content: {
    en: {
      badge: "On-Page SEO",
      heading: "Product Page SEO",
      intro:
        "Your product pages are where transactions happen, yet most ecommerce stores treat them as afterthoughts, copying manufacturer descriptions, uploading unoptimized images, and slapping on generic title tags. A well-optimized product page does three things simultaneously: it ranks for specific product queries, it convinces the shopper to buy, and it sends structured data to search engines so your listings stand out in results. We see product page optimization as one of the highest-ROI activities in ecommerce SEO because the traffic these pages attract already carries strong purchase intent.",
      readTime: "10 min read",
      sections: [
        {
          title: "Anatomy of a Well-Optimized Product Page",
          content:
            "Every high-performing product page shares a set of structural elements that satisfy both search engines and shoppers. At the top, a clear H1 that matches the product name and primary keyword. Below that, product images with descriptive alt text. Then a unique description that goes beyond specs to address buyer questions and use cases. Supporting elements include breadcrumb navigation, customer reviews, related product links, and structured data markup.\n\nThe order and visual hierarchy of these elements matters. Eye-tracking studies consistently show that shoppers scan in an F-pattern: they look at the product image first, then the title, then the price, and finally the description. Your SEO elements should align with this natural scanning behavior rather than fighting against it. A title tag stuffed with keywords that doesn't match the visible H1 confuses both users and search engines.\n\nWe audit product pages using a 12-point checklist that covers technical SEO, content quality, and conversion elements. The stores that score highest on this checklist tend to have 30-50% more organic traffic per product page compared to competitors in the same niche. The difference isn't any single element, it's the compound effect of getting every element right on thousands of product pages.",
          items: [
            "H1 heading matching the product name and primary keyword",
            "Unique product description with buyer-focused language (not copied from manufacturer)",
            "Optimized images with descriptive alt text and compressed file sizes",
            "Breadcrumb navigation showing the category hierarchy",
            "Product schema markup for rich results in search",
            "Customer reviews displayed on the page with review schema",
          ],
        },
        {
          title: "Title Tags with Product Attributes",
          content:
            "Product page title tags need to balance keyword inclusion with click appeal. The most effective formula we've found for product pages is: Product Name + Key Attribute + Brand + Store Name. For example, \"Merino Wool Hiking Socks - Lightweight, Size 9-12 | TrailGear\" packs the product keyword, a differentiating attribute, size information, and the store name into a single tag.\n\nIncluding product attributes like color, size, material, or model number in title tags captures long-tail searches that your competitors miss. Someone searching \"blue ceramic 12oz coffee mug\" has extremely specific purchase intent, and a title tag that matches those attributes will earn the click over a generic \"Coffee Mug\" listing every time.\n\nFor stores with large catalogs, manually writing title tags for every product isn't realistic. Instead, build a template system that pulls product attributes dynamically. Most ecommerce platforms support this through template variables: {Product Name} - {Color} {Material} | {Brand} | {Store Name}. The key is choosing which attributes matter most for each category. Clothing products benefit from material and size in the title. Electronics need model numbers. Furniture benefits from dimensions.\n\nKeep title tags under 60 characters when possible. Google truncates longer titles in search results, and a cut-off title looks unprofessional and loses information. If your product name alone exceeds 40 characters, you'll need to prioritize which attributes to include and which to save for the meta description.",
          tip: "Test different title tag formulas across product categories by running A/B experiments in Google Search Console. Change the title tags for 50 products in one category, wait 4-6 weeks, and compare CTR changes against a control group of unchanged products in the same category.",
        },
        {
          title: "Writing Unique Product Descriptions",
          content:
            "Manufacturer descriptions are one of the biggest SEO liabilities in ecommerce. When 200 stores use the same text for the same product, Google has no reason to rank your page over any of the others. Duplicate content doesn't trigger a penalty, but it eliminates your ability to differentiate in search results. Writing unique descriptions is non-negotiable for competitive product rankings.\n\nA strong product description answers three questions the shopper is asking: What is this product? Why should I buy it from you? How does it solve my specific problem? Start with a short paragraph that covers the product's primary benefit, not a feature list, but the outcome the buyer gets. Then expand with details about materials, sizing, compatibility, or use cases. Close with any differentiators like warranty, free returns, or bundled accessories.\n\nLength depends on the product's complexity and price point. A $15 phone case might need 100-150 words. A $2,000 espresso machine deserves 400-600 words covering every aspect a buyer would research before purchasing. Match your description depth to the consideration level of the purchase, the more expensive or complex the product, the more content the page needs to rank and convert.\n\nIncorporate relevant keywords naturally throughout the description, but write for the human reader first. Phrases like \"this stainless steel water bottle keeps drinks cold for 24 hours\" naturally include the keywords a searcher would use while also communicating a concrete benefit. Forced keyword insertion like \"buy best stainless steel water bottle online\" reads poorly and doesn't improve rankings.",
          items: [
            "Rewrite manufacturer copy in your brand's voice with unique angles",
            "Lead with the primary benefit rather than a feature specification list",
            "Match description depth to product price and complexity, higher price means longer content",
            "Include natural keyword variations throughout the text without forcing them",
          ],
        },
        {
          title: "Product Schema Markup",
          content:
            "Product schema (structured data) tells Google exactly what your page is about and enables rich results, those enhanced listings with star ratings, prices, and availability badges that dominate ecommerce search results. Pages with rich results consistently earn higher click-through rates than plain blue links, and we've measured 15-35% CTR improvements after implementing product schema across client stores.\n\nThe essential Product schema properties to include are: name, description, image, brand, sku, offers (with price, currency, and availability), and aggregateRating (if you have reviews). Each property must accurately reflect what's visible on the page, Google will penalize misleading structured data. If your product shows $49.99 on the page, the schema price must match exactly.\n\nImplement schema using JSON-LD format, which Google recommends over microdata or RDFa. Place the JSON-LD script in the page's head or body. Most modern ecommerce platforms either include product schema by default or offer apps that generate it automatically. However, we always recommend auditing auto-generated schema because plugins frequently miss properties or output incorrect values.\n\nValidate your schema using Google's Rich Results Test tool after implementation. Common errors include missing required fields, incorrect data types (price as string vs. number), and review markup on pages without visible reviews. Fix validation errors promptly, invalid schema won't generate rich results and could trigger a manual action if Google considers it spammy.",
          tip: "Add the 'review' property within your Product schema only when actual customer reviews are displayed on the page. Google has cracked down on review markup that doesn't correspond to visible review content, and violations can result in losing all rich results across your entire domain.",
        },
        {
          title: "Image Alt Text and File Naming",
          content:
            "Product images represent a significant SEO opportunity that most stores waste. Google Images drives a meaningful share of ecommerce traffic, we've seen it account for 10-25% of organic visits for visually-driven product categories like furniture, fashion, and home decor. Optimizing image alt text and file names is the entry point for capturing this traffic.\n\nFile names should describe the product before the image is ever uploaded. Rename \"IMG_4582.jpg\" to \"red-leather-crossbody-bag-front.jpg\" before it goes on your site. Search engines use file names as a ranking signal for image search, and descriptive names also help screen readers provide context for visually impaired shoppers. Use hyphens to separate words, keep names concise, and include the primary product keyword.\n\nAlt text serves a dual purpose: accessibility and SEO. Write alt text that describes what the image shows as if you were explaining it to someone who can't see it. \"Red leather crossbody bag with gold chain strap, front view\" tells both screen readers and search engines exactly what's in the image. Avoid keyword-stuffing alt text, \"buy red leather bag best red leather crossbody bag sale\" is spammy and unhelpful.\n\nFor product pages with multiple images (front, back, detail, lifestyle), vary the alt text to describe each specific view. This creates multiple opportunities to rank in image search for different queries. The lifestyle shot of someone carrying the bag at a cafe might rank for \"crossbody bag outfit\" while the detail shot ranks for \"gold chain bag strap.\"",
        },
        {
          title: "UX Signals That Affect Product Page Rankings",
          content:
            "Google measures how users interact with your product pages after clicking from search results. High bounce rates, short time-on-page, and pogo-sticking (clicking back to search results and choosing a different listing) all signal that your page didn't satisfy the searcher's intent. These behavioral signals influence rankings over time, which means UX and SEO are deeply connected on product pages.\n\nPage speed is the most measurable UX factor. Product pages loaded with uncompressed images, excessive JavaScript, and third-party tracking scripts often take 4-6 seconds to load on mobile. Google's Core Web Vitals, Largest Contentful Paint, Interaction to Next Paint, and Cumulative Layout Shift, directly measure loading performance, interactivity, and visual stability. We target under 2.5 seconds for LCP, under 200ms for INP, and under 0.1 for CLS on all product pages.\n\nMobile usability is equally critical. Over 60% of ecommerce traffic comes from mobile devices, and a product page that's difficult to navigate on a phone will lose both rankings and sales. Tap targets need to be large enough for thumbs, product images should be zoomable, and the add-to-cart button must be visible without excessive scrolling. Test every product page template on actual mobile devices, not just browser resize tools.\n\nTrust elements reduce bounce rates and increase dwell time. Visible shipping costs, return policies, security badges, and customer reviews all give shoppers reasons to stay on the page rather than bouncing back to search results. A product page that immediately answers \"how much is shipping\" and \"can I return this\" keeps users engaged, which sends positive signals to Google about your page's quality and relevance.",
          items: [
            "Target LCP under 2.5 seconds, INP under 200ms, and CLS under 0.1 for all product pages",
            "Ensure mobile usability with zoomable images, large tap targets, and visible CTAs",
            "Display shipping costs, return policies, and trust badges above the fold",
            "Include customer reviews to increase dwell time and reduce bounce rates",
          ],
        },
      ],
      navLabels: {
        previous: "Seasonal Keyword Trends",
        next: "Category Page SEO",
      },
    },
    de: {
      badge: "On-Page SEO",
      heading: "Produktseiten-SEO",
      intro:
        "Ihre Produktseiten sind der Ort, an dem Transaktionen stattfinden, dennoch behandeln die meisten E-Commerce-Shops sie als Nebensache, sie kopieren Herstellerbeschreibungen, laden unoptimierte Bilder hoch und verwenden generische Title-Tags. Eine gut optimierte Produktseite erfüllt drei Aufgaben gleichzeitig: Sie rankt für spezifische Produktanfragen, sie überzeugt den Käufer zum Kauf, und sie sendet strukturierte Daten an Suchmaschinen, damit Ihre Listings in den Ergebnissen hervorstechen. Wir sehen die Produktseiten-Optimierung als eine der Aktivitäten mit dem höchsten ROI im E-Commerce-SEO, da der Traffic, den diese Seiten anziehen, bereits starke Kaufabsicht mitbringt.",
      readTime: "10 Min. Lesezeit",
      sections: [
        {
          title: "Anatomie einer gut optimierten Produktseite",
          content:
            "Jede leistungsstarke Produktseite teilt eine Reihe struktureller Elemente, die sowohl Suchmaschinen als auch Käufer zufriedenstellen. Oben eine klare H1-Überschrift, die zum Produktnamen und primären Keyword passt. Darunter Produktbilder mit beschreibendem Alt-Text. Dann eine einzigartige Beschreibung, die über Spezifikationen hinausgeht und Käuferfragen sowie Anwendungsfälle behandelt. Unterstützende Elemente umfassen Breadcrumb-Navigation, Kundenbewertungen, Links zu verwandten Produkten und strukturierte Daten.\n\nDie Reihenfolge und visuelle Hierarchie dieser Elemente ist entscheidend. Eye-Tracking-Studien zeigen konsistent, dass Käufer in einem F-Muster scannen: Sie schauen zuerst auf das Produktbild, dann den Titel, dann den Preis und schließlich die Beschreibung. Ihre SEO-Elemente sollten mit diesem natürlichen Scanverhalten übereinstimmen, anstatt dagegen zu arbeiten. Ein mit Keywords vollgestopfter Title-Tag, der nicht zur sichtbaren H1 passt, verwirrt sowohl Nutzer als auch Suchmaschinen.\n\nWir prüfen Produktseiten anhand einer 12-Punkte-Checkliste, die technisches SEO, Content-Qualität und Conversion-Elemente abdeckt. Die Shops, die bei dieser Checkliste am besten abschneiden, haben tendenziell 30-50% mehr organischen Traffic pro Produktseite im Vergleich zu Wettbewerbern in der gleichen Nische. Der Unterschied liegt nicht in einem einzelnen Element, es ist der kumulative Effekt, jedes Element auf Tausenden von Produktseiten richtig umzusetzen.",
          items: [
            "H1-Überschrift passend zum Produktnamen und primären Keyword",
            "Einzigartige Produktbeschreibung mit käuferorientierter Sprache (nicht vom Hersteller kopiert)",
            "Optimierte Bilder mit beschreibendem Alt-Text und komprimierten Dateigrößen",
            "Breadcrumb-Navigation zur Darstellung der Kategorie-Hierarchie",
            "Produkt-Schema-Markup für Rich Results in der Suche",
            "Kundenbewertungen auf der Seite mit Review-Schema angezeigt",
          ],
        },
        {
          title: "Title-Tags mit Produktattributen",
          content:
            "Title-Tags für Produktseiten müssen Keyword-Einbindung mit Klick-Attraktivität in Einklang bringen. Die effektivste Formel, die wir für Produktseiten gefunden haben, ist: Produktname + Schlüsselattribut + Marke + Shopname. Zum Beispiel packt „Merino-Woll-Wandersocken - Leicht, Größe 42-45 | TrailGear“ das Produkt-Keyword, ein differenzierendes Attribut, Größeninformation und den Shopnamen in einen einzigen Tag.\n\nDie Aufnahme von Produktattributen wie Farbe, Größe, Material oder Modellnummer in Title-Tags erfasst Long-Tail-Suchanfragen, die Ihre Wettbewerber übersehen. Jemand, der nach „blaue Keramik 350ml Kaffeetasse“ sucht, hat extrem spezifische Kaufabsicht, und ein Title-Tag, der diese Attribute abbildet, wird den Klick gegenüber einem generischen „Kaffeetasse“-Listing jedes Mal gewinnen.\n\nFür Shops mit großen Katalogen ist das manuelle Schreiben von Title-Tags für jedes Produkt nicht realistisch. Bauen Sie stattdessen ein Template-System, das Produktattribute dynamisch einzieht. Die meisten E-Commerce-Plattformen unterstützen dies über Template-Variablen: {Produktname} - {Farbe} {Material} | {Marke} | {Shopname}. Der Schlüssel liegt in der Auswahl, welche Attribute für jede Kategorie am wichtigsten sind. Bekleidungsprodukte profitieren von Material und Größe im Titel. Elektronik braucht Modellnummern. Möbel profitieren von Abmessungen.\n\nHalten Sie Title-Tags wenn möglich unter 60 Zeichen. Google kürzt längere Titel in Suchergebnissen, und ein abgeschnittener Titel wirkt unprofessionell und verliert Information. Wenn Ihr Produktname allein 40 Zeichen überschreitet, müssen Sie priorisieren, welche Attribute aufgenommen und welche für die Meta-Description gespart werden.",
          tip: "Testen Sie verschiedene Title-Tag-Formeln über Produktkategorien hinweg, indem Sie A/B-Experimente in der Google Search Console durchführen. Ändern Sie die Title-Tags für 50 Produkte in einer Kategorie, warten Sie 4-6 Wochen und vergleichen Sie CTR-Änderungen mit einer Kontrollgruppe unveränderter Produkte in derselben Kategorie.",
        },
        {
          title: "Einzigartige Produktbeschreibungen schreiben",
          content:
            "Herstellerbeschreibungen sind eine der größten SEO-Schwachstellen im E-Commerce. Wenn 200 Shops denselben Text für dasselbe Produkt verwenden, hat Google keinen Grund, Ihre Seite vor einer anderen zu ranken. Duplicate Content löst keine Abstrafung aus, aber er eliminiert Ihre Fähigkeit, sich in Suchergebnissen zu differenzieren. Das Schreiben einzigartiger Beschreibungen ist unverzichtbar für wettbewerbsfähige Produkt-Rankings.\n\nEine starke Produktbeschreibung beantwortet drei Fragen, die der Käufer stellt: Was ist dieses Produkt? Warum sollte ich es bei Ihnen kaufen? Wie löst es mein spezifisches Problem? Beginnen Sie mit einem kurzen Absatz, der den Hauptvorteil des Produkts behandelt, keine Feature-Liste, sondern das Ergebnis, das der Käufer erhält. Erweitern Sie dann mit Details zu Materialien, Größen, Kompatibilität oder Anwendungsfällen. Schließen Sie mit Differenzierungsmerkmalen wie Garantie, kostenlosem Rückversand oder gebündeltem Zubehör.\n\nDie Länge hängt von der Komplexität und dem Preisniveau des Produkts ab. Eine 15€-Handyhülle braucht vielleicht 100-150 Wörter. Eine 2.000€-Espressomaschine verdient 400-600 Wörter, die jeden Aspekt abdecken, den ein Käufer vor dem Kauf recherchieren würde. Passen Sie die Beschreibungstiefe an das Überlegungsniveau des Kaufs an, je teurer oder komplexer das Produkt, desto mehr Content braucht die Seite zum Ranken und Konvertieren.\n\nIntegrieren Sie relevante Keywords natürlich in die gesamte Beschreibung, aber schreiben Sie zuerst für den menschlichen Leser. Formulierungen wie „diese Edelstahl-Trinkflasche hält Getränke 24 Stunden kalt“ enthalten natürlich die Keywords, die ein Suchender verwenden würde, und kommunizieren gleichzeitig einen konkreten Nutzen. Erzwungene Keyword-Einbindung wie „beste Edelstahl-Trinkflasche online kaufen“ liest sich schlecht und verbessert keine Rankings.",
          items: [
            "Herstellertexte in der eigenen Markenstimme mit einzigartigen Blickwinkeln umschreiben",
            "Mit dem Hauptvorteil beginnen statt mit einer Feature-Spezifikationsliste",
            "Beschreibungstiefe an Produktpreis und Komplexität anpassen, höherer Preis bedeutet längeren Content",
            "Natürliche Keyword-Variationen im gesamten Text einbauen ohne sie zu erzwingen",
          ],
        },
        {
          title: "Produkt-Schema-Markup",
          content:
            "Produkt-Schema (strukturierte Daten) teilt Google genau mit, worum es auf Ihrer Seite geht, und ermöglicht Rich Results, jene erweiterten Listings mit Sternebewertungen, Preisen und Verfügbarkeitsanzeigen, die die E-Commerce-Suchergebnisse dominieren. Seiten mit Rich Results erzielen konsistent höhere Klickraten als einfache blaue Links, und wir haben 15-35% CTR-Verbesserungen gemessen, nachdem wir Produkt-Schema auf Client-Shops implementiert haben.\n\nDie wesentlichen Produkt-Schema-Eigenschaften sind: name, description, image, brand, sku, offers (mit Preis, Währung und Verfügbarkeit) und aggregateRating (wenn Sie Bewertungen haben). Jede Eigenschaft muss genau widerspiegeln, was auf der Seite sichtbar ist, Google bestraft irreführende strukturierte Daten. Wenn Ihr Produkt auf der Seite 49,99€ anzeigt, muss der Schema-Preis exakt übereinstimmen.\n\nImplementieren Sie Schema im JSON-LD-Format, das Google gegenüber Microdata oder RDFa empfiehlt. Platzieren Sie das JSON-LD-Script im Head oder Body der Seite. Die meisten modernen E-Commerce-Plattformen enthalten Produkt-Schema standardmäßig oder bieten Apps an, die es automatisch generieren. Wir empfehlen jedoch immer, automatisch generiertes Schema zu prüfen, da Plugins häufig Eigenschaften auslassen oder falsche Werte ausgeben.\n\nValidieren Sie Ihr Schema nach der Implementierung mit Googles Rich Results Test-Tool. Häufige Fehler sind fehlende Pflichtfelder, falsche Datentypen (Preis als String statt Zahl) und Review-Markup auf Seiten ohne sichtbare Bewertungen. Beheben Sie Validierungsfehler zeitnah, ungültiges Schema erzeugt keine Rich Results und könnte eine manuelle Maßnahme auslösen, wenn Google es als spammy betrachtet.",
          tip: "Fügen Sie die 'review'-Eigenschaft innerhalb Ihres Produkt-Schemas nur hinzu, wenn tatsächliche Kundenbewertungen auf der Seite angezeigt werden. Google hat das Vorgehen gegen Review-Markup verschärft, das keinem sichtbaren Review-Content entspricht, und Verstöße können zum Verlust aller Rich Results über Ihre gesamte Domain führen.",
        },
        {
          title: "Bild-Alt-Text und Dateibenennung",
          content:
            "Produktbilder stellen eine erhebliche SEO-Chance dar, die die meisten Shops verschwenden. Google Images generiert einen bedeutenden Anteil des E-Commerce-Traffics, wir haben gesehen, dass es 10-25% der organischen Besuche für visuell geprägte Produktkategorien wie Möbel, Mode und Wohnaccessoires ausmacht. Die Optimierung von Bild-Alt-Text und Dateinamen ist der Einstiegspunkt zur Erfassung dieses Traffics.\n\nDateinamen sollten das Produkt beschreiben, bevor das Bild jemals hochgeladen wird. Benennen Sie „IMG_4582.jpg“ in „rote-leder-umhaengetasche-vorderansicht.jpg“ um, bevor es auf Ihre Seite kommt. Suchmaschinen verwenden Dateinamen als Ranking-Signal für die Bildersuche, und beschreibende Namen helfen auch Screenreadern, Kontext für sehbehinderte Käufer zu liefern. Verwenden Sie Bindestriche zur Worttrennung, halten Sie Namen prägnant und fügen Sie das primäre Produkt-Keyword ein.\n\nAlt-Text dient einem doppelten Zweck: Barrierefreiheit und SEO. Schreiben Sie Alt-Text, der beschreibt, was das Bild zeigt, als würden Sie es jemandem erklären, der es nicht sehen kann. „Rote Leder-Umhängetasche mit goldener Kettenriemen, Vorderansicht“ sagt sowohl Screenreadern als auch Suchmaschinen genau, was auf dem Bild zu sehen ist. Vermeiden Sie Keyword-Stuffing im Alt-Text, „rote Ledertasche kaufen beste rote Leder-Umhängetasche Angebot“ ist spammy und unhilfreich.\n\nFür Produktseiten mit mehreren Bildern (vorne, hinten, Detail, Lifestyle) variieren Sie den Alt-Text, um jede spezifische Ansicht zu beschreiben. Dies schafft mehrere Möglichkeiten, in der Bildersuche für verschiedene Anfragen zu ranken. Das Lifestyle-Foto einer Person, die die Tasche in einem Café trägt, könnte für „Umhängetasche Outfit“ ranken, während das Detailbild für „goldene Ketten-Taschenriemen“ rankt.",
        },
        {
          title: "UX-Signale, die Produktseiten-Rankings beeinflussen",
          content:
            "Google misst, wie Nutzer nach dem Klick aus den Suchergebnissen mit Ihren Produktseiten interagieren. Hohe Absprungraten, kurze Verweildauer und Pogo-Sticking (Zurück zu den Suchergebnissen klicken und ein anderes Listing wählen) signalisieren alle, dass Ihre Seite die Suchintention nicht befriedigt hat. Diese Verhaltenssignale beeinflussen Rankings über die Zeit, was bedeutet, dass UX und SEO auf Produktseiten eng miteinander verbunden sind.\n\nSeitengeschwindigkeit ist der am besten messbare UX-Faktor. Produktseiten, die mit unkomprimierten Bildern, übermäßigem JavaScript und Third-Party-Tracking-Scripts geladen sind, brauchen auf Mobilgeräten oft 4-6 Sekunden zum Laden. Googles Core Web Vitals, Largest Contentful Paint, Interaction to Next Paint und Cumulative Layout Shift, messen direkt Ladeleistung, Interaktivität und visuelle Stabilität. Wir zielen auf unter 2,5 Sekunden für LCP, unter 200ms für INP und unter 0,1 für CLS auf allen Produktseiten ab.\n\nMobile Benutzerfreundlichkeit ist gleichermaßen entscheidend. Über 60% des E-Commerce-Traffics kommt von Mobilgeräten, und eine Produktseite, die auf einem Telefon schwer zu navigieren ist, verliert sowohl Rankings als auch Verkäufe. Tippziele müssen groß genug für Daumen sein, Produktbilder sollten zoombar sein und der Warenkorb-Button muss ohne übermäßiges Scrollen sichtbar sein. Testen Sie jede Produktseiten-Vorlage auf echten Mobilgeräten, nicht nur mit Browser-Resize-Tools.\n\nVertrauenselemente reduzieren Absprungraten und erhöhen die Verweildauer. Sichtbare Versandkosten, Rückgaberichtlinien, Sicherheitssiegel und Kundenbewertungen geben Käufern Gründe, auf der Seite zu bleiben, anstatt zu den Suchergebnissen zurückzuspringen. Eine Produktseite, die sofort „wie viel kostet der Versand“ und „kann ich dies zurückgeben“ beantwortet, hält Nutzer engagiert, was positive Signale an Google über die Qualität und Relevanz Ihrer Seite sendet.",
          items: [
            "LCP unter 2,5 Sekunden, INP unter 200ms und CLS unter 0,1 für alle Produktseiten anstreben",
            "Mobile Benutzerfreundlichkeit mit zoombaren Bildern, großen Tippzielen und sichtbaren CTAs sicherstellen",
            "Versandkosten, Rückgaberichtlinien und Vertrauenssiegel above the fold anzeigen",
            "Kundenbewertungen einbinden, um die Verweildauer zu erhöhen und Absprungraten zu senken",
          ],
        },
      ],
      navLabels: {
        previous: "Saisonale Keyword-Trends",
        next: "Kategorieseiten-SEO",
      },
    },
    fr: {
      badge: "SEO On-Page",
      heading: "SEO des pages produits",
      intro:
        "Vos pages produits sont l'endroit ou les transactions se concretisent, pourtant la plupart des boutiques en ligne les traitent comme un detail secondaire, copiant les descriptions du fabricant, telechargeant des images non optimisees et ajoutant des balises title generiques. Une page produit bien optimisee remplit trois fonctions simultanement : elle se positionne sur les requetes produits specifiques, elle convainc l'acheteur de passer a l'achat, et elle envoie des donnees structurees aux moteurs de recherche pour que vos annonces se demarquent dans les resultats. Nous considerons l'optimisation des pages produits comme l'une des activites au meilleur ROI du SEO ecommerce, car le trafic que ces pages attirent porte deja une forte intention d'achat.",
      readTime: "10 min de lecture",
      sections: [
        {
          title: "Anatomie d'une page produit bien optimisee",
          content:
            "Chaque page produit performante partage un ensemble d'elements structurels qui satisfont a la fois les moteurs de recherche et les acheteurs. En haut, un H1 clair correspondant au nom du produit et au mot-cle principal. En dessous, des images produit avec un texte alternatif descriptif. Ensuite, une description unique qui va au-dela des specifications pour repondre aux questions et cas d'usage des acheteurs. Les elements de soutien incluent la navigation par fil d'Ariane, les avis clients, les liens vers des produits associes et le balisage de donnees structurees.\n\nL'ordre et la hierarchie visuelle de ces elements comptent. Les etudes d'eye-tracking montrent systematiquement que les acheteurs scannent en forme de F : ils regardent d'abord l'image du produit, puis le titre, puis le prix, et enfin la description. Vos elements SEO doivent s'aligner sur ce comportement de balayage naturel plutot que de le contredire. Une balise title bourrée de mots-cles qui ne correspond pas au H1 visible seme la confusion chez les utilisateurs et les moteurs de recherche.\n\nNous auditons les pages produits avec une checklist en 12 points couvrant le SEO technique, la qualite du contenu et les elements de conversion. Les boutiques qui obtiennent les meilleurs scores sur cette checklist tendent a avoir 30-50% de trafic organique en plus par page produit par rapport aux concurrents dans le meme creneau. La difference ne tient pas a un seul element, c'est l'effet combine de chaque element bien execute sur des milliers de pages produits.",
          items: [
            "Balise H1 correspondant au nom du produit et au mot-cle principal",
            "Description produit unique avec un langage oriente acheteur (pas copiee du fabricant)",
            "Images optimisees avec texte alternatif descriptif et tailles de fichiers compressees",
            "Navigation par fil d'Ariane montrant la hierarchie des categories",
            "Balisage schema produit pour les resultats enrichis dans la recherche",
            "Avis clients affiches sur la page avec le schema review",
          ],
        },
        {
          title: "Balises title avec attributs produit",
          content:
            "Les balises title des pages produits doivent equilibrer l'inclusion de mots-cles et l'attrait au clic. La formule la plus efficace que nous ayons trouvee pour les pages produits est : Nom du Produit + Attribut Cle + Marque + Nom de la Boutique. Par exemple, « Chaussettes de Randonnee en Laine Merinos - Legeres, Taille 42-45 | TrailGear » regroupe le mot-cle produit, un attribut differenciant, l'information de taille et le nom de la boutique dans une seule balise.\n\nInclure des attributs produit comme la couleur, la taille, le materiau ou le numero de modele dans les balises title capture les recherches longue traine que vos concurrents ratent. Quelqu'un recherchant « tasse a cafe ceramique bleue 350ml » a une intention d'achat extremement specifique, et une balise title qui correspond a ces attributs remportera le clic face a une annonce generique « Tasse a Cafe » a chaque fois.\n\nPour les boutiques avec de grands catalogues, ecrire manuellement les balises title pour chaque produit n'est pas realiste. Construisez plutot un systeme de templates qui extrait les attributs produit dynamiquement. La plupart des plateformes ecommerce supportent cela via des variables de template : {Nom du Produit} - {Couleur} {Materiau} | {Marque} | {Nom de la Boutique}. La cle est de choisir quels attributs comptent le plus pour chaque categorie. Les produits vestimentaires beneficient du materiau et de la taille dans le titre. L'electronique a besoin des numeros de modele. Le mobilier beneficie des dimensions.\n\nGardez les balises title sous 60 caracteres quand c'est possible. Google tronque les titres plus longs dans les resultats de recherche, et un titre coupe a l'air non professionnel et perd de l'information. Si votre nom de produit seul depasse 40 caracteres, vous devrez prioriser quels attributs inclure et lesquels reserver pour la meta description.",
          tip: "Testez differentes formules de balises title sur les categories de produits en executant des experiences A/B dans Google Search Console. Modifiez les balises title de 50 produits dans une categorie, attendez 4-6 semaines, et comparez les changements de CTR avec un groupe temoin de produits inchanges dans la meme categorie.",
        },
        {
          title: "Rediger des descriptions produit uniques",
          content:
            "Les descriptions du fabricant sont l'un des plus grands handicaps SEO dans le ecommerce. Quand 200 boutiques utilisent le meme texte pour le meme produit, Google n'a aucune raison de classer votre page devant les autres. Le contenu duplique ne declenche pas de penalite, mais il elimine votre capacite a vous differencier dans les resultats de recherche. Rediger des descriptions uniques est indispensable pour des classements produits competitifs.\n\nUne description produit solide repond a trois questions que l'acheteur se pose : Qu'est-ce que ce produit ? Pourquoi devrais-je l'acheter chez vous ? Comment resout-il mon probleme specifique ? Commencez par un court paragraphe couvrant le benefice principal du produit, pas une liste de fonctionnalites, mais le resultat concret que l'acheteur obtient. Ensuite, developpez avec des details sur les materiaux, les tailles, la compatibilite ou les cas d'utilisation. Terminez avec les differencieurs comme la garantie, les retours gratuits ou les accessoires inclus.\n\nLa longueur depend de la complexite et du prix du produit. Une coque de telephone a 15€ peut necessiter 100-150 mots. Une machine a expresso a 2 000€ merite 400-600 mots couvrant chaque aspect qu'un acheteur rechercherait avant l'achat. Adaptez la profondeur de votre description au niveau de reflexion de l'achat, plus le produit est cher ou complexe, plus la page a besoin de contenu pour se classer et convertir.\n\nIntegrez des mots-cles pertinents naturellement dans toute la description, mais ecrivez d'abord pour le lecteur humain. Des phrases comme « cette gourde en acier inoxydable garde les boissons froides pendant 24 heures » incluent naturellement les mots-cles qu'un chercheur utiliserait tout en communiquant un benefice concret. L'insertion forcee de mots-cles comme « acheter meilleure gourde acier inoxydable en ligne » se lit mal et n'ameliore pas les classements.",
          items: [
            "Reecrire le texte du fabricant dans la voix de votre marque avec des angles uniques",
            "Commencer par le benefice principal plutot qu'une liste de specifications techniques",
            "Adapter la profondeur de la description au prix et a la complexite du produit, prix plus eleve signifie contenu plus long",
            "Inclure des variations naturelles de mots-cles dans tout le texte sans les forcer",
          ],
        },
        {
          title: "Balisage schema produit",
          content:
            "Le schema produit (donnees structurees) indique a Google exactement de quoi parle votre page et permet les resultats enrichis, ces annonces ameliorees avec notes etoilees, prix et badges de disponibilite qui dominent les resultats de recherche ecommerce. Les pages avec resultats enrichis obtiennent systematiquement des taux de clic plus eleves que les liens bleus simples, et nous avons mesure des ameliorations de CTR de 15-35% apres implementation du schema produit sur les boutiques de nos clients.\n\nLes proprietes essentielles du schema Produit a inclure sont : name, description, image, brand, sku, offers (avec prix, devise et disponibilite), et aggregateRating (si vous avez des avis). Chaque propriete doit refleter fidelement ce qui est visible sur la page, Google penalise les donnees structurees trompeuses. Si votre produit affiche 49,99€ sur la page, le prix du schema doit correspondre exactement.\n\nImplementez le schema au format JSON-LD, que Google recommande par rapport au microdata ou RDFa. Placez le script JSON-LD dans le head ou le body de la page. La plupart des plateformes ecommerce modernes incluent le schema produit par defaut ou proposent des applications qui le generent automatiquement. Cependant, nous recommandons toujours d'auditer le schema auto-genere car les plugins omettent frequemment des proprietes ou produisent des valeurs incorrectes.\n\nValidez votre schema avec l'outil de test des resultats enrichis de Google apres implementation. Les erreurs courantes incluent les champs obligatoires manquants, les types de donnees incorrects (prix comme chaine au lieu de nombre), et le balisage d'avis sur des pages sans avis visibles. Corrigez les erreurs de validation rapidement, un schema invalide ne generera pas de resultats enrichis et pourrait declencher une action manuelle si Google le considere comme spam.",
          tip: "Ajoutez la propriete 'review' dans votre schema Produit uniquement quand de vrais avis clients sont affiches sur la page. Google a sevi contre le balisage d'avis qui ne correspond pas au contenu d'avis visible, et les violations peuvent entrainer la perte de tous les resultats enrichis sur l'ensemble de votre domaine.",
        },
        {
          title: "Texte alternatif des images et nommage des fichiers",
          content:
            "Les images produit representent une opportunite SEO significative que la plupart des boutiques gaspillent. Google Images genere une part notable du trafic ecommerce, nous avons constate qu'il represente 10-25% des visites organiques pour les categories de produits visuelles comme le mobilier, la mode et la decoration interieure. L'optimisation du texte alternatif et des noms de fichiers des images est le point d'entree pour capter ce trafic.\n\nLes noms de fichiers doivent decrire le produit avant meme que l'image ne soit telechargee. Renommez « IMG_4582.jpg » en « sac-bandouliere-cuir-rouge-face-avant.jpg » avant de le mettre sur votre site. Les moteurs de recherche utilisent les noms de fichiers comme signal de classement pour la recherche d'images, et les noms descriptifs aident aussi les lecteurs d'ecran a fournir du contexte aux acheteurs malvoyants. Utilisez des tirets pour separer les mots, gardez les noms concis et incluez le mot-cle produit principal.\n\nLe texte alternatif sert un double objectif : accessibilite et SEO. Redigez un texte alternatif qui decrit ce que montre l'image comme si vous l'expliquiez a quelqu'un qui ne peut pas la voir. « Sac bandouliere en cuir rouge avec bandouliere chaine doree, vue de face » indique aux lecteurs d'ecran et aux moteurs de recherche exactement ce qui se trouve dans l'image. Evitez le bourrage de mots-cles dans le texte alternatif, « acheter sac cuir rouge meilleur sac bandouliere cuir rouge promo » est du spam inutile.\n\nPour les pages produits avec plusieurs images (face avant, dos, detail, lifestyle), variez le texte alternatif pour decrire chaque vue specifique. Cela cree de multiples opportunites de classement dans la recherche d'images pour differentes requetes. La photo lifestyle de quelqu'un portant le sac dans un cafe pourrait se classer pour « tenue sac bandouliere » tandis que la photo de detail se classe pour « bandouliere chaine doree sac ».",
        },
        {
          title: "Signaux UX qui affectent les classements des pages produits",
          content:
            "Google mesure comment les utilisateurs interagissent avec vos pages produits apres avoir clique depuis les resultats de recherche. Des taux de rebond eleves, un temps court sur la page et le pogo-sticking (retourner aux resultats de recherche et choisir un autre listing) signalent tous que votre page n'a pas satisfait l'intention du chercheur. Ces signaux comportementaux influencent les classements dans le temps, ce qui signifie que l'UX et le SEO sont profondement lies sur les pages produits.\n\nLa vitesse de chargement est le facteur UX le plus mesurable. Les pages produits chargees d'images non compressees, de JavaScript excessif et de scripts de tracking tiers mettent souvent 4-6 secondes a charger sur mobile. Les Core Web Vitals de Google, Largest Contentful Paint, Interaction to Next Paint et Cumulative Layout Shift, mesurent directement la performance de chargement, l'interactivite et la stabilite visuelle. Nous visons moins de 2,5 secondes pour le LCP, moins de 200ms pour l'INP et moins de 0,1 pour le CLS sur toutes les pages produits.\n\nL'utilisabilite mobile est tout aussi critique. Plus de 60% du trafic ecommerce provient des appareils mobiles, et une page produit difficile a naviguer sur un telephone perdra des classements et des ventes. Les cibles de tapotement doivent etre assez grandes pour les pouces, les images produit doivent etre zoomables, et le bouton d'ajout au panier doit etre visible sans defilement excessif. Testez chaque template de page produit sur de vrais appareils mobiles, pas seulement avec les outils de redimensionnement du navigateur.\n\nLes elements de confiance reduisent les taux de rebond et augmentent le temps passe sur la page. Les frais de livraison visibles, les politiques de retour, les badges de securite et les avis clients donnent aux acheteurs des raisons de rester sur la page plutot que de retourner aux resultats de recherche. Une page produit qui repond immediatement a « combien coute la livraison » et « puis-je retourner ceci » maintient les utilisateurs engages, ce qui envoie des signaux positifs a Google sur la qualite et la pertinence de votre page.",
          items: [
            "Viser un LCP sous 2,5 secondes, un INP sous 200ms et un CLS sous 0,1 pour toutes les pages produits",
            "Assurer l'utilisabilite mobile avec des images zoomables, de grandes cibles tactiles et des CTA visibles",
            "Afficher les frais de livraison, les politiques de retour et les badges de confiance au-dessus de la ligne de flottaison",
            "Inclure les avis clients pour augmenter le temps passe et reduire les taux de rebond",
          ],
        },
      ],
      navLabels: {
        previous: "Tendances saisonnieres des mots-cles",
        next: "SEO des pages categories",
      },
    },
    es: {
      badge: "SEO On-Page",
      heading: "SEO de paginas de producto",
      intro:
        "Tus paginas de producto son donde ocurren las transacciones, sin embargo la mayoria de las tiendas online las tratan como algo secundario, copiando descripciones del fabricante, subiendo imagenes sin optimizar y usando etiquetas de titulo genericas. Una pagina de producto bien optimizada cumple tres funciones simultaneamente: se posiciona para consultas de producto especificas, convence al comprador de comprar, y envia datos estructurados a los motores de busqueda para que tus listados destaquen en los resultados. Consideramos la optimizacion de paginas de producto como una de las actividades con mayor ROI en SEO para ecommerce, porque el trafico que estas paginas atraen ya lleva una fuerte intencion de compra.",
      readTime: "10 min de lectura",
      sections: [
        {
          title: "Anatomia de una pagina de producto bien optimizada",
          content:
            "Cada pagina de producto de alto rendimiento comparte un conjunto de elementos estructurales que satisfacen tanto a los motores de busqueda como a los compradores. En la parte superior, un H1 claro que coincide con el nombre del producto y la palabra clave principal. Debajo, imagenes del producto con texto alternativo descriptivo. Luego una descripcion unica que va mas alla de las especificaciones para abordar preguntas del comprador y casos de uso. Los elementos de soporte incluyen navegacion por migas de pan, resenas de clientes, enlaces a productos relacionados y marcado de datos estructurados.\n\nEl orden y la jerarquia visual de estos elementos importa. Los estudios de eye-tracking muestran consistentemente que los compradores escanean en patron de F: primero miran la imagen del producto, luego el titulo, luego el precio y finalmente la descripcion. Tus elementos SEO deben alinearse con este comportamiento de escaneo natural en lugar de contradecirlo. Una etiqueta de titulo atiborrada de palabras clave que no coincide con el H1 visible confunde tanto a usuarios como a motores de busqueda.\n\nAuditamos paginas de producto usando una lista de verificacion de 12 puntos que cubre SEO tecnico, calidad de contenido y elementos de conversion. Las tiendas que obtienen las puntuaciones mas altas en esta lista tienden a tener 30-50% mas de trafico organico por pagina de producto comparado con competidores en el mismo nicho. La diferencia no esta en ningun elemento individual, es el efecto compuesto de hacer bien cada elemento en miles de paginas de producto.",
          items: [
            "Encabezado H1 que coincida con el nombre del producto y la palabra clave principal",
            "Descripcion de producto unica con lenguaje orientado al comprador (no copiada del fabricante)",
            "Imagenes optimizadas con texto alternativo descriptivo y tamanos de archivo comprimidos",
            "Navegacion de migas de pan mostrando la jerarquia de categorias",
            "Marcado de esquema de producto para resultados enriquecidos en la busqueda",
            "Resenas de clientes mostradas en la pagina con esquema de review",
          ],
        },
        {
          title: "Etiquetas de titulo con atributos de producto",
          content:
            "Las etiquetas de titulo de las paginas de producto deben equilibrar la inclusion de palabras clave con el atractivo al clic. La formula mas efectiva que hemos encontrado para paginas de producto es: Nombre del Producto + Atributo Clave + Marca + Nombre de la Tienda. Por ejemplo, \"Calcetines de Senderismo Lana Merino - Ligeros, Talla 42-45 | TrailGear\" agrupa la palabra clave del producto, un atributo diferenciador, informacion de talla y el nombre de la tienda en una sola etiqueta.\n\nIncluir atributos de producto como color, talla, material o numero de modelo en las etiquetas de titulo captura busquedas de cola larga que tus competidores pierden. Alguien que busca \"taza de cafe ceramica azul 350ml\" tiene una intencion de compra extremadamente especifica, y una etiqueta de titulo que coincida con esos atributos ganara el clic sobre un listado generico de \"Taza de Cafe\" siempre.\n\nPara tiendas con catalogos grandes, escribir manualmente etiquetas de titulo para cada producto no es realista. En su lugar, construye un sistema de plantillas que extraiga atributos de producto dinamicamente. La mayoria de las plataformas ecommerce soportan esto mediante variables de plantilla: {Nombre del Producto} - {Color} {Material} | {Marca} | {Nombre de la Tienda}. La clave es elegir que atributos importan mas para cada categoria. Los productos de ropa se benefician del material y la talla en el titulo. La electronica necesita numeros de modelo. Los muebles se benefician de las dimensiones.\n\nManten las etiquetas de titulo por debajo de 60 caracteres cuando sea posible. Google trunca los titulos mas largos en los resultados de busqueda, y un titulo cortado se ve poco profesional y pierde informacion. Si tu nombre de producto solo supera los 40 caracteres, tendras que priorizar que atributos incluir y cuales guardar para la meta descripcion.",
          tip: "Prueba diferentes formulas de etiquetas de titulo en categorias de productos ejecutando experimentos A/B en Google Search Console. Cambia las etiquetas de titulo de 50 productos en una categoria, espera 4-6 semanas y compara los cambios de CTR con un grupo de control de productos sin cambios en la misma categoria.",
        },
        {
          title: "Escribir descripciones de producto unicas",
          content:
            "Las descripciones del fabricante son una de las mayores desventajas SEO en el ecommerce. Cuando 200 tiendas usan el mismo texto para el mismo producto, Google no tiene razon para posicionar tu pagina por encima de las demas. El contenido duplicado no activa una penalizacion, pero elimina tu capacidad de diferenciarte en los resultados de busqueda. Escribir descripciones unicas es innegociable para rankings de producto competitivos.\n\nUna descripcion de producto fuerte responde a tres preguntas que el comprador se hace: Que es este producto? Por que deberia comprarlo aqui? Como resuelve mi problema especifico? Comienza con un parrafo corto que cubra el beneficio principal del producto, no una lista de caracteristicas, sino el resultado que el comprador obtiene. Luego amplia con detalles sobre materiales, tallas, compatibilidad o casos de uso. Cierra con diferenciadores como garantia, devoluciones gratuitas o accesorios incluidos.\n\nLa longitud depende de la complejidad y el precio del producto. Una funda de telefono de 15 euros puede necesitar 100-150 palabras. Una maquina de espresso de 2.000 euros merece 400-600 palabras cubriendo cada aspecto que un comprador investigaria antes de comprar. Ajusta la profundidad de tu descripcion al nivel de consideracion de la compra, cuanto mas caro o complejo el producto, mas contenido necesita la pagina para posicionarse y convertir.\n\nIncorpora palabras clave relevantes de forma natural a lo largo de la descripcion, pero escribe primero para el lector humano. Frases como \"esta botella de agua de acero inoxidable mantiene las bebidas frias durante 24 horas\" incluyen naturalmente las palabras clave que un buscador usaria mientras comunican un beneficio concreto. La insercion forzada de palabras clave como \"comprar mejor botella acero inoxidable online\" se lee mal y no mejora los rankings.",
          items: [
            "Reescribir el texto del fabricante con la voz de tu marca y angulos unicos",
            "Comenzar con el beneficio principal en lugar de una lista de especificaciones tecnicas",
            "Ajustar la profundidad de la descripcion al precio y complejidad del producto, mayor precio significa contenido mas largo",
            "Incluir variaciones naturales de palabras clave en todo el texto sin forzarlas",
          ],
        },
        {
          title: "Marcado de esquema de producto",
          content:
            "El esquema de producto (datos estructurados) le dice a Google exactamente de que trata tu pagina y habilita resultados enriquecidos, esos listados mejorados con calificaciones de estrellas, precios e indicadores de disponibilidad que dominan los resultados de busqueda ecommerce. Las paginas con resultados enriquecidos obtienen consistentemente tasas de clic mas altas que los enlaces azules simples, y hemos medido mejoras de CTR del 15-35% despues de implementar el esquema de producto en las tiendas de nuestros clientes.\n\nLas propiedades esenciales del esquema de Producto a incluir son: name, description, image, brand, sku, offers (con precio, moneda y disponibilidad) y aggregateRating (si tienes resenas). Cada propiedad debe reflejar con precision lo que es visible en la pagina, Google penaliza los datos estructurados enganosos. Si tu producto muestra 49,99 euros en la pagina, el precio del esquema debe coincidir exactamente.\n\nImplementa el esquema usando formato JSON-LD, que Google recomienda sobre microdata o RDFa. Coloca el script JSON-LD en el head o body de la pagina. La mayoria de las plataformas ecommerce modernas incluyen el esquema de producto por defecto u ofrecen aplicaciones que lo generan automaticamente. Sin embargo, siempre recomendamos auditar el esquema auto-generado porque los plugins frecuentemente omiten propiedades o producen valores incorrectos.\n\nValida tu esquema usando la herramienta de prueba de resultados enriquecidos de Google despues de la implementacion. Los errores comunes incluyen campos obligatorios faltantes, tipos de datos incorrectos (precio como string vs. numero) y marcado de resenas en paginas sin resenas visibles. Corrige los errores de validacion rapidamente, un esquema invalido no generara resultados enriquecidos y podria desencadenar una accion manual si Google lo considera spam.",
          tip: "Anade la propiedad 'review' dentro de tu esquema de Producto solo cuando las resenas reales de clientes se muestran en la pagina. Google ha tomado medidas contra el marcado de resenas que no corresponde al contenido de resenas visible, y las violaciones pueden resultar en la perdida de todos los resultados enriquecidos en todo tu dominio.",
        },
        {
          title: "Texto alternativo de imagenes y nombres de archivo",
          content:
            "Las imagenes de producto representan una oportunidad SEO significativa que la mayoria de las tiendas desperdician. Google Images genera una parte considerable del trafico ecommerce, hemos visto que representa del 10-25% de las visitas organicas para categorias de productos visuales como muebles, moda y decoracion del hogar. Optimizar el texto alternativo y los nombres de archivo de las imagenes es el punto de entrada para capturar este trafico.\n\nLos nombres de archivo deben describir el producto antes de que la imagen se suba. Renombra \"IMG_4582.jpg\" a \"bolso-bandolera-cuero-rojo-frente.jpg\" antes de ponerlo en tu sitio. Los motores de busqueda usan los nombres de archivo como senal de posicionamiento para la busqueda de imagenes, y los nombres descriptivos tambien ayudan a los lectores de pantalla a proporcionar contexto para compradores con discapacidad visual. Usa guiones para separar palabras, manten los nombres concisos e incluye la palabra clave principal del producto.\n\nEl texto alternativo cumple un doble proposito: accesibilidad y SEO. Escribe texto alternativo que describa lo que muestra la imagen como si estuvieras explicandoselo a alguien que no puede verla. \"Bolso bandolera de cuero rojo con correa de cadena dorada, vista frontal\" les dice tanto a los lectores de pantalla como a los motores de busqueda exactamente lo que hay en la imagen. Evita rellenar el texto alternativo con palabras clave, \"comprar bolso cuero rojo mejor bolso bandolera cuero rojo oferta\" es spam inutil.\n\nPara paginas de producto con multiples imagenes (frente, espalda, detalle, lifestyle), varia el texto alternativo para describir cada vista especifica. Esto crea multiples oportunidades de posicionamiento en busqueda de imagenes para diferentes consultas. La foto lifestyle de alguien llevando el bolso en un cafe podria posicionarse para \"outfit bolso bandolera\" mientras la foto de detalle se posiciona para \"correa cadena dorada bolso\".",
        },
        {
          title: "Senales UX que afectan los rankings de paginas de producto",
          content:
            "Google mide como los usuarios interactuan con tus paginas de producto despues de hacer clic desde los resultados de busqueda. Altas tasas de rebote, tiempo corto en la pagina y pogo-sticking (hacer clic para volver a los resultados de busqueda y elegir otro listado) senalan que tu pagina no satisfizo la intencion del buscador. Estas senales de comportamiento influyen en los rankings con el tiempo, lo que significa que UX y SEO estan profundamente conectados en las paginas de producto.\n\nLa velocidad de carga es el factor UX mas medible. Las paginas de producto cargadas con imagenes sin comprimir, JavaScript excesivo y scripts de rastreo de terceros a menudo tardan 4-6 segundos en cargar en movil. Los Core Web Vitals de Google, Largest Contentful Paint, Interaction to Next Paint y Cumulative Layout Shift, miden directamente el rendimiento de carga, la interactividad y la estabilidad visual. Apuntamos a menos de 2,5 segundos para LCP, menos de 200ms para INP y menos de 0,1 para CLS en todas las paginas de producto.\n\nLa usabilidad movil es igualmente critica. Mas del 60% del trafico ecommerce proviene de dispositivos moviles, y una pagina de producto dificil de navegar en un telefono perdera tanto rankings como ventas. Los objetivos de toque deben ser lo suficientemente grandes para los pulgares, las imagenes de producto deben ser ampliables y el boton de anadir al carrito debe ser visible sin desplazamiento excesivo. Prueba cada plantilla de pagina de producto en dispositivos moviles reales, no solo con herramientas de redimensionamiento del navegador.\n\nLos elementos de confianza reducen las tasas de rebote y aumentan el tiempo en la pagina. Los costos de envio visibles, las politicas de devolucion, las insignias de seguridad y las resenas de clientes dan a los compradores razones para quedarse en la pagina en lugar de volver a los resultados de busqueda. Una pagina de producto que responde inmediatamente \"cuanto cuesta el envio\" y \"puedo devolver esto\" mantiene a los usuarios comprometidos, lo que envia senales positivas a Google sobre la calidad y relevancia de tu pagina.",
          items: [
            "Apuntar a LCP menor de 2,5 segundos, INP menor de 200ms y CLS menor de 0,1 para todas las paginas de producto",
            "Asegurar usabilidad movil con imagenes ampliables, objetivos de toque grandes y CTAs visibles",
            "Mostrar costos de envio, politicas de devolucion e insignias de confianza por encima del pliegue",
            "Incluir resenas de clientes para aumentar el tiempo en pagina y reducir las tasas de rebote",
          ],
        },
      ],
      navLabels: {
        previous: "Tendencias estacionales de palabras clave",
        next: "SEO de paginas de categoria",
      },
    },
    it: {
      badge: "SEO On-Page",
      heading: "SEO delle pagine prodotto",
      intro:
        "Le tue pagine prodotto sono dove avvengono le transazioni, eppure la maggior parte degli ecommerce le tratta come un ripensamento, copiando le descrizioni del produttore, caricando immagini non ottimizzate e aggiungendo title tag generici. Una pagina prodotto ben ottimizzata svolge tre funzioni contemporaneamente: si posiziona per query di prodotto specifiche, convince l'acquirente ad acquistare e invia dati strutturati ai motori di ricerca perche le tue inserzioni risaltino nei risultati. Consideriamo l'ottimizzazione delle pagine prodotto come una delle attivita con il piu alto ROI nella SEO ecommerce, perche il traffico che queste pagine attraggono porta gia una forte intenzione di acquisto.",
      readTime: "10 min di lettura",
      sections: [
        {
          title: "Anatomia di una pagina prodotto ben ottimizzata",
          content:
            "Ogni pagina prodotto ad alte prestazioni condivide un insieme di elementi strutturali che soddisfano sia i motori di ricerca che gli acquirenti. In alto, un H1 chiaro che corrisponde al nome del prodotto e alla parola chiave principale. Sotto, immagini del prodotto con testo alternativo descrittivo. Poi una descrizione unica che va oltre le specifiche per rispondere alle domande degli acquirenti e ai casi d'uso. Gli elementi di supporto includono la navigazione breadcrumb, le recensioni dei clienti, i link a prodotti correlati e il markup dei dati strutturati.\n\nL'ordine e la gerarchia visiva di questi elementi contano. Gli studi di eye-tracking mostrano costantemente che gli acquirenti scansionano secondo un pattern a F: guardano prima l'immagine del prodotto, poi il titolo, poi il prezzo e infine la descrizione. I tuoi elementi SEO dovrebbero allinearsi con questo comportamento di scansione naturale piuttosto che contrastarlo. Un title tag riempito di parole chiave che non corrisponde all'H1 visibile confonde sia gli utenti che i motori di ricerca.\n\nVerifichiamo le pagine prodotto usando una checklist a 12 punti che copre SEO tecnico, qualita del contenuto ed elementi di conversione. I negozi che ottengono i punteggi piu alti su questa checklist tendono ad avere il 30-50% di traffico organico in piu per pagina prodotto rispetto ai concorrenti nella stessa nicchia. La differenza non sta in un singolo elemento, e l'effetto composto di fare bene ogni elemento su migliaia di pagine prodotto.",
          items: [
            "Intestazione H1 corrispondente al nome del prodotto e alla parola chiave principale",
            "Descrizione prodotto unica con linguaggio orientato all'acquirente (non copiata dal produttore)",
            "Immagini ottimizzate con testo alternativo descrittivo e dimensioni file compresse",
            "Navigazione breadcrumb che mostra la gerarchia delle categorie",
            "Markup schema prodotto per risultati arricchiti nella ricerca",
            "Recensioni clienti mostrate sulla pagina con schema review",
          ],
        },
        {
          title: "Title tag con attributi di prodotto",
          content:
            "I title tag delle pagine prodotto devono bilanciare l'inclusione di parole chiave con l'attrattiva al clic. La formula piu efficace che abbiamo trovato per le pagine prodotto e: Nome Prodotto + Attributo Chiave + Marca + Nome Negozio. Per esempio, \"Calze da Trekking in Lana Merino - Leggere, Taglia 42-45 | TrailGear\" racchiude la parola chiave del prodotto, un attributo differenziante, l'informazione sulla taglia e il nome del negozio in un unico tag.\n\nIncludere attributi di prodotto come colore, taglia, materiale o numero di modello nei title tag cattura ricerche a coda lunga che i tuoi concorrenti perdono. Chi cerca \"tazza da caffe ceramica blu 350ml\" ha un'intenzione d'acquisto estremamente specifica, e un title tag che corrisponde a quegli attributi otterra il clic rispetto a un'inserzione generica \"Tazza da Caffe\" ogni volta.\n\nPer i negozi con grandi cataloghi, scrivere manualmente i title tag per ogni prodotto non e realistico. Costruisci invece un sistema di template che estrae gli attributi del prodotto dinamicamente. La maggior parte delle piattaforme ecommerce lo supporta tramite variabili di template: {Nome Prodotto} - {Colore} {Materiale} | {Marca} | {Nome Negozio}. La chiave e scegliere quali attributi contano di piu per ogni categoria. I prodotti di abbigliamento beneficiano di materiale e taglia nel titolo. L'elettronica ha bisogno dei numeri di modello. I mobili beneficiano delle dimensioni.\n\nMantieni i title tag sotto i 60 caratteri quando possibile. Google tronca i titoli piu lunghi nei risultati di ricerca, e un titolo tagliato appare poco professionale e perde informazioni. Se il solo nome del tuo prodotto supera i 40 caratteri, dovrai dare priorita a quali attributi includere e quali riservare per la meta description.",
          tip: "Testa diverse formule di title tag nelle categorie di prodotto eseguendo esperimenti A/B in Google Search Console. Modifica i title tag di 50 prodotti in una categoria, attendi 4-6 settimane e confronta i cambiamenti di CTR con un gruppo di controllo di prodotti invariati nella stessa categoria.",
        },
        {
          title: "Scrivere descrizioni prodotto uniche",
          content:
            "Le descrizioni del produttore sono una delle piu grandi responsabilita SEO nell'ecommerce. Quando 200 negozi usano lo stesso testo per lo stesso prodotto, Google non ha motivo di posizionare la tua pagina sopra le altre. Il contenuto duplicato non attiva una penalizzazione, ma elimina la tua capacita di differenziarti nei risultati di ricerca. Scrivere descrizioni uniche e imprescindibile per posizionamenti di prodotto competitivi.\n\nUna descrizione prodotto efficace risponde a tre domande che l'acquirente si pone: Cos'e questo prodotto? Perche dovrei comprarlo da voi? Come risolve il mio problema specifico? Inizia con un breve paragrafo che copre il beneficio principale del prodotto, non un elenco di caratteristiche, ma il risultato che l'acquirente ottiene. Poi espandi con dettagli su materiali, taglie, compatibilita o casi d'uso. Chiudi con i fattori differenzianti come garanzia, resi gratuiti o accessori inclusi.\n\nLa lunghezza dipende dalla complessita e dal prezzo del prodotto. Una cover per telefono da 15 euro potrebbe richiedere 100-150 parole. Una macchina per espresso da 2.000 euro merita 400-600 parole che coprano ogni aspetto che un acquirente ricercherebbe prima dell'acquisto. Adatta la profondita della descrizione al livello di considerazione dell'acquisto, piu il prodotto e costoso o complesso, piu contenuto la pagina necessita per posizionarsi e convertire.\n\nIncorpora parole chiave pertinenti in modo naturale in tutta la descrizione, ma scrivi prima per il lettore umano. Frasi come \"questa borraccia in acciaio inossidabile mantiene le bevande fredde per 24 ore\" includono naturalmente le parole chiave che un cercatore userebbe comunicando al contempo un beneficio concreto. L'inserimento forzato di parole chiave come \"comprare migliore borraccia acciaio inossidabile online\" si legge male e non migliora i posizionamenti.",
          items: [
            "Riscrivere il testo del produttore nella voce del tuo marchio con angoli unici",
            "Iniziare con il beneficio principale piuttosto che con un elenco di specifiche tecniche",
            "Adattare la profondita della descrizione al prezzo e alla complessita del prodotto, prezzo piu alto significa contenuto piu lungo",
            "Includere variazioni naturali di parole chiave in tutto il testo senza forzarle",
          ],
        },
        {
          title: "Markup schema prodotto",
          content:
            "Lo schema prodotto (dati strutturati) comunica a Google esattamente di cosa tratta la tua pagina e abilita i risultati arricchiti, quelle inserzioni migliorate con valutazioni in stelle, prezzi e badge di disponibilita che dominano i risultati di ricerca ecommerce. Le pagine con risultati arricchiti ottengono costantemente tassi di clic piu alti rispetto ai semplici link blu, e abbiamo misurato miglioramenti del CTR del 15-35% dopo l'implementazione dello schema prodotto nei negozi dei nostri clienti.\n\nLe proprieta essenziali dello schema Prodotto da includere sono: name, description, image, brand, sku, offers (con prezzo, valuta e disponibilita) e aggregateRating (se hai recensioni). Ogni proprieta deve riflettere accuratamente cio che e visibile sulla pagina, Google penalizza i dati strutturati fuorvianti. Se il tuo prodotto mostra 49,99 euro sulla pagina, il prezzo nello schema deve corrispondere esattamente.\n\nImplementa lo schema usando il formato JSON-LD, che Google raccomanda rispetto a microdata o RDFa. Posiziona lo script JSON-LD nell'head o nel body della pagina. La maggior parte delle piattaforme ecommerce moderne include lo schema prodotto per impostazione predefinita o offre app che lo generano automaticamente. Tuttavia, raccomandiamo sempre di verificare lo schema auto-generato perche i plugin frequentemente omettono proprieta o producono valori errati.\n\nValida il tuo schema usando lo strumento di test dei risultati arricchiti di Google dopo l'implementazione. Gli errori comuni includono campi obbligatori mancanti, tipi di dati errati (prezzo come stringa invece che numero) e markup delle recensioni su pagine senza recensioni visibili. Correggi gli errori di validazione tempestivamente, uno schema non valido non generera risultati arricchiti e potrebbe innescare un'azione manuale se Google lo considera spam.",
          tip: "Aggiungi la proprieta 'review' nel tuo schema Prodotto solo quando le recensioni reali dei clienti sono mostrate sulla pagina. Google ha intensificato le azioni contro il markup delle recensioni che non corrisponde al contenuto delle recensioni visibili, e le violazioni possono comportare la perdita di tutti i risultati arricchiti su tutto il tuo dominio.",
        },
        {
          title: "Testo alternativo delle immagini e denominazione dei file",
          content:
            "Le immagini dei prodotti rappresentano un'opportunita SEO significativa che la maggior parte dei negozi spreca. Google Images genera una quota rilevante del traffico ecommerce, abbiamo visto che rappresenta il 10-25% delle visite organiche per categorie di prodotti visivamente orientate come mobili, moda e arredamento. Ottimizzare il testo alternativo e i nomi dei file delle immagini e il punto di ingresso per catturare questo traffico.\n\nI nomi dei file dovrebbero descrivere il prodotto prima ancora che l'immagine venga caricata. Rinomina \"IMG_4582.jpg\" in \"borsa-tracolla-pelle-rossa-fronte.jpg\" prima di metterla sul tuo sito. I motori di ricerca usano i nomi dei file come segnale di posizionamento per la ricerca immagini, e i nomi descrittivi aiutano anche gli screen reader a fornire contesto per gli acquirenti ipovedenti. Usa i trattini per separare le parole, mantieni i nomi concisi e includi la parola chiave principale del prodotto.\n\nIl testo alternativo serve un doppio scopo: accessibilita e SEO. Scrivi testo alternativo che descriva cosa mostra l'immagine come se lo stessi spiegando a qualcuno che non puo vederla. \"Borsa a tracolla in pelle rossa con tracolla a catena dorata, vista frontale\" comunica sia agli screen reader che ai motori di ricerca esattamente cosa c'e nell'immagine. Evita di riempire il testo alternativo di parole chiave, \"comprare borsa pelle rossa migliore borsa tracolla pelle rossa offerta\" e spam inutile.\n\nPer le pagine prodotto con piu immagini (fronte, retro, dettaglio, lifestyle), varia il testo alternativo per descrivere ogni vista specifica. Questo crea molteplici opportunita di posizionamento nella ricerca immagini per diverse query. Lo scatto lifestyle di qualcuno che porta la borsa in un bar potrebbe posizionarsi per \"outfit borsa a tracolla\" mentre lo scatto di dettaglio si posiziona per \"tracolla catena dorata borsa\".",
        },
        {
          title: "Segnali UX che influenzano i posizionamenti delle pagine prodotto",
          content:
            "Google misura come gli utenti interagiscono con le tue pagine prodotto dopo aver cliccato dai risultati di ricerca. Alti tassi di rimbalzo, tempo breve sulla pagina e pogo-sticking (cliccare indietro ai risultati di ricerca e scegliere un'altra inserzione) segnalano tutti che la tua pagina non ha soddisfatto l'intento del cercatore. Questi segnali comportamentali influenzano i posizionamenti nel tempo, il che significa che UX e SEO sono profondamente connessi sulle pagine prodotto.\n\nLa velocita della pagina e il fattore UX piu misurabile. Le pagine prodotto cariche di immagini non compresse, JavaScript eccessivo e script di tracciamento di terze parti spesso impiegano 4-6 secondi a caricarsi su mobile. I Core Web Vitals di Google, Largest Contentful Paint, Interaction to Next Paint e Cumulative Layout Shift, misurano direttamente le prestazioni di caricamento, l'interattivita e la stabilita visiva. Puntiamo a meno di 2,5 secondi per il LCP, meno di 200ms per l'INP e meno di 0,1 per il CLS su tutte le pagine prodotto.\n\nL'usabilita mobile e altrettanto critica. Oltre il 60% del traffico ecommerce proviene da dispositivi mobili, e una pagina prodotto difficile da navigare su un telefono perdera sia posizionamenti che vendite. I target di tocco devono essere abbastanza grandi per i pollici, le immagini dei prodotti devono essere zoomabili e il pulsante aggiungi al carrello deve essere visibile senza scorrimento eccessivo. Testa ogni template di pagina prodotto su dispositivi mobili reali, non solo con gli strumenti di ridimensionamento del browser.\n\nGli elementi di fiducia riducono i tassi di rimbalzo e aumentano il tempo di permanenza. Costi di spedizione visibili, politiche di reso, badge di sicurezza e recensioni dei clienti danno agli acquirenti motivi per restare sulla pagina piuttosto che tornare ai risultati di ricerca. Una pagina prodotto che risponde immediatamente a \"quanto costa la spedizione\" e \"posso restituire questo\" mantiene gli utenti coinvolti, il che invia segnali positivi a Google sulla qualita e la pertinenza della tua pagina.",
          items: [
            "Puntare a LCP sotto 2,5 secondi, INP sotto 200ms e CLS sotto 0,1 per tutte le pagine prodotto",
            "Garantire l'usabilita mobile con immagini zoomabili, grandi target di tocco e CTA visibili",
            "Mostrare costi di spedizione, politiche di reso e badge di fiducia sopra la piega",
            "Includere recensioni dei clienti per aumentare il tempo di permanenza e ridurre i tassi di rimbalzo",
          ],
        },
      ],
      navLabels: {
        previous: "Tendenze stagionali delle parole chiave",
        next: "SEO delle pagine categoria",
      },
    },
    nl: {
      badge: "On-Page SEO",
      heading: "Productpagina SEO",
      intro:
        "Je productpagina's zijn waar transacties plaatsvinden, maar toch behandelen de meeste webshops ze als bijzaak, ze kopieren fabrikantenomschrijvingen, uploaden ongeoptimaliseerde afbeeldingen en gebruiken generieke title tags. Een goed geoptimaliseerde productpagina doet drie dingen tegelijk: hij rankt voor specifieke productzoekopdrachten, hij overtuigt de koper om te kopen, en hij stuurt gestructureerde data naar zoekmachines zodat je vermeldingen opvallen in de resultaten. Wij zien productpagina-optimalisatie als een van de activiteiten met de hoogste ROI in ecommerce SEO, omdat het verkeer dat deze pagina's aantrekken al een sterke koopintentie heeft.",
      readTime: "10 min leestijd",
      sections: [
        {
          title: "Anatomie van een goed geoptimaliseerde productpagina",
          content:
            "Elke goed presterende productpagina deelt een set structurele elementen die zowel zoekmachines als kopers tevreden stellen. Bovenaan een duidelijke H1 die overeenkomt met de productnaam en het primaire zoekwoord. Daaronder productafbeeldingen met beschrijvende alt-tekst. Dan een unieke beschrijving die verder gaat dan specificaties en vragen van kopers en gebruikssituaties behandelt. Ondersteunende elementen zijn breadcrumb-navigatie, klantreviews, links naar gerelateerde producten en gestructureerde data-markup.\n\nDe volgorde en visuele hierarchie van deze elementen is belangrijk. Eye-tracking-onderzoeken tonen consequent aan dat kopers in een F-patroon scannen: ze kijken eerst naar de productafbeelding, dan de titel, dan de prijs en tot slot de beschrijving. Je SEO-elementen moeten aansluiten bij dit natuurlijke scangedrag in plaats van ertegen in te gaan. Een title tag volgepropt met zoekwoorden die niet overeenkomt met de zichtbare H1 verwart zowel gebruikers als zoekmachines.\n\nWij auditen productpagina's met een 12-punten checklist die technische SEO, contentkwaliteit en conversie-elementen dekt. De winkels die het hoogst scoren op deze checklist hebben doorgaans 30-50% meer organisch verkeer per productpagina vergeleken met concurrenten in dezelfde niche. Het verschil zit niet in een enkel element, het is het samengestelde effect van elk element goed uitvoeren op duizenden productpagina's.",
          items: [
            "H1-kop die overeenkomt met de productnaam en het primaire zoekwoord",
            "Unieke productbeschrijving met op de koper gerichte taal (niet gekopieerd van de fabrikant)",
            "Geoptimaliseerde afbeeldingen met beschrijvende alt-tekst en gecomprimeerde bestandsgroottes",
            "Breadcrumb-navigatie die de categoriehierarchie toont",
            "Product schema-markup voor rich results in de zoekmachine",
            "Klantreviews weergegeven op de pagina met review-schema",
          ],
        },
        {
          title: "Title tags met productattributen",
          content:
            "Title tags van productpagina's moeten zoekwoordopname balanceren met klikaantrekkingskracht. De meest effectieve formule die we voor productpagina's hebben gevonden is: Productnaam + Kernattribuut + Merk + Winkelnaam. Bijvoorbeeld, \"Merino Wol Wandelsokken - Lichtgewicht, Maat 42-45 | TrailGear\" bundelt het productzoekwoord, een onderscheidend attribuut, maatinformatie en de winkelnaam in een enkele tag.\n\nHet opnemen van productattributen zoals kleur, maat, materiaal of modelnummer in title tags vangt long-tail zoekopdrachten op die je concurrenten missen. Iemand die zoekt naar \"blauwe keramische 350ml koffiemok\" heeft een extreem specifieke koopintentie, en een title tag die overeenkomt met die attributen wint elke keer de klik ten opzichte van een generieke \"Koffiemok\" vermelding.\n\nVoor winkels met grote catalogi is het handmatig schrijven van title tags voor elk product niet realistisch. Bouw in plaats daarvan een templatesysteem dat productattributen dynamisch invoegt. De meeste ecommerce-platforms ondersteunen dit via templatevariabelen: {Productnaam} - {Kleur} {Materiaal} | {Merk} | {Winkelnaam}. De sleutel is kiezen welke attributen het belangrijkst zijn voor elke categorie. Kledingproducten profiteren van materiaal en maat in de titel. Elektronica heeft modelnummers nodig. Meubels profiteren van afmetingen.\n\nHoud title tags waar mogelijk onder de 60 tekens. Google kapt langere titels af in zoekresultaten, en een afgekapte titel ziet er onprofessioneel uit en verliest informatie. Als je productnaam alleen al meer dan 40 tekens beslaat, moet je prioriteren welke attributen je opneemt en welke je bewaart voor de meta-omschrijving.",
          tip: "Test verschillende title tag-formules voor productcategorieen door A/B-experimenten uit te voeren in Google Search Console. Wijzig de title tags van 50 producten in een categorie, wacht 4-6 weken en vergelijk CTR-veranderingen met een controlegroep van ongewijzigde producten in dezelfde categorie.",
        },
        {
          title: "Unieke productbeschrijvingen schrijven",
          content:
            "Fabrikantenomschrijvingen zijn een van de grootste SEO-zwaktes in ecommerce. Wanneer 200 winkels dezelfde tekst gebruiken voor hetzelfde product, heeft Google geen reden om jouw pagina boven de andere te ranken. Duplicate content veroorzaakt geen penalty, maar het elimineert je vermogen om je te onderscheiden in zoekresultaten. Het schrijven van unieke beschrijvingen is niet onderhandelbaar voor concurrerende productrankings.\n\nEen sterke productbeschrijving beantwoordt drie vragen die de koper stelt: Wat is dit product? Waarom zou ik het bij jullie kopen? Hoe lost het mijn specifieke probleem op? Begin met een korte alinea die het primaire voordeel van het product behandelt, geen functielijst, maar het resultaat dat de koper krijgt. Breid dan uit met details over materialen, maten, compatibiliteit of gebruikssituaties. Sluit af met onderscheidende factoren zoals garantie, gratis retourneren of meegeleverde accessoires.\n\nDe lengte hangt af van de complexiteit en het prijspunt van het product. Een telefoonhoesje van 15 euro heeft misschien 100-150 woorden nodig. Een espressomachine van 2.000 euro verdient 400-600 woorden die elk aspect behandelen dat een koper zou onderzoeken voor de aankoop. Stem je beschrijvingsdiepte af op het overwegingsniveau van de aankoop, hoe duurder of complexer het product, hoe meer content de pagina nodig heeft om te ranken en te converteren.\n\nVerwerk relevante zoekwoorden op natuurlijke wijze door de hele beschrijving, maar schrijf eerst voor de menselijke lezer. Zinnen als \"deze roestvrijstalen drinkfles houdt dranken 24 uur koud\" bevatten van nature de zoekwoorden die een zoeker zou gebruiken terwijl ze ook een concreet voordeel communiceren. Geforceerde zoekwoordinvoeging zoals \"koop beste roestvrijstalen drinkfles online\" leest slecht en verbetert geen rankings.",
          items: [
            "Fabrikantteksten herschrijven in je eigen merkstem met unieke invalshoeken",
            "Beginnen met het primaire voordeel in plaats van een lijst met technische specificaties",
            "Beschrijvingsdiepte afstemmen op productprijs en complexiteit, hogere prijs betekent langere content",
            "Natuurlijke zoekwoordvariaties door de hele tekst opnemen zonder ze te forceren",
          ],
        },
        {
          title: "Product schema-markup",
          content:
            "Product schema (gestructureerde data) vertelt Google precies waar je pagina over gaat en maakt rich results mogelijk, die verbeterde vermeldingen met sterrenwaarderingen, prijzen en beschikbaarheidsbadges die de ecommerce zoekresultaten domineren. Pagina's met rich results behalen consistent hogere klikpercentages dan gewone blauwe links, en we hebben CTR-verbeteringen van 15-35% gemeten na implementatie van product schema in webshops van klanten.\n\nDe essentiele Product schema-eigenschappen om op te nemen zijn: name, description, image, brand, sku, offers (met prijs, valuta en beschikbaarheid) en aggregateRating (als je reviews hebt). Elke eigenschap moet nauwkeurig weergeven wat zichtbaar is op de pagina, Google bestraft misleidende gestructureerde data. Als je product 49,99 euro op de pagina toont, moet de schemaprijs exact overeenkomen.\n\nImplementeer schema in JSON-LD-formaat, dat Google aanbeveelt boven microdata of RDFa. Plaats het JSON-LD-script in de head of body van de pagina. De meeste moderne ecommerce-platforms bevatten standaard product schema of bieden apps die het automatisch genereren. Wij raden echter altijd aan om automatisch gegenereerd schema te auditen omdat plugins regelmatig eigenschappen missen of onjuiste waarden produceren.\n\nValideer je schema met Googles Rich Results Test-tool na implementatie. Veelvoorkomende fouten zijn ontbrekende verplichte velden, onjuiste datatypes (prijs als string vs. nummer) en reviewmarkup op pagina's zonder zichtbare reviews. Los validatiefouten snel op, ongeldig schema genereert geen rich results en kan een handmatige actie uitlokken als Google het als spam beschouwt.",
          tip: "Voeg de 'review'-eigenschap alleen toe binnen je Product schema wanneer daadwerkelijke klantreviews op de pagina worden weergegeven. Google heeft het optreden tegen reviewmarkup die niet overeenkomt met zichtbare reviewcontent aangescherpt, en overtredingen kunnen leiden tot het verlies van alle rich results over je hele domein.",
        },
        {
          title: "Alt-tekst voor afbeeldingen en bestandsnaamgeving",
          content:
            "Productafbeeldingen vertegenwoordigen een aanzienlijke SEO-kans die de meeste winkels verspillen. Google Images levert een aanzienlijk deel van het ecommerce-verkeer, we hebben gezien dat het 10-25% van de organische bezoeken uitmaakt voor visueel gedreven productcategorieen zoals meubels, mode en woondecoratie. Het optimaliseren van alt-tekst en bestandsnamen van afbeeldingen is het startpunt voor het vastleggen van dit verkeer.\n\nBestandsnamen moeten het product beschrijven voordat de afbeelding wordt geupload. Hernoem \"IMG_4582.jpg\" naar \"rode-leren-crossbodytas-voorkant.jpg\" voordat het op je site komt. Zoekmachines gebruiken bestandsnamen als rankingsignaal voor beeldzoeken, en beschrijvende namen helpen ook schermlezers context te bieden voor visueel beperkte kopers. Gebruik koppeltekens om woorden te scheiden, houd namen beknopt en neem het primaire productzoekwoord op.\n\nAlt-tekst dient een dubbel doel: toegankelijkheid en SEO. Schrijf alt-tekst die beschrijft wat de afbeelding toont alsof je het uitlegt aan iemand die het niet kan zien. \"Rode leren crossbodytas met gouden kettingband, vooraanzicht\" vertelt zowel schermlezers als zoekmachines precies wat er op de afbeelding staat. Vermijd het volproppen van alt-tekst met zoekwoorden, \"koop rode leren tas beste rode leren crossbodytas aanbieding\" is spam en niet behulpzaam.\n\nVoor productpagina's met meerdere afbeeldingen (voorkant, achterkant, detail, lifestyle) varieer je de alt-tekst om elke specifieke weergave te beschrijven. Dit creëert meerdere mogelijkheden om te ranken in beeldzoeken voor verschillende zoekopdrachten. De lifestylefoto van iemand die de tas draagt in een cafe kan ranken voor \"crossbodytas outfit\" terwijl de detailfoto rankt voor \"gouden kettingband tas\".",
        },
        {
          title: "UX-signalen die productpagina-rankings beinvloeden",
          content:
            "Google meet hoe gebruikers omgaan met je productpagina's na het klikken vanuit zoekresultaten. Hoge bouncepercentages, korte tijd op de pagina en pogo-sticking (terugklikken naar zoekresultaten en een andere vermelding kiezen) geven allemaal aan dat je pagina niet voldeed aan de zoekintentie. Deze gedragssignalen beinvloeden rankings in de loop van de tijd, wat betekent dat UX en SEO diep verbonden zijn op productpagina's.\n\nPaginasnelheid is de meest meetbare UX-factor. Productpagina's overladen met ongecomprimeerde afbeeldingen, overmatig JavaScript en third-party trackingscripts laden vaak 4-6 seconden op mobiel. Googles Core Web Vitals, Largest Contentful Paint, Interaction to Next Paint en Cumulative Layout Shift, meten direct laadprestaties, interactiviteit en visuele stabiliteit. Wij richten ons op minder dan 2,5 seconden voor LCP, minder dan 200ms voor INP en minder dan 0,1 voor CLS op alle productpagina's.\n\nMobiele bruikbaarheid is even kritisch. Meer dan 60% van het ecommerce-verkeer komt van mobiele apparaten, en een productpagina die moeilijk te navigeren is op een telefoon verliest zowel rankings als verkopen. Tikdoelen moeten groot genoeg zijn voor duimen, productafbeeldingen moeten inzoombaar zijn en de toevoegen-aan-winkelwagen-knop moet zichtbaar zijn zonder overmatig scrollen. Test elke productpagina-template op echte mobiele apparaten, niet alleen met browserresizetools.\n\nVertrouwenselementen verlagen bouncepercentages en verhogen de verblijftijd. Zichtbare verzendkosten, retourbeleid, beveiligingsbadges en klantreviews geven kopers redenen om op de pagina te blijven in plaats van terug te springen naar zoekresultaten. Een productpagina die onmiddellijk antwoord geeft op \"hoeveel kost verzending\" en \"kan ik dit retourneren\" houdt gebruikers betrokken, wat positieve signalen stuurt naar Google over de kwaliteit en relevantie van je pagina.",
          items: [
            "Richt op LCP onder 2,5 seconden, INP onder 200ms en CLS onder 0,1 voor alle productpagina's",
            "Zorg voor mobiele bruikbaarheid met inzoombare afbeeldingen, grote tikdoelen en zichtbare CTA's",
            "Toon verzendkosten, retourbeleid en vertrouwensbadges boven de vouw",
            "Neem klantreviews op om verblijftijd te verhogen en bouncepercentages te verlagen",
          ],
        },
      ],
      navLabels: {
        previous: "Seizoensgebonden zoekwoordtrends",
        next: "Categoriepagina SEO",
      },
    },
  },
};
